### ISSUE TITLE
[feat] Better defaults for npx tauri init

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#10019]
### Describe the problem

I regularly use npx tauri init to test Tauri APIs, but every time I create a new project, it forces me to fill in these values:

```console
➜  sample npx tauri init
✔ What is your app name? · default name
✔ What should the window title be? · default name
✔ Where are your web assets (HTML/CSS/JS) located, relative to the "<current dir>/src-tauri/tauri.conf.json" file that will be created? · no src files!
✔ What is the url of your dev server? · no server
✔ What is your frontend dev command? · no cmmand
✔ What is your frontend build command? · no command
    Warn Tauri dir ("/Users/user/Documents/sample/src-tauri") not empty. Run `init --force` to overwrite.
➜  sample 
```
Can you provide better default values and even skip prompts for inputs that are not used? For example, I don't use a dev server, URL, or build command.

### Describe the solution you'd like

Provide better defaults and allow skipping if empty

### Additional context

I don't use server at all, so every time I init the project I need to edit `tauri.conf.json` and remove the build section

**Comment by amrbashir** [comment]
> I regularly use npx tauri init to test Tauri APIs

I would recommend to use `npm create tauri-app` instead, which can be used to bootstrap a quick project that is setup correctly so you don't have to answer all the questions of `tauri init`. You can also use this single command without any prompts `npm create tauri-app -- -- -t vanilla -m npm test-app`


> Can you provide better default values and even skip prompts for inputs that are not used? For example, I don't use a dev server, URL, or build command.

`tauri init` does try to load better defaults for your current project, but ofc not the most perfect, However it should be good in most cases. The problem is if you're using a vanilla or unknown frontend configuration, `tauri init` can't determine if you're using a devServer or not, or if you need a beforeDevCommand or not and thus we can't skip these values, we need you to confirm that you're not using these things.

I would recommend using `npm create tauri-app` as I mentioned above
