### ISSUE TITLE
println don't show in the terminal and how to turn off the ios info(too much) .

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#10090]
### Describe the bug

![image](https://github.com/tauri-apps/tauri/assets/70792885/9e73dd91-2e76-4e03-8207-03a3b52a2d8f)

### Full `tauri info` output

```text
➜  app git:(0.7.0) cargo tauri info  

[✔] Environment
    - OS: Mac OS 14.5.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.14.0
    - pnpm: 9.4.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.20
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams: None
```

**Comment by pewsheen** [comment]
The device log seems not able to be disabled now because it's hardcoded: https://github.com/tauri-apps/cargo-mobile2/blob/46c0a4209bafa456ce1fca2ea0265c382a1f21bb/src/apple/device/simctl/run.rs#L74-L77

For the `println`, `stdout` from the application is somehow suppressed while running. What I did before was use `NSLog` to let it print to the log. If you want to try `NSLog`, here's a reference https://github.com/pewsheen/nslog-rs/blob/main/src/lib.rs . But I think there must be a better way to achieve it.

**Comment by FabianLars** [comment]
> But I think there must be a better way to achieve it.

You can use tauri-plugin-log and the `log` crate.
