### ISSUE TITLE
[feat] 2.0: decouple Rust build from iOS Xcode Script phase

### ISSUE THREAD

**Issue by MikeChongCan** [tauri-apps/tauri#10191]
### Describe the problem

like many issue e.g. #6573

folks are facing many Xcode related problems because by default Xcode is using `/bin/sh` which is far from commonly used shell.

Meanwhile, it is hard to find out a way to build the static lib first then use Xcode to build the host app only.

```
> tauri "ios" "build" "-h"

Build your app in release mode for iOS and generate IPAs

Usage: pnpm run tauri ios build [OPTIONS]

Options:
  -d, --debug                        Builds with the debug flag
  -v, --verbose...                   Enables verbose logging
  -t, --target [<TARGETS>...]        Which targets to build [default: aarch64] [possible values: aarch64, aarch64-sim, x86_64]
  -f, --features [<FEATURES>...]     List of cargo features to activate
  -c, --config <CONFIG>              JSON string or path to JSON file to merge with tauri.conf.json
      --build-number <BUILD_NUMBER>  Build number to append to the app version
  -o, --open                         Open Xcode
      --ci                           Skip prompting for values [env: CI=]
  -h, --help                         Print help (see more with '--help')
  -V, --version                      Print version
```

### Describe the solution you'd like

Allow two modes:

1. Integrated build with zero configuration: current state

2. Separate Rust static lib build (.a) and the host app build

**Comment by ghost** [comment]
I'll give this a go, it would help my current project at work tremendously. Not sure what the ideal solution would be yet because it would require generating the project without the Build Rust Code phase, but Xcode provides a bunch ofvariables necessary to build the lib so I'm not sure decoupling the xcode-script phase is worth it in the end. Although I'm interested to figure out how we can relieve the pain points.

For what it's worth @imWildCat, you can always get by by creating symlinks from the required binaries location to /usr/local/bin.

EDIT:
Alright so after spending some time looking into this, It does indeed seem to me like having xcode execute the script is the best course of action because xcode will provide a bunch of information required to compile the library. These information change depending on the target, so decoupling both seems it would actually make things more complicated.

**Comment by MikeChongCan** [comment]
@mrguiman thanks!

> best course of action because xcode will provide a bunch of information required to compile the library

I don't think there're a lot information required. in the worse case, we can always assume some env vars for the "standalone" mode of compilation.

This could address many pain points. For example, the current blocker for me to upload the release build of `.ipa` to the App Store is that it is not properly signed

**Comment by ghost** [comment]
@imWildCat for this you can use the --open option (cargo tauri ios build - -open). it does require manual steps but it will allow you to go through with uploading to the app store, we just released that way this week

**Comment by MikeChongCan** [comment]
> cargo tauri ios build --open

🫡 thank you so much, @mrguiman !

**Comment by MikeChongCan** [comment]
interesting it does not seem to work in my case

<img width="734" alt="image" src="https://github.com/user-attachments/assets/16acccd9-fc77-44b2-8d3a-265cfe01dbef">

**Comment by MikeChongCan** [comment]
oh never mind!

the Xcode project previously included the `.a` from debug builds...

**Comment by lucasfernog** [comment]
I'll close this issue, as mentioned before decoupling causes all sorts of issues and would degrade the DX. Using the `--open` flag is the recommended way to use Xcode and Android Studio.
Let us know if you face any other issue :)

**Comment by MikeChongCan** [comment]
make sense! thank you!
