### ISSUE TITLE
[feat] ArrayBuffer interface

### ISSUE THREAD

**Issue by notdanilo** [tauri-apps/tauri#10226]
### Describe the problem

The most optimal way to send binary data to the web-view is by exposing an interface for ArrayBuffer. This is extremely important for interfacing with WebGL/WebGPU and other APIs where real-time data streaming is mandatory. Tauri lacks such feature.

### Describe the solution you'd like

Expose an interface to get a handle to a ArrayBuffer object with methods for reading and writing the underlying data.

### Alternatives considered

Reference for current alternatives:
https://github.com/tauri-apps/tauri/discussions/5511
https://tauri.app/v1/guides/features/command/

**Comment by FabianLars** [comment]
This is really outside of our hands. Only WebView2 (the webview used on Windows) supports shared memory, and a single platform is _currently_ not enough for any of the team members to invest time into this.

Fwiw, if we end up switching to cef on Linux (and maybe offering it as an option on macos) we still won't be closer to that, because cef doesn't have shared memory either.
