### ISSUE TITLE
[feat] 使用tauri中怎么隐藏状态栏图标

### ISSUE THREAD

**Issue by Sunrisies** [tauri-apps/tauri#10253]
### Describe the problem

在window11电脑上面怎么隐藏这个状态栏图标

### Describe the solution you'd like

在window11电脑上面怎么隐藏这个状态栏图标

**Comment by FabianLars** [comment]
So i'm not sure what exactly you're asking for (please send a screenshot if my answer below doesn't cover it) because the translator was a bit vague.

If you want to hide the app from the taskbar, you can use the [`skipTaskbar`](https://tauri.app/v1/api/config/#windowconfig.skiptaskbar) window config.

If you want to hide the icon in the system tray you can only _destroy_ it in v1 like this ```rs
app_handle.tray_handle().destroy();
```
This will require you to create a new tray icon from scratch if you want to show it instead.

In v2 you can also hide it via ```rs
if let Some(tray_handle) = app_handle.tray_by_id("main") {
  tray_handle.set_visible(false);
}
```

**Comment by Sunrisies** [comment]
好的，问题已经解决了，谢谢

**Comment by ayangweb** [comment]
@FabianLars Hey👋, if you want to `destroy` and then want to show the tray again how do you implement this in v1? The link below is the version I implemented, but after the second call to `init_tray`, no menu is displayed when the tray is clicked!

https://github.com/EcoPasteHub/EcoPaste/blob/f072c4f3f4a3a001d811c74caf108a361a2a7d43/src-tauri/src/plugins/tray.rs#L111

https://github.com/user-attachments/assets/de18faf5-f599-4c35-83b8-7d167e5caf46

**Comment by FabianLars** [comment]
@ayangweb On first glance your code looks alright so it may be a bug in Tauri. Would it be possible to create a minimal reproduction example for the team to check out? Would make triaging much easier. Please open a new issue then :)

**Comment by ayangweb** [comment]
> @ayangweb On first glance your code looks alright so it may be a bug in Tauri. Would it be possible to create a minimal reproduction example for the team to check out? Would make triaging much easier. Please open a new issue then :)

After testing, it seems to be caused by using a third-party menu bar management software, and other apps can have the same problem!

<img width="181" alt="image" src="https://github.com/user-attachments/assets/f461f8a4-96d6-463c-9dbd-83d182d8165e">

**Comment by FabianLars** [comment]
Ah okay! Glad to see it's not our fault for once 😂

**Comment by ayangweb** [comment]
> Ah okay! Glad to see it's not our fault for once 😂

Since it runs stable in Windows, I suspect a software conflict may be causing the problem. I'll keep asking questions if I have another problem in the future!
