### ISSUE TITLE
Clean up stale binary after name change with windows msi updater

### ISSUE THREAD

**Issue by pierremtb** [tauri-apps/tauri#10355]
Recent beta builds are no longer renaming the binary in a bundle to `productName`, keeping the rust crate name.

The issue we're facing at KittyCAD/Zoo is that running the updater installs our new `zoo-modeling-app.exe` binary (new name) in the `Zoo Modeling App` directory, but doesn't remove the existing `Zoo Modeling App.exe` (old name), leaving it stale for the user to potentially get confused about.

![image](https://github.com/user-attachments/assets/ee18444e-f01d-43a5-ba84-19a6d8dd8433)

Is there a hook we could use to run some type of clean up script for that stale executable as we forge ahead with the tauri dependency bump that requires this binary executable name change? I'm assuming other tauri users would be in the same boat as the rust crate names are much more restrictive on what characters they allow (for instance, no space).

Thank you!

**Comment by lucasfernog** [comment]
NSIS has installer [hooks](https://github.com/tauri-apps/tauri/pull/9731) but I think this one should be handled by us @amrbashir

**Comment by olexiyb** [comment]
I feel it was a mistake to use package name instead of productName from tauri.conf.json
With old approach if you need to install multiple versions to test them separately on Windows it used to be

"Sanctum Dev"
"Sanctum Beta"
"Sanctum"
The [commit](https://github.com/tauri-apps/tauri/commit/265c23886ee5efbcc6d7188ff5c84cb32fa82aea) brakes 
* support of multiple version on windows
* support of human named link on windows

![image](https://github.com/user-attachments/assets/f83a75d1-ee9a-4224-96e5-91989d3a5b01)

**Comment by jjh42** [comment]
I agree it's nice to have an easy way of setting beta/dev names so they can be installed alongside release versions.

**Comment by tweidinger** [comment]
Related for tracking: 
- https://github.com/tauri-apps/tauri/issues/10548
- https://github.com/tauri-apps/tauri/pull/9375
- https://github.com/gitbutlerapp/tauri/pull/1

**Comment by lucasfernog** [comment]
Closed by https://github.com/tauri-apps/tauri/pull/10962 and https://github.com/tauri-apps/tauri/pull/10967
