### ISSUE TITLE
[bug] Inconsistent emit and listen results between windows

### ISSUE THREAD

**Issue by A-kirami** [tauri-apps/tauri#10450]
### Describe the bug

I encountered an issue with communication between multiple windows. When window A emits an event and window B listens for the event, the data received by window B is sometimes different from what window A emitted.

![preview-window](https://github.com/user-attachments/assets/f4d5d6e1-a1e3-417b-a5fa-808cc8afafdd)

### Reproduction

https://github.com/A-kirami/tauri-app-window

### Expected behavior

The data received by window B should be identical to the data emitted by window A.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - pnpm: 9.6.0
    - yarn: 3.6.1
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.25
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.16
    - @tauri-apps/cli [NPM]: 2.0.0-beta.23

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by chippers** [comment]
This seems to be a problem with your own frontend code, not the events API. There are two things going wrong here, the first one is that you are using `listen` for the event instead of `once`, causing old listeners to fire their old uuids. The second is that sometimes your button submits multiple times and so 2 versions of it are running at the same time, sometimes causing only the "first" value generated getting to the spawned window instead of the second.

The fix to the first one is just to change `window.listen('preview-window-created', /* ... */)` to `window.once('preview-window-created', /* ... */)`. The second one can be fixed by allowing only a single instance of the function generating the uuid to be ran at a time.

```js
let running = false;
async function createPreviewWindow() {
  if (running) return;
  running = true;

  /* ... */

  window.once('preview-window-created', async () => {
    await window.emit('set-preview-content', { uuid, uuids })
    running = false
  })
}
```

on a side note, i don't know if vue ref's are safe to serialize and deserialize with json, because one of the keys to the object laying beneath it gets turned to `[object Object]` -> `"dep": Object {"[object Object]": Number(32)}`
