### ISSUE TITLE
[bug] Cannot execute cmd command correctly in dev mode

### ISSUE THREAD

**Issue by RSS1102** [tauri-apps/tauri#10452]
### Discussed in https://github.com/tauri-apps/tauri/discussions/10446

<div type='discussions-op-text'>

<sup>Originally posted by **RSS1102** August  1, 2024</sup>
I use **Tauri's** ` use std:: process:: Command` I tried to change the registry of npm successfully, but the registry obtained is still the one before starting **Tauri**
1. starting **Tauri** (The current npm registry is https://registry.npmjs.org)；
2. set
```rs
    let _= Command::new("cmd")
        .args(&["/C", "npm config set registry http://mirrors.cloud.tencent.com/npm"])
        .output()
        .expect("failed");
```
3.get **(At this moment, what I have obtained is https://registry.npmjs.org)**
```rs
    let output = Command::new("cmd")
        .args(&["/C", "npm config get registry"])
        .output()
        .expect("failed");

    let version = String::from_utf8_lossy(&output.stdout);
    return version.to_string();
```
But after I closed **Tauri ** and ran 'npm config get registry' again, what I got was http://mirrors.cloud.tencent.com/npm

So was this environment variable set by npm cached when **Tauri** started?

</div>

---

But after I build and install, I can go to 'npm config set registry `http://mirrors.cloud.tencent.com/npm` Afterwards, execute `npm config get registry` correctly.

1. Why can dev mode only retrieve previous values in the **same situation**, but build can always retrieve them correctly.
2. By the way, why does a cmd pop-up appear when executing the cmd command after build&install, but not when executing the cmd command in dev mode

![image](https://github.com/user-attachments/assets/b605a2cc-2d10-4659-9584-4a495eb58a85)

**Comment by chippers** [comment]
Not sure why you are using `cmd /C "<command>"`, you should be able to just use npm directly if it is in your PATH (which it probably is since cmd can find it). Only thing i could see that not working with is if you have project local npm PATHs and not a global one.

Try:
```rust
let _ = Command::new("npm")
        .args(&["config", "set", "registry", "http://mirrors.cloud.tencent.com/npm"])
        .output()
        .expect("failed");
```

(and for the config get also)

That should fix both your problems. Otherwise if you need to spawn cmd for some reason the below applies

1. Afaik the config gets stored in a file at `$HOME/.npmrc`, so it shouldn't be dependent on env vars. if this file doesn't exists when you run it on windows, then maybe windows behaves differently. i dont have a windows machine on hand to test it out on right now.


2. That might be due to setting the windows_subsystem to windows on non-debug binaries. I haven't played around with calling cmd from gui apps on windows before. You might be able to try...

```rust
const CREATE_NO_WINDOW: u32 = 0x08000000;
let output = Command::new("cmd")
  .args(&["/C", "npm config get registry"])
  .creation_flags (CREATE_NO_WINDOW)
  .output()
  .expect("failed");
```

based on [the `CommandExt` docs](https://doc.rust-lang.org/stable/std/os/windows/process/trait.CommandExt.html#tymethod.creation_flags).

**Comment by RSS1102** [comment]
🤓🤓Thank you very much. For using `Command:: new ("npm")`, it is possible that the user's installed `npm` address is unknown(in Windows). I have tried many times but have not been successful. So I tried to directly use cmd to mimic user operations and obtain npm information.

`Setting the windows_subsystem to windows on non debug bins has been very helpful to me. Thank you.

**Comment by RSS1102** [comment]
Regarding this issue, I am currently only focusing on Mac and may continue to explore it in the future.
Thanks again😘😘
