### ISSUE TITLE
[bug] macOS permissions are not stored between updates

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#10567]
### Describe the bug

I have v2 project that records the screen on macOS.
When download new version of the app from Github releases and installing, the app request for permissions again.
Morever, it's very confusing since there's need to remove the previous permission of the same app before we can allow it again.

### Reproduction

Download Vibe version 2.2.0 
https://github.com/thewh1teagle/vibe/releases/tag/v2.2.0
Click on record. Allow the permission. restart the app.
Record again without permission.

Download then 2.4.0
https://github.com/thewh1teagle/vibe/releases/tag/v2.2.0
Repeat the process. you will see that it prompt for permission again and hard to allow it.

### Expected behavior

It shouldn't prompt twice. And also it should be easier to fix it if it does prompt

### Full `tauri info` output

```text
macOS aarch64 
tauri = { version = "2.0.0-beta.25", features = ["protocol-asset", "devtools"] }
tauri-build = { version = "=2.0.0-beta.19", features = [] }
```

### Additional context

When updating through updater it's ok. but sometimes users needs to update manually. rarely but happens. It also affect development experience.

---
P.S: it's hard for me to get tauri info since I build it on CI. Let me know if more information is needed.

**Comment by FabianLars** [comment]
As far as i know this can only be fixed by signing the app with an actual certificate (using the same one for each update - 99% sure that ad-hoc signing doesn't count). A quick google search suggests the same, including [official docs](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html) (all the way at the bottom).

In regards to "Additional context": Not exactly sure what makes the updater work, other than this being a mis-observation or a system fluke but since the "issue" is expected macOS behavior i'll close this issue.
