### ISSUE TITLE
writeBinaryFile **DOES NOT WORK** even though correct USAGE! [2021 ISSUE]

### ISSUE THREAD

**Issue by copyandexecute** [tauri-apps/tauri#1133]
Dear Tauri Team,
I am trying to download a jar file and then save it with your provided funcation "writeBinaryFile". Unfortunately it does not work.

 ```
 await axios({
          url: '/downloads/client/latest.jar',
          method: "GET",
          responseType: "blob", // important
          onDownloadProgress: (progressEvent) => {
            setProgress(Math.round((progressEvent.loaded * 100) / progressEvent.total));
          }
        }).then(async value => {
          const mcDir = await promisified({cmd: "minecraftDir"});
          console.log(mcDir)
          console.log(value)
          console.log(value.data)
          await writeBinaryFile({contents: value.data, path: mcDir + "/norisk/test.jar"}, {});
        })
```

It creates an EMPTY + CORRUPTED File.
Whats the correct use?

Your sincerely,
Max

**Comment by zakpatterson** [comment]
The issue is basically that [writeBinaryFile in the JS api](https://github.com/tauri-apps/tauri/blob/d7b343e8c8ffe0f87c3bdf9f73c3b926b2bf24eb/cli/tauri.js/api-src/fs.ts#L157) does not call [WriteBinaryFile in the rust API](https://github.com/tauri-apps/tauri/blob/d7b343e8c8ffe0f87c3bdf9f73c3b926b2bf24eb/tauri/src/endpoints.rs#L62), but instead calls [WriteFile in the Rust API](https://github.com/tauri-apps/tauri/blob/d7b343e8c8ffe0f87c3bdf9f73c3b926b2bf24eb/tauri/src/endpoints.rs#L50) with the file contents base64 encoded. So you may find, that your jar file that is saved in your filesystem is fine, it just needs to be base64 decoded, as `base64 -d corrupted_file > good_file`. 

I am working on a fix now.

**Comment by zakpatterson** [comment]
@copyandexecute You might try pulling down the `dev` branch and making sure your issue is resolved? Otherwise I think a new release is coming out soon with this fix. Thanks
