### ISSUE TITLE
[bug] Icons of dragged item get stuck on the screen after being dropped on Xorg

### ISSUE THREAD

**Issue by JuTonic** [tauri-apps/tauri#11343]
### Describe the bug

When dragging files on Xorg, the icon of a file does not disappear after being dropped and gets stuck on the screen until reboot.

[Запись экрана от 2024-10-13 16-12-51.webm](https://github.com/user-attachments/assets/453f8e8d-3522-47bd-add9-356312154b3e)

### Reproduction

Use Xorg. Create a standard svelte template, put this to `src/routes/+page.svelte` run dev server and drop a file to the app.

```{svelte}
<script lang="ts">
    import { listen } from "@tauri-apps/api/event";

    listen("tauri://drag-drop", (e) => {
        console.log(e);
    });
</script>

<div>drag file here</div>
```

### Expected behavior

Icon should disappear after file is dropped

### Full `tauri info` output

```text
[✔] Environment
    - OS: Artix Linux Unknown x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.1
    ✔ rsvg2: 2.59.1
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (2024-05-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.9.0
    - pnpm: 9.6.0
    - yarn: 1.22.22
    - npm: 10.9.0
    - bun: 1.1.27
    - deno: deno 1.45.5

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.0
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

I am using Artix linux with GNOME 47. The issue was also encountered on Ubuntu 24.4.0 x86_64 (X64) (see https://github.com/tauri-apps/tauri/issues/11282#issuecomment-2408965270).

It may be a problem of the latest GNOME release? Currently, I cannot probe it on kde or older GNOME versions, so additional testing is needed.

**Comment by jb-alvarado** [comment]
Hi, I just wanted to confirm that this problem also occurs under Fedora 41 with Gnome 47.

But here are some more things I found out:
1. The problem is not related to the events. You can remove them and drop a file on the window and the icon will stick.
2. With the option `"dragDropEnabled": false` the problem disappears, but of course dragging in general does not work any more, and the files are only opened in the webview.
3.  The interesting thing is that when I open the Gnome web browser and drop a file into it, the file also stays on the screen, and a few seconds later Gnome Web crashes.
 
A small update:

I had some graphics related updates (nvidia, mesa, etc.) and after I found out that I had X11 active, which is strange because some months ago I switched to wayland. Then I enable wayland again and after that I'm able to drag&drop files into the Gnome web browser. But now when I drag&drop files into my tauri application it opens the file as if `dragDropEnabled` is set to false. Somehow the **drag-drop** event is not responding. **drag-enter** and **drag-leave** work as they should.

Next update:

[Patch](https://github.com/tauri-apps/tauri/issues/11282#issuecomment-2452933189) from @amrbashir works!

**Comment by amrbashir** [comment]
I opened a PR to fix the dragged icons getting stuck, can you guys confirm the fix by adding the following in your `src-tauri/Cargo.toml`
```toml
[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/linux-gnome-drag-icons" }
```
then run `cargo update -p wry` inside `src-tauri`

**Comment by metdxt** [comment]
Yep, this fixes icons for me. Gj!
