### ISSUE TITLE
[bug] (v2 Shell) Command spawn hanging in production

### ISSUE THREAD

**Issue by EvilStew** [tauri-apps/tauri#11513]
### Describe the bug

When running in production, the spawn() function seems to be hanging on Windows. The problem is intermittent and seems to be happening in production only. All is fine in dev mode.

I made a small app from the default template with examples for easy reproduction.

Let me know if you have more questions this is my first ever submitted issue. I searched other issues and I see this one that could be related, but I'm not sure since it's not escaped for me and don't happen all the time: https://github.com/tauri-apps/tauri/issues/11427

### Reproduction

https://github.com/EvilStew/tauri-commands-viewer

Follow README for instructions including commands you can try. Note that you must build to production and try multiple commands / applications restarts. If you don't do the arguments part correctly, the Command error should be printed in the textarea.

### Expected behavior

The spawn function should always return an output (if asked) or an error if there's an error.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 x86_64 (X64)
    ✔ WebView2: 129.0.2792.89
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.9.0
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by amrbashir** [comment]
I tried your repro and every combination of args, seem to work as expected.

The only thing I noticed that would make your repro hang on `Loading...` is that if you're using `cmd` and pass `dir` (or any other command) without also passing `/c` at the start. This indeed hangs on `Loading...` but that's because spawning `cmd dir` is different than `cmd /c dir`.

The first one will spawn a `cmd` process and waits for inputs on its stdin, while the later will execute the `cmd` process with `dir` command and then returns.

You can try both variants in your terminal and observe the behavior.
