### ISSUE TITLE
[docs] How to launch appimage with wayland?

### ISSUE THREAD

**Issue by Isolyth** [tauri-apps/tauri#11790]
I've noticed that when running via npm run tauri dev, my program launches with wayland - great! But when I run my appimage, it defaults to X, which results in poor scaling. It doesn't seem to be documented anywhere how I can run this with wayland? Is there some variable I can set or an option in the config? The only mentions to wayland in the docs are in regards to flatpack and snap packages.

**Comment by FabianLars** [comment]
There isn't a direct way because it's [harcoded](https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/blob/master/linuxdeploy-plugin-gtk.sh#L243) because gtk crashes for many users if run inside appimages.
I disabled that once for a test and we ended up with issues like https://github.com/tauri-apps/tauri/issues/8541

I _think_ you can maybe overwrite it in rust by adding this above the tauri::Builder line
```rs
std::env::set_var("GDK_BACKEND", "wayland");
```

**Comment by Isolyth** [comment]
I don't understand, why can it run in dev mode with Wayland but not when compiled into an appimage? That issue mentions that GTK isn't expecting an anti aliasing setting, why can't that be removed for the Wayland version?

**Comment by FabianLars** [comment]
> I don't understand, why can it run in dev mode with Wayland but not when compiled into an appimage?

appimages are pretty hacky, so there are many things that don't work well inside of it (making webkitgtk work inside it is absolute hell btw)

> That issue mentions that GTK isn't expecting an anti aliasing setting

probably only one of the issues, i don't think that's why the setting was hardcoded upstream

> why can't that be removed for the Wayland version?

well, if anyone can tell me how? 🙃 This may come from webkitgtk directly and not our own use of gtk

**Comment by flusterIO** [comment]
I know this is old, but has anyone found a solution for a universal Linux setup? I'm currently working on [Fluster](https://github.com/flusterIO/fluster), but I'm running into issues with users on Linux systems, with some getting stuck with a white screen when using wayland without xwayland (I'm a mac fanboy... I'm just relaying what they've passed on to me). Has anyone ran into a similar issue, and if so how did you solve it?

**Comment by FabianLars** [comment]
so far i got pretty positive feedback on https://github.com/tauri-apps/tauri/pull/12491 but i didn't get to the docs yet Ifor example it shouldn't be built on ubuntu but on arch or similar). also it's "just" a better appimage than the current one and still using webitgtk so it's still far from a perfect solution (not that even exists on linux).
