### ISSUE TITLE
Pass messages between Rust frontend and backend without JSON serialization

### ISSUE THREAD

**Issue by JakubKoralewski** [tauri-apps/tauri#1271]
**Is your feature request related to a problem? Please describe.**

https://tauri.studio/en/docs/guides/command mentions:

> Tauri by default serializes every message to a JSON string, so you can use serde_json on the backend to deserialize it.

But if I write my frontend in Rust and use Rust for handling the commands the in-between step of converting a Rust struct into JSON and back again seems redundant. 

**Describe the solution you'd like**
Maybe something like https://github.com/servo/bincode could be used for message passing instead.

**Describe alternatives you've considered**
Would [`mpsc`](https://doc.rust-lang.org/std/sync/mpsc/) work?

**Additional context**
Moved from https://github.com/tauri-apps/tauri/discussions/1268#discussioncomment-391719

**Comment by tensor-programming** [comment]
I wonder if this even would work this way.  If the Rust generates JavaScript, then it will go through the Tauri event manager, but if its generating WASM then I suspect it would not go through the event manager and that there would be no serialization.

**Comment by nanashj** [comment]
https://github.com/nanashj98

**Comment by Boscop** [comment]
+1 for binary payloads. It seems this is currently blocked upstream by https://github.com/MicrosoftEdge/WebView2Feedback/issues/1005
But I'm also very much looking forward to this.
In my app, I'm using websockets with binary payloads between Rust backend and frontend (for both directions), because JSON was too slow.
The app is sending lots of data and needs to visualize it with lowest possible latency.

**Comment by lucasfernog** [comment]
This is possible using a custom invoke system such as [tauri-invoke-http](https://github.com/tauri-apps/tauri-invoke-http). We will investigate an IPC refactor for tauri v2.

**Comment by schickling** [comment]
> This is possible using a custom invoke system such as [tauri-invoke-http](https://github.com/tauri-apps/tauri-invoke-http). 

Is `tauri-invoke-http` still actively maintained? The dependencies seem rather outdated.

> We will investigate an IPC refactor for tauri v2.

Shouldn't this issue stay open until then or is there another tracking issue for this?

**Comment by JonasKruckenberg** [comment]
> Is `tauri-invoke-http` still actively maintained? The dependencies seem rather outdated.

As much as two volunteers with other responsibilities in the Tauri org can maintain like 30 different plugins it's still maintained yes. If we decide to deprecate a plugin we will archive the corresponding repo. But because of severe lack of time we're currently focusing our efforts on the most popular plugins. Plugins that aren't as requested will therefore see a bit of neglect. I hope this is understandable.

> > We will investigate an IPC refactor for tauri v2.

This issue was concerned with using a different serialization, and that is currently out of scope for any IPC refactors. (Due to webview limitations we're a bit stuck with to-string serializations)
I've been thinking about a possible workaround for this, but it hasn't progressed much further than a few messages on discord yet.

**Comment by ghost** [comment]
How did you guys even get the Rust–Wasm–Rust bridge to work without JS? I'm trying to use a common IPC API types lib crate to share between front- and backend Rust, like so:
```rs
#[wasm_bindgen]
pub struct Msg1 { ... }
#[wasm_bindgen]
pub struct Msg2 { ... }
#[wasm_bindgen]
pub struct Msg3 { ... }

#[wasm_bindgen]
pub enum Msg {
    Msg1(Msg1),
    Msg2(Msg2),
    Msg3(Msg3),
}
```

and use it in server:
```rs
#[tauri::command]
fn handle_msg1(msg1: Msg1) {
    // ...
}
```

and use it in client:
```rs
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["window", "__TAURI__"])]
    fn invoke(s: &str, msg: Msg);
}

#[wasm_bindgen(start)]
fn main() {
    let msg1 = Msg::Msg1 {
        // ...
    };
    invoke("handle_msg1", msg1);
}
```

but this doesn't work for multiple reasons. But I think the idea that I'm trying to go for is clear. How do I achieve this?
