### ISSUE TITLE
tauri init: include a .gitignore file?

### ISSUE THREAD

**Issue by MikeChongCan** [tauri-apps/tauri#1423]
**Is your feature request related to a problem? Please describe.**

While using `tauri init` to create a new project, a recommended `.gitignore` file could be needed since the project is kinda special compared to a normal JS/Rust project.

**Describe the solution you'd like**

something like
```.gitignore
node_modules/
src-tauri/target
```

**Describe alternatives you've considered**
Not sure about this.

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by nklayman** [comment]
`tauri init` already adds a `.gitignore` file inside of the `src-tauri` directory ([see file here](https://github.com/tauri-apps/tauri/blob/dev/cli/core/templates/src-tauri/.gitignore)). We don't add one in the root of the project because it is expected that the user already has one. We don't want to assume that the developer is using npm, or any other frontend tool. `tauri init` should purely init Tauri, not configure anything about the developer's web project.
