### ISSUE TITLE
Consider using BSON rather than JSON

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1573]
**Describe the solution you'd like**
A feature gate that allows one to depend on [mongodb/js-bson](https://github.com/mongodb/js-bson) and [mongodb/bson-rust](https://github.com/mongodb/bson-rust) for better efficiency in writing, reading and transmitting arbitrary data to the webview.

**Describe alternatives you've considered**
JSON - it takes up a lot of memory, since it has to be UTF-8, and is considerably slower to parse than a "binary" format!

**Additional Context**
As a higher level implementation, it may be useful to abstract away the underlying data serialization format, and re-exporting proxies to it.

For example, there should be a Tauri equivalent of the `json!` macro from serde_json, which will return a value based on the chosen feature-gated serialization format, meaning developers can easily swap serialization formats if they so desire.

**Comment by nothingismagick** [comment]
I would like to see some real evidence of this, especially in the context of message passing within a javascript engine. Do you have resources to back up your claims? Will abstracting the data serialization and then proxying and serializing and then deserializing and then proxying on the other side be THAT much faster? In what circumstances?

Again, I think that this should be very carefully weighed, because every ounce of complexity we add to tauri turns into thousands of hours of maintenance and review and upkeep over the next ten years of this open source project. Who is going to maintain it?

**Comment by nothingismagick** [comment]
related: https://github.com/tauri-apps/tauri/issues/1271

**Comment by lucasfernog** [comment]
We won't implement but in v1 you can use custom invoke systems (example: https://github.com/tauri-apps/tauri-invoke-http).
