### ISSUE TITLE
Consider using a websocket for communication between the webview and Rust

### ISSUE THREAD

**Issue by WilliamVenner** [tauri-apps/tauri#1574]
**Is your feature request related to a problem? Please describe.**
JSON parsing + JavaScript evaluation can be slow, and can be considerably increased via a websocket + communication of binary formats.

**Describe the solution you'd like**
A feature gate or plugin that allows one to use a websocket to communicate webview <-> Rust.

**Describe alternatives you've considered**
Doing it myself, or sticking with JSON parsing + JavaScript evaluation.

**Additional context**
Relevant issue: #1573

**Comment by nothingismagick** [comment]
I think this should be a plugin and absolutely not part of core. My reasoning is that I don't want us to get in the habit of shipping insecure servers just because it might make things in some situations faster. 

Should this be an official plugin? I see two thought processes here:
1. YES! Because otherwise people will just do it wrong and insecurely.
2. NO! Who is going to maintain it, document it, etc.

**Comment by lucasfernog** [comment]
For security reasons we can't offer this on the core crate (it's already quite some work to handle the security aspect of the current mechanism). As Daniel said, you can write your own solution for this.

A websocket plugin sounds amazing though :P
