### ISSUE TITLE
Poor `readBinaryFile` performance via JS API

### ISSUE THREAD

**Issue by halgorithm** [tauri-apps/tauri#1817]
**Describe the bug**
`readBinaryFile` is very slow for me, taking over a second to read a 800kb local file and over a minute to read a 20MB one on my device. As a comparison, reading the 800kb file via Node's fs promises API takes less than 10ms.

**To Reproduce**
```javascript
import { readBinaryFile } from '@tauri-apps/api/fs'
const startedAt = new Date()
await readBinaryFile(filePath)
console.log(`file read in ${new Date() - startedAt}ms`)
```

**Expected behavior**
Interacting with the file system via the JS API should have acceptable performance.

**Platform and Versions**
```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 90.0.818.56

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.10.0
  yarn - 1.23.0-20210103.1434

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/.git
/.yarn
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta-rc.4
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../dist
devPath - http://localhost:3000
framework - React
```

**Comment by lucasfernog** [comment]
I just checked the performance for reading a 2.9MB file, here's the results:

debug build:
read: 360ms
serialization (serde_json): 4s

release build:
read: 40ms
serialization (serde_json): 110ms

The bottleneck is the serde_json performance on debug, there's not much we can do about it. We're investigating better Rust->JS communication on wry, so this has room for improvements (specially since it took 400ms for the message to arrive on the JS end - even on release build).

But your app is still quite fast with a release build :)

**Comment by benbenbenbenbenben** [comment]
I don't want to reopen this but I have to 🚩 it. 

tauri is serializing binary data to JSON instead of passing blobs/buffers???

Why isn't it read with a fetch get, write with a fetch post?

**Comment by amrbashir** [comment]
@benbenbenbenbenben due to some restrictions in the webview on linux, we are not able to use fetch because it lacks headers support in custom protocol but that's about to change. Webkit2gtk will add headers support in custom protocols soon, so tauri v2 will definitely have much better performance in that regard than tauri v1.

**Comment by benbenbenbenbenben** [comment]
Okay that's cool. Thanks @amrbashir. I did embed tiny-http just to see how it compared performance wise and the difference is stark. I did think longer term it would want a security token in the URL, perhaps unique per get/post... but I guess you've got his all figured out and that's something you anticipate headers will carry?

**Comment by icewind** [comment]
Maybe there is some workaround? Or the only option is to implement `fs` module manually using request without serialization? Currently it is an issue for me because on Macbook Pro late 19 it takes almost 4 seconds to read a standard photo from an iPhone(3.8 ~ 3.9Mb). It gives the user a feeling of slow and laggy application(even with async progress indicator).

**Comment by lucasfernog** [comment]
For now you can use a localhost HTTP server instead of wry's IPC system, it should have better performance: https://github.com/tauri-apps/tauri-invoke-http
Documentation and benchmark is still WIP though.

**Comment by icewind** [comment]
Thank you very much! I'll give it a try.

**Comment by FabianLars** [comment]
@icewind Keep in mind that until we rework our invoke system, tauri-invoke-http still has to serialize the binary to a json string. It's still faster than the built-in IPC tho.
If you really need the performance (and can't wait for us to fix it), you'd have to completely go the DIY route (aka no `@tauri-apps/api` and a custom ipc alternative).

Btw, i'm not recommending this, because of reasons (mainly security), just giving you the option or whatever.

**Comment by schickling** [comment]
> so tauri v2 will definitely have much better performance in that regard than tauri v1

Is there a tracking issue I can subscribe to for this? We're also hitting this limitation.

**Comment by amrbashir** [comment]
@schickling here the tracking issue of headers support on Linux https://github.com/tauri-apps/wry/issues/422
Once that is fixed, we can start overhauling the IPC system for better performance.

**Comment by schickling** [comment]
Thanks a lot @amrbashir! Would it maybe make sense to keep the current issue open to track the progress on the Tauri side?

**Comment by amrbashir** [comment]
I think opening a new issue is better.

**Comment by MountainAndMorning** [comment]
This problem still exists in the tauri 2.0.0-alpha.

**Comment by Toyking10** [comment]
This problem still exists for me

**Comment by Vilhelm-Ian** [comment]
@MountainAndMorning  and @Toyking10 the is not solved. Readbinary still has to convert the binary to json . In debug you have to use the http-invoke to send the data as a raw binary instead of what tauri does and send it as json

**Comment by FabianLars** [comment]
I assume you're not talking about v2 because http-invoke is still v1 only. I'm 99% sure that in v2 the ipc can handle raw binary without converting it to json. If that is not the case please send me a link to the code since it's something we'd have to look into before v2 gets stable.

Nothing we can do about it in v1 though, otherwise we would have fixed it there instead of doing it in v2.

Edit: By the way, as i mentioned in an older comment above, http-invoke still converts it to json (though it can send that over better nonetheless)

**Comment by Vilhelm-Ian** [comment]
@FabianLars  i did not know that http-invoke is still in v1  a lot of time has passed i just assumed it got to v2 plus the issue that was linked was closed. 

I am curious if I convert the Vec<u8> to a string and send it to the frontend as a string and at the frontend do something like data.split(" ") would it be faster than passing the Vec<u8> to serde

**Comment by MountainAndMorning** [comment]
> I'm 99% sure that in v2 the ipc can handle raw binary without converting it to json
 
Thanks for your help. Is there any example for config ipc to handle raw binary?

**Comment by FabianLars** [comment]
There's no config. Simply use the latest v2 alpha and if you send binary data, tauri should automatically handle that.
I don't know for sure how well it handles binary data nested inside objects though, so `-> Vec<u8>` vs `-> MyStruct { Vec<u8> }`
