### ISSUE TITLE
Crash when trying to get any monitor

### ISSUE THREAD

**Issue by RealDrPuc** [tauri-apps/tauri#1893]
**Describe the bug**
The execution of the program stops when I try to use primary_monitor(), available_monitors() or current_monitor().

**To Reproduce**
1. Add the following code to the Builder::default()
```
.setup(|app| {
    let window = app.get_window("main").unwrap();
    println!("This will print!");
    let _monitors = window.available_monitors();
    println!("This won't.");

    Ok(())
})
```
2. Run with yarn tauri dev.
3. See console and the program's window.
4. See that "This won't." isn't printed and the window does not respond.

**Expected behavior**
Can get monitors and, at least, not crash the program.

**Screenshots**
Images on [here (imgur link)](https://imgur.com/a/nZfLyx6).

**Platform and Versions:**
OS: Windows, version 10.0.19041 X64
Node: 16.2.0
NPM: 7.13.0
Yarn: 1.22.10
Rustc: 1.52.1
Webview2: 90.0.818.66
@tauri-apps/cli: 1.0.0-beta.1
@tauri-apps/api: Not installed

**Additional context**

**Important!**
This is the output of Tao's monitor_list example:

```
[src\main.rs:9] window.available_monitors().collect::<Vec<_>>() = [
    MonitorHandle {
        inner: MonitorHandle(
            0x0000000000010001,
        ),
    },
]
[src\main.rs:10] window.primary_monitor() = Some(
    MonitorHandle {
        inner: MonitorHandle(
            0x0000000000010001,
        ),
    },
)
```

Also, this issue applies on 2 separate Windows machines.

**Stack Trace**
I don't know how to get a stack trace, but I will happy to provide one if the issue needs it.

**Comment by Flakebi** [comment]
I get the same hang on Linux/Wayland with tauri 1.0.0-beta.1.

**Edit:** I guess this is a deadlock because tauri tries to schedule something and wait for it while we are currently in the scheduler thread. Starting a new thread and calling `current_monitor()` there creates `thread 'main' panicked at 'not yet implemented'`.

**Comment by RealDrPuc** [comment]
I can confirm this is a Tauri issue, WRY and Tao can get the monitors but Tauri can't.

The following code returns **Some(MonitorHandle { inner: MonitorHandle(0x10001) })**
```
fn main() {
  use wry::{
    application::{
      event_loop::EventLoop,
      window::WindowBuilder,
    }
  };

  let event_loop = EventLoop::new();
  let window = WindowBuilder::new()
    .with_title("Monitor Test")
    .build(&event_loop).unwrap();

  let monitor = window.current_monitor();
  println!("{:?}", monitor);
}
```

**Comment by lucasfernog** [comment]
On Linux the API is not implemented yet. I'll investigate the issue on Windows.

**Comment by lucasfernog** [comment]
The problem here is that `setup` runs before the `tao` event loop is initialized, and the `available_monitors` (and most of the other window APIs) sends a message to the event loop and waits for the response, so it's a deadlock. There's not much to do here except document this behavior on the `setup` callback.

Example code that works:

```rust
.setup(|app| {
      let window = app.get_window("main").unwrap();
      std::thread::spawn(move || {
        println!("This will print!");
        let _monitors = window.available_monitors();
        println!("This will print!");
      });

      Ok(())
})
```
