### ISSUE TITLE
Drop-in replacement of UI code written for Electron.

### ISSUE THREAD

**Issue by janakg** [tauri-apps/tauri#1914]
**Is your feature request related to a problem? Please describe.**
We have developed for Electron for 2+ years, UI works flawlessly in Chrome. For Tauri, we need to support multiple browsers for various OS, it is a time-consuming task and roadblock.

**Describe the solution you'd like**
Can the WebView lib mandate the availability of Chrome with a certain version on all platforms? And it will run only on it.

**Describe alternatives you've considered** 
Support multiple browser targets. 

**Additional context**
Also, we depend on a few chrome devtools APIs exposed via electron, so that might also be a roadblock to migrate.

**Comment by nothingismagick** [comment]
This is not a possibility, unfortunately.

**Comment by janakg** [comment]
@nothingismagick Thanks for the clarification. Just another thought.
As an option to the developer, would it be possible to repurpose PlayWright or Puppeteer as a window management tool with Chrome as its browser?

**Comment by nklayman** [comment]
@janakg that has been tried by google: https://github.com/GoogleChromeLabs/carlo

**Comment by nothingismagick** [comment]
So here is the thing, right now we are stabilizing for the following use case:

system webview + rust backend + webdriver.io test harness

Once we have a stable system with all the expected bells and whistles that runs perfectly on desktops and mobiles, then we are going to circle back and see about supporting other window types, such as pure GL contexts. We will also investigate bindings from rust to other languages like C, python, etc.

But the delivery time of these enhancements is not something I feel comfortable putting on a concrete roadmap, because there are still a few known unknowns that we need to resolve.
