### ISSUE TITLE
Can't Initialize Tauri App - Crates.io installation issue

### ISSUE THREAD

**Issue by coraunderhill** [tauri-apps/tauri#1995]
**Describe the bug**
Trying to run `npm run tauri init` results in the following error:
```zsh
[tauri:init] Tauri dir ("/Users/cora/Projects/mastodon/src-tauri") not empty. Run ``init --force template`` to overwrite.

 dependency:manager Installing missing dependencies... +0ms
 app:spawn [sync] Running "cargo generate-lockfile" +342ms

    Updating crates.io index
error: failed to select a version for the requirement `tauri = "^1.0.0-beta-rc.4"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.0, ...
location searched: crates.io index
required by package `app v0.1.0 (/Users/cora/Projects/mastodon/src-tauri)`

 app:spawn ⚠️  Command "cargo" failed with exit code: 101 +1ms`
```

**To Reproduce**
1. Complete the setup process for Mac (Homebrew, GCC, Rust, etc)
2. Run `npm run tauri init` from the project directory
3. Follow on-screen prompts

**Expected behavior**
It's supposed to actually _work_

**Screenshots**

**Platform and Versions (please complete the following information):**
```zsh
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.1 (outdated, latest: 1.0.0-beta.2)
  @tauri-apps/api - Not installed

Global packages
  npm - 7.17.0
  yarn - Not installed

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/bin
/node_modules
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta-rc.4 (no lockfile)
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../bin
devPath - 127.0.0.1
framework - React
bundler - Webpack
```

**Additional context**
Super confusing. Especially with the three different Tauri versions showing up instead of just the one I asked for :L

**Comment by lucasfernog** [comment]
Seems like the `src-tauri` dir already existed so it didn't update the dependency version. If that's the case, you can just change `1.0.0-beta-rc.4` to `1.0.0-beta.2` (and also update the tauri-build version).

Otherwise try removing the node_modules folder and trying again, you might be running an older CLI version (that has the beta-rc template).

If that doesn't work, please reach out to our community on Discord.

**Comment by Olyno** [comment]
Hi @lucasfernog 

Sorry but i have the exact same problem with  ``1.0.0-beta.10``. Here is my ``tauri info`` output:
```
Operating System - Linux, version 20.2.4 X64

Node.js environment
  Node.js - 17.0.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.0
  yarn - 1.22.15

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.vscode
/node_modules
/src
/public
/src-tauri

App
  tauri.rs - 1.0.0-beta-rc.4 (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - Svelte

Done in 5.50s.
```

We're already 3 with this issue (@coraunderhill, @jmca and me). Would be good to post a real answer to that issue instead of redirect anyone to the Discord. Also, i don't find it normal to still have this issue 6 months later after this issue has been created **and closed**. It's not a good developer experience.

Cheers, Olyno.

**Comment by lucasfernog** [comment]
`tauri.rs - 1.0.0-beta-rc.4` doesn't exist anymore, it should be `1.0.0-beta.8`. Is your project generated with the `1.0.0-beta.10` CLI version?

**Comment by Olyno** [comment]
Yes it has been, i tried to generate a new project some minutes ago, and got this error when using ``tauri dev`` with ``"@tauri-apps/cli": "^1.0.0-beta.10"``

**Comment by Nickersoft** [comment]
Would just like to chime in and add that I've been seeing this same error as well with beta.10 👋🏼

**Comment by nothingismagick** [comment]
So, as hard to believe as it may be, most of us are waging war (using the `next` branch) with security issues in order to press forward with the audit and get the release done this year.

On a hunch, I did a complete fresh install of all dependencies on a brand new mac, and ran into many problems. First of all, I would like to apologize. We haven't focussed enough on the developer experience, and we will investigate all these problems and get the basics working on all platforms asap.

**Comment by nothingismagick** [comment]
Please bear just a little bit longer with us through these teething issues.

**Comment by Olyno** [comment]
Everything I'm going to say below is just my personal opinion, but I would like to share it:

I think that the developer experience should be a priority in open source projects. If a developer takes the time to report a problem (which doesn't happen very often in my experience), we should try to listen to them and fix it.
The current problem I see is that we are a few developers to have reported this problem, and despite everything the issue remains closed. It would be nice to reopen it first so that the Tauri team, or an external contributor, can work on it and fix it as soon as possible.

This problem affects the installation at the developers, which is very problematic since without installation, there is no testing, and without testing, there is no developer feedback. This issue made me run away from Tauri more than trying it. I just wanted to go back to a project that took more resources but was much more stable when installed: electron. Note that this kind of problems during the installation are not new, I already had a similar problem a few years ago with Tauri, and I already ran away from Tauri because of that, giving it a second chance a few days ago.

Concerning Discord and the Tauri community, I prefer to go there of my own free will because I'm interested in the project than to have to go there to report a simple installation problem. I find it sad that I have to redirect the developers on there to report bugs and have a chance to get it fixed.

**Comment by nothingismagick** [comment]
You're absolutely right,

**Comment by nothingismagick** [comment]
We're working on it. I would like to remind you that we are all volunteers, and while this isn't an excuse - we're active on a lot of fronts here. Another thing you'll learn about open source projects, is that its a team effort and attitude explains a lot about the reaction your issues get.

Anyway, thanks for giving us a second chance, and I'll ping you when I think we're ready for a review of the DX.

**Comment by jasonpolites** [comment]
I came here all salty because after following the [Getting Started](https://tauri.studio/en/docs/getting-started/setup-linux) guide for the first time, ever, I hit this very issue. I then read the comments from the volunteer team, and I'm all embarrassed that I was salty 😬 

FWIW, your initial bootstrapping docs are already a lot better than Electron's. I shall await humbly and thankful for updates 😄

**Comment by jamieshepherd** [comment]
Hey. I stumbled across the same issue (Note: Windows) - and my fix was fairly straight forward. The crate versions the current @tauri-apps/cli points to no longer exist (deleted, for some reason?). To address that, go into your `Cargo.toml` file and update to the latest real versions for both

- `tauri-build` (as of writing, `tauri-build = { version = "1.0.0-beta.4" }`)
- `tauri` (as of writing, `{ version = "1.0.0-beta.8", features =["api-all"]}`)

You can find the latest versions here:
- https://crates.io/crates/tauri/versions
- https://crates.io/crates/tauri-build/versions

I then ran `cargo update` from the `src-tauri` folder, but I expect that just running the yarn or npm commands again (e.g. `yarn cargo init`) will also work. Hope this helps someone

**Comment by FabianLars** [comment]
With 1.0 stable finally released, i'm going to be a little optimistic and close this issue. Please scream at me if you still encounter this issue 🙏
