### ISSUE TITLE
ATTENTION: FEATURE FREEZE

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#2060]
For the time being (until the audit is over) we will not accept any new feature requests for 1.0 - all work is being focussed on resolving issues discovered during the audit. Please consult the [next](https://github.com/tauri-apps/tauri/tree/next) branch if you want to use upcoming features.

You can read more about the code audit here:
https://dev.to/tauri/tauri-feature-freeze-and-security-audit-1ml1

Thankyou for your understanding.

**Comment by jquesada2016** [comment]
What's the current status of the audit? I haven't been able to find updates on this.

**Comment by FabianLars** [comment]
@jquesada2016 
> I haven't been able to find updates on this.

Because we didn't provide any update :P 
It's still ongoing 🤷 Keep in mind that the audit is not just work for the auditors but for us too.
In short the process is: they audit our code -> we make changes in regard to the results -> they check our code again -> we have to merge the changes to dev together with some (not all) changes from `next` (that will be fun lol).

Giving any more specific updates on what's happening or where we are or what the deadlines are would just make it harder for me/us dealing with impatient people imho. Every oss maintainer should know which kind of people i know 😂 

Edit: closed by accident (misclick), sorry

Edit2: Also, don't forget about the holiday season and stuff 🎅

**Comment by Hadwanvelasco** [comment]
> For the time being (until the audit is over) we will not accept any new feature requests for 1.0 - all work is being focussed on resolving issues discovered during the audit. Please consult the [next](https://github.com/tauri-apps/tauri/tree/next) branch if you want to use upcoming features.
> 
> You can read more about the code audit here: https://dev.to/tauri/tauri-feature-freeze-and-security-audit-1ml1
> 
> Thankyou for your understanding.

**Comment by jquesada2016** [comment]
@FabianLars Thank you for the update, that was exactly what I was curious about. I've personally have never been involved with an audit and therefore don't know what the process is, nor the work involved.
