### ISSUE TITLE
yarn tauri init stuck on Downloading Rust CLI...

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2079]
### `yarn tauri init` is stuck on Downloading Rust CLI...
When I run the command `yarn tauri init`, it just gives me the following and exits:
```
→ yarn tauri init
yarn run v1.22.10
warning package.json: No license field
$ /home/<user>/file-explorator/node_modules/.bin/tauri init
Downloading Rust CLI...
Done in 0.20s.
→ 
```

### **To Reproduce**
1. Install tauri (`yarn add -D @tauri-apps/cli`)
2. Initialize tauri (`yarn tauri init`)
3. It says `Downloading Rust CLI... Done in 0.20s` without anything else

### **Expected behavior**
Tauri would give me a `src-tauri` folder with the following structure (taken from [here](https://tauri.studio/en/docs/usage/development/integration)):
```
src-tauri
    ├── .gitignore
    ├── Cargo.toml
    ├── rustfmt.toml
    ├── tauri.conf.json
    ├── icons
    │   ├── 128x128.png
    │   ├── 128x128@2x.png
    │   ├── 32x32.png
    │   ├── Square107x107Logo.png
    │   ├── Square142x142Logo.png
    │   ├── Square150x150Logo.png
    │   ├── Square284x284Logo.png
    │   ├── Square30x30Logo.png
    │   ├── Square310x310Logo.png
    │   ├── Square44x44Logo.png
    │   ├── Square71x71Logo.png
    │   ├── Square89x89Logo.png
    │   ├── StoreLogo.png
    │   ├── icon.icns
    │   ├── icon.ico
    │   └── icon.png
    └── src
        ├── build.rs
        ├── cmd.rs
        └── main.rs
```

### **Platform and Versions (required):**

```
Operating System - Linux (Ubuntu 20.04.1 LTS)

Node.js environment - what is Node.js environment?
Node.js - v16.2.0
@tauri-apps/cli - 1.0.0-beta.3
@tauri-apps/api - N/A

Global packages
npm - 7.13.0
yarn - 1.22.10

Rust environment
rustc - rustc 1.53.0 (53cb7b09b 2021-06-17)
cargo - cargo 1.53.0 (4369396ce 2021-04-27)

App directory structure
N/A

App
tauri.rs 
build-type 
CSP 
```

### **Stack Trace**

N/A

**Comment by lisiur** [comment]
I also encountered the same problem, and it took longer to display the prompt “Done in *s”, but in fact nothing happened. Sometimes switching networks may succeed. The strange thing is that there is no error message. This is very confusing.

**Comment by nothingismagick** [comment]
hmm. i worried that we may have had problems because of serving assets from GH Releases - thanks for the reporting. going to talk with the team and see about figuring out a more reliable alternative.

**Comment by lucasfernog** [comment]
Sounds like an issue with the init command, and not with the CLI downloading.

**Comment by lucasfernog** [comment]
Does `yarn tauri into` prints the message correctly? I guess it's only on the init cmd.

**Comment by nothingismagick** [comment]
Do you have a project you are installing into?
i.e.
```
git init
yarn init
yarn tauri init
```

**Comment by lisiur** [comment]
The easiest way to reproduce is to cut off the network and run `yarn tauri init`. And I found the problem：

https://github.com/tauri-apps/tauri/blob/4339b46e4bedc27f943db296ef5d89674046ca0e/tooling/cli.js/src/helpers/download-binary.ts#L42-L45

Throw statement in the catch callback will not be thrown out, we need try-catch to handle it.
New PR has been submitted #2116 

------------edit--------------
I was wrong, await a rejected promise is fine. 

https://github.com/tauri-apps/tauri/blob/4339b46e4bedc27f943db296ef5d89674046ca0e/tooling/cli.js/src/helpers/download-binary.ts#L22-L31

Meybe it's because `removeDownloadedCliIfNeeded()` just exit the process before error thrown.

**Comment by kubijo** [comment]
I've run into this as well… the solution for me was to [unplug](https://yarnpkg.com/cli/unplug) the `@tauri-apps/cli` package.
I guess you don't play well with yarn's PNP

**Comment by JohnCido** [comment]
I ran into this issue too. Any updates on this?
And this also happens when I run `yarn tauri info`. Does this CLI tool has to be downloaded each time?

**Comment by diversoft** [comment]
I also encountered the same problem, it will download rust cli when run 'yarn tauri dev' each time?

**Comment by johntostring** [comment]
It works for me:
**package.json**
```json
{
  "scripts": {
    "tauri:dev": "_HTTP_PROXY='http://127.0.0.1:1087' _HTTPS_PROXY='http://127.0.0.1:1087' _NO_PROXY='127.0.0.1,localhost,192.168.*' tauri dev"
  }
}
```
Tauri cli use [got](https://github.com/sindresorhus/got) as HTTP request library, and use [global-agent](https://github.com/gajus/global-agent) deal with HTTP/HTTPS proxy
https://github.com/tauri-apps/tauri/blob/48f3768c41a2c68e2e097fcc1ef50e549c1dfb78/tooling/cli.js/src/helpers/download-binary.ts#L5
https://github.com/tauri-apps/tauri/blob/48f3768c41a2c68e2e097fcc1ef50e549c1dfb78/tooling/cli.js/src/helpers/download-binary.ts#L16
https://github.com/tauri-apps/tauri/blob/48f3768c41a2c68e2e097fcc1ef50e549c1dfb78/tooling/cli.js/src/helpers/download-binary.ts#L49-L51

The problem is **environmentVariableNamespace**, and it's the prefix of the [global-agent Environment Variables](https://github.com/gajus/global-agent#environment-variables). so the env variables needs to start with `_` (😱)
@diversoft @kubijo

**Comment by mainrs** [comment]
> I've run into this as well… the solution for me was to [unplug](https://yarnpkg.com/cli/unplug) the `@tauri-apps/cli` package.
> I guess you don't play well with yarn's PNP

This didn't work for me. `yarn tauri init` works just fine. But `yarn tauri:serve` fails. The last manage I get is `Downloading Rust CLI...` (which has already been downloaded due to `yarn tauri init`). After that, the process exits.
