### ISSUE TITLE
http POST: missing boundary with content-type "multipart/form-data"

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2118]
Currently it is not possible to use "multipart/form-data" as content-type posting form-data with the http module due to missing boundary.

Example using the JS-API setting content-type by hand resulting in missing boundary:

```
return await http.fetch(url, {
    method: "POST",
    headers: {
        "Content-Type": "multipart/form-data",
    },
    responseType: 1,
    body: http.Body.form({
        name: "test"
    })
});

```

This might be an issue with attohttpc, leaving the content type blank the content-type defaults to "application/x-www-form-urlencoded".

I am using the latest version of tauri (1.0.0-beta.4).

**Comment by nothingismagick** [comment]
This is a great finding, thankyou! I see a couple options here:

1. You create a custom command and use something like reqwest
2. We create an advanced plugin using something like reqwest
3. We replace our current client with something like reqwest

**Comment by lucasfernog** [comment]
The issue is that we need to use the dedicated multipart APIs to support this:
https://docs.rs/reqwest/0.11.4/reqwest/struct.RequestBuilder.html#method.multipart
https://docs.rs/attohttpc/0.17.0/attohttpc/struct.MultipartBuilder.html

But the crate's design for multipart is filled with references, so it's tricky to implement it without introducing a breaking change.

**Comment by mgedgaudas** [comment]
> This is a great finding, thankyou! I see a couple options here:
> 
> 1. You create a custom command and use something like reqwest
> 2. We create an advanced plugin using something like reqwest
> 3. We replace our current client with something like reqwest

Would be nice if someone could provide an example how a custom command would look like for sending multipart form with files if this feature is not going to natively supported any time soon.

**Comment by FabianLars** [comment]
@mgedgaudas 
Kinda ugly cause i'm lazy, but that should provide the basics:
```rs
#[tauri::command]
async fn upload_file(file: std::path::PathBuf) -> Result<(), String> {
                  // ^We expect the frontend to send a file path.

    let client = reqwest::Client::new();

    let file_name = file.file_name().unwrap().to_string_lossy().to_string();
    let file_content = tokio::fs::read(file).await.map_err(|err| err.to_string())?;
    let part = reqwest::multipart::Part::bytes(file_content).file_name(file_name);
    let form = reqwest::multipart::Form::new().part("file", part);

    client
        .post("URL_HERE")
        .multipart(form)
        .send()
        .await
        .map_err(|err| err.to_string())?;

    Ok(())
}
```
You need to enable the `multipart` feature for `reqwest`.
And while you're at it you probably want to add the `reqwest-client` feature flag to `tauri` in Cargo.toml so that you don't bundle 2 different http libs into the binary (the default one is attohttpc)
