### ISSUE TITLE
tauri.js CLI: Errors from the Rust CLI don't propagate up to the JS CLI

### ISSUE THREAD

**Issue by rajivshah3** [tauri-apps/tauri#231]
**Describe the bug**
It seems like errors reported by the Rust CLI do not propagate to the JS CLI. In other words, the Rust CLI exits with a non-zero exit code, yet the JS CLI does not. Since the JS CLI returns an exit code of 0, the command is considered to have passed. This poses a problem for our own smoke tests in particular -- in the event that this occurs, GitHub Actions will [mark the step as "passed"](https://github.com/tauri-apps/tauri/pull/188#issuecomment-567963724) even though it actually should fail.

Examples where this has occurred:
https://github.com/tauri-apps/tauri/pull/187/checks?check_run_id=357905199#step:11:112
https://github.com/tauri-apps/tauri/pull/214/checks?check_run_id=363576771#step:14:130

**To Reproduce**
1. Run a command from the JS CLI (e.g. `yarn tauri build`) which causes an error to be thrown from the Rust CLI

**Expected behavior**
Non-zero error codes from the Rust CLI should result in a non-zero error code from the JS CLI

**Platform (please complete the following information):**
This doesn't appear to be a platform-specific issue

**Comment by rajivshah3** [comment]
Ah looks like this was previously reported in #202 . I'm investigating right now to see what's causing the issue

**Comment by tensor-programming** [comment]
I already know what the problem is.  When an error is reported from Rust it gets obscured by the Node runtime.  If you go into the bundler and try to use println! to print a message you'll notice that it won't make it through the I/O.  Best way to get around this is with the stdout pipe and some of the functions from the common.rs module.  I'll look tomorrow, its really just a matter of adding a piece of code to invoke the error logger when an error propagates.
