### ISSUE TITLE
[docs] Missing required dependency for Linux (Debian)

### ISSUE THREAD

**Issue by andrewbrey** [tauri-apps/tauri#2436]
On https://tauri.studio/en/docs/get-started/setup-linux, it is indicated that the required dependencies are:

```
$ sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    libssl-dev \
    libgtk-3-dev \
    squashfs-tools
```

But on a fresh install of stock Ubuntu, when building an app for the first time, I encountered the following error (snippet clipped from rerunning a build with `yarn tauri build --verbose`) while the scripts were building the AppImage file:

```
file command is missing but required, please install it
Error: failed to bundle project

Caused by:
    Shell Scripting Error:`error running appimage.sh`
```

After running `sudo apt install file`, I was then able to proceed and successfully built my AppImage. It would be helpful to indicate that this utility is required in the Linux setup instructions.

Thanks for the cool project!

**Comment by lucasfernog** [comment]
I'm changing the AppImage build script here: #2437 hopefully that'll fix the issues since `linuxdeploy` is an AppImage, so it includes everything that it needs to run. (I tried it on a fresh Ubuntu 18.04 and didn't have to install the `file` package). Please let me know if that's still needed after our release (probably tonight!).
