### ISSUE TITLE
[docs] .scripts/setup.ps1 is not working

### ISSUE THREAD

**Issue by aleksey-hoffman** [tauri-apps/tauri#2469]
## Problem

This script is not working:

https://github.com/tauri-apps/tauri/blob/dev/.scripts/setup.ps1

`setup.sh` is potentially broken as well, I didn't test it.

The script is trying to get `tauri/.scripts/tooling` instead of `tauri/tooling`

## Solution

Add a dot before `\tooling\`

```
Line 7: cd .\tooling\api
Line 12: cd .\tooling\cli.rs
Line 24: cd .\tooling\cli.js
```

## Console log

```
PS E:\tauri>./.scripts/setup.ps1
Building API definitions...
cd : Cannot find path 'E:\tauri\.scripts\tooling\api' because it does not exist.
At E:\tauri>./.scripts/setup.ps1:7 char:1
+ cd tooling\api
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (E:\tauri\.scripts\tooling\api:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

**Comment by FabianLars** [comment]
afaik you're "supposed" to invoke the script in tauri's root folder with `.\.scripts\setup.ps1` (or `./.scripts/setup.sh` for that matter).
btw "`Line 7: cd .\tooling\api`" would be wrong too, i think? (`.\` -> current dir -> .scripts)

**Comment by aleksey-hoffman** [comment]
@FabianLars these lines are effectively the same thing:

```
E:\tauri\.scripts> .\setup.ps1
E:\tauri>.\.scripts\setup.ps1
```

The error is thrown by the script itself. I had to modify the script in order to run the example api app

**Comment by FabianLars** [comment]
No, these lines are not the same. The current working directory differs! For example put `Get-Location` in a test.ps1 in the .scripts folder and run both commands, to see it yourself 🤷 .
(Therefore adding `.\` shouldn't make a difference, because `.\tooling\api` and `tooling\api` both start in the cwd and not at the script location)

edit: an actual fix could be to try using the script location as a starting point with `$PSScriptRoot` and `dirname $0` or something like that, but maybe that would cause more issues than it solves 🤷

**Comment by aleksey-hoffman** [comment]
@FabianLars yeah, you are right. it's working properly if you open it like this
