### ISSUE TITLE
Launch on system startup

### ISSUE THREAD

**Issue by elvinaspredkelis** [tauri-apps/tauri#2589]
**Describe the solution you'd like**
It would be amazing to be able to launch the app on system startup.

**Describe alternatives you've considered**
I've been browsing over the GitHub issues and/or solutions online but it seems there is no universal way to support this on all desktop platform.

**Additional context**
It seems that electron community is using this package to deal with launching the app on startup:
https://www.npmjs.com/package/auto-launch

If it helps in any way, this seems to be the official way of doing the auto launching, but it doesn't support Linux
https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows

**Comment by zzzgydi** [comment]
After your inspiration, I have published a crate [auto-launch](https://crates.io/crates/auto-launch) which I rewrite in Rust based on [node-auto-launch](https://github.com/Teamwork/node-auto-launch). Here is the git repo <https://github.com/zzzgydi/auto-launch>. And I have used it in my tauri project. Hope this works for you.

**Comment by nothingismagick** [comment]
Really interesting work. Might be nice to consider integration into TAO ... WDYT @lucasfernog @lemarier @amrbashir @wusyong

**Comment by wusyong** [comment]
It's looking great but we might need to schedule it after v1 I think.

**Comment by lucasfernog** [comment]
Interesting, I also wrote a plugin for this but did not test Windows yet :) might just use that awesome crate @zzzgydi

**Comment by betamos** [comment]
@zzzgydi I successfully used auto-launch in a tauri app, awesome! Tested on Windows 10, MacOS and Ubuntu.

The "hard" part for my Tauri app was getting _the path to the app, at runtime_, which for MacOS is the path to the **package**, e.g. `/Applications/MyApp.app` (not the executable).

It would be great to create a plugin for Tauri, with a couple of commands for getting/setting the option. Let me know if someone already did/is in the process of doing that, otherwise I'm happy to do it.

**Comment by zzzgydi** [comment]
@betamos I also met the hard part you mentioned, but I have no plans to do this recently. If you have create the plugin, I'm happy to test it in my tauri app.

**Comment by RyKilleen** [comment]
@betamos @zzzgydi If there's a public example somewhere of `auto-launch` integrated with a Tauri app, I'd appreciate it!

**Comment by zzzgydi** [comment]
@RyKilleen Hi, I have used `auto-launch` on my app [clash-verge](https://github.com/zzzgydi/clash-verge), you can see the code [here](https://github.com/zzzgydi/clash-verge/blob/b2a24c7abd82f4650ec3ec873b742219169310de/src-tauri/src/core/verge.rs#L73).

**Comment by lucasfernog** [comment]
Here's the Tauri plugin using auto-launch: https://github.com/tauri-apps/tauri-plugin-autostart
Thanks for the amazing crate @zzzgydi

**Comment by akozhemiakin** [comment]
@lucasfernog We tried to use tauri-plugin-autostart but understood that it doesn't feet our needs, for several reasons:
1. It doesn't enable autostart after install, but allows it to be enabled by user later on.
2. We couldn't use auto_launch crate or any similar approach, because by setting app to auto start on boot we will affect development builds and even launching app from exe file without installing it (where, obviously, we don't need auto start).

We found a solution for Windows by creating the following WiX fragment:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Fragment>
    <DirectoryRef Id="TARGETDIR">
      <Component Id="AutoStartRegistryEntries" Guid="6B4846B4-C05D-425A-9B24-BDFABDAFE4DF">
          <RegistryKey Root="HKCU"
                       Key="Software\Microsoft\Windows\CurrentVersion\Run">
              <RegistryValue Name="[ProductName]" Type="string" Value="[INSTALLDIR][ProductName].exe"/>
          </RegistryKey>
      </Component>
    </DirectoryRef>
    <Feature Id="AutoStartRegistryEntries" Title="Run at OS startup" Absent="disallow">
      <ComponentRef Id="AutoStartRegistryEntries" />
    </Feature>
  </Fragment>
</Wix>
```

I could create PR to include this functionality in Tauri by adding new boolean `autostart` attribute into WixConfig. Is there any interest in it?
