### ISSUE TITLE
Provide a way to yank releases

### ISSUE THREAD

**Issue by mainrs** [tauri-apps/tauri#2596]
**Is your feature request related to a problem? Please describe.**
In some cases it might be desirable to yank already published versions. For example if a really bad bug has been introduced or breaks certain behavior.

**Describe the solution you'd like**
A new field added to the update json manifest `yank: boolean`. If set, the version will not be considered to be an update, even if the semver is higher than the currently running application making the update check.

**Describe alternatives you've considered**
An alternative would be to simply remove the entry inside the update manifest. However, I do not like this approach nor do I think it is a good one. It removes the knowledge of that version ever to have existed. It's harder to track (through VCS) on when and why it got removed.
It also removes the ability to actively notify a user if their installed version has been yanked.

**Additional context**
An optional field that could be used to link to a resource or free text on why the version has been yanked would also be good to have. In that case, the application could even display that information to the user and asks if he wants to revert to the last stable version instead of keeping the yanked one installed.

**Comment by FabianLars** [comment]
You can do something like this with the update server method (instead of the static file) already, as tauri installs whatever version the server returns (mainly to allow stuff like downgrading). So yeah that's like _The_ use-case for the server variant.

The static json can't really support this afaik, as it always returns just the latest version (or whatever you specify, but the point is, it's just _one_).  
So if that version is marked as yanked, alright, tauri's not gonna install it.  
But if the installed version is the yanked one (being the same version specified in the json): where should tauri get the info about the "new" version from?

**Comment by mainrs** [comment]
Looks like I didn't understand the static json file correctly then! I thought it would contain a history. Looks like the server variant is indeed a solution that would work perfectly fine! Thanks for pointing that out!
