### ISSUE TITLE
dlopen + dlsym / FFI / native modules (ability to dynamically load symbols and call exported functions from .so / .dylib / .dll)

### ISSUE THREAD

**Issue by brandonros** [tauri-apps/tauri#2706]
Like this: https://github.com/node-ffi-napi/ref-napi https://github.com/node-ffi-napi/node-ffi-napi

**Comment by amrbashir** [comment]
Rust has [ffi](https://doc.rust-lang.org/nomicon/ffi.html) system which you can use, it is not specific to Tauri though, however if you want to ship some .dll/.so/.dylib with your app, you can add them as resources here https://tauri.studio/en/docs/api/config#tauri.bundle.resources.

**Comment by brandonros** [comment]
Wouldn’t it be wise to develop some kind of FFI interop so end users are abstracted away from having to dive into Rust? For example, Electron has the ffi packages I listed

**Comment by amrbashir** [comment]
It is not specific to electron but to NodeJS in genereal.

Anyhow, providing ffi system in the webview is a huge security issue and probably near-impossible to implement. It is easier to use rust ffi tbh and more robust. 

In the future we plan to support deno, NodeJS, c++, python and many more as the backend instead of rust to make it easier for people that aren't familiar with rust but it will be a while before we start working on that.

**Comment by nothingismagick** [comment]
I absolutely agree with amr: direct FFI interop from the webview is totally unwise, unsafe, and virtually irresponsible. We provide a complete message passing system and API so most use cases won't have to even need to touch rust.  The big thing that most FFI users forget, is that you have to trust that the C authors (or whatever lang) did a perfect job of managing memory and packaging their lib. FFI is by nature unsafe, because the host has to trust the foreign functions. In security contexts this is untenebale, and tts why fuzzing is such a huge thing in non rust libraries. But put an FFI in a JS context? That's a big nope.
