### ISSUE TITLE
Custom folder for Rust source code

### ISSUE THREAD

**Issue by crapStone** [tauri-apps/tauri#2752]
**Is your feature request related to a problem? Please describe.**
I want to split my codebase into two separate folders: the ui/app and a rust workspace where one of the crates is the tauri app and the rest are libraries that are used by the app.

**Describe the solution you'd like**
My idea was to add options to the `package.json` and `tauri.conf.json` to specify the relative path to the respectively other config.

folder structure:

```
.
├── crates
│   ├── lib1
│   │   ├── Cargo.toml
│   │   └── src
│   ├── lib2
│   │   ├── Cargo.toml
│   │   └── src
│   └── tauri_app
│       ├── Cargo.toml
│       ├── src
│       └── tauri.conf.json
├── LICENSE
├── README.md
└── ui
    ├── package.json
    └── src
```

package.json:

```json
{
  "tauri": {
    "rustConfigPath": "../crates/tauri_app/"
  }
}
```

tari.conf.json

```json
{
  "build": {
    "appPath": "../../ui/",
  }
}
```

**Describe alternatives you've considered**
I found [this](https://github.com/tauri-apps/tauri/commit/a8cff6b3bc3288a53d7cdc5b3cb95d371309d2d6) commit but it requires the app and tauri app to be just one folder level apart.

**Comment by dannymcgee** [comment]
I would also really appreciate this feature. I use [Nx](https://nx.dev) to manage my TypeScript workspaces, and without this, it doesn't look like there's a clean way to integrate a Tauri app into my existing projects. I haven't really started investigating workarounds though — I'll comment with a follow-up if I come up with something.

**Comment by dannymcgee** [comment]
> I haven't really started investigating workarounds though — I'll comment with a follow-up if I come up with something.

I came up with an _okay_ workaround for Nx by using a global install of `@tauri-apps/cli` and [executing the command with an explicit working directory](https://github.com/electric-io/electric/blob/f5137d8d7cd403725c05568f02ef606322a8e554/demos/tauri-app/project.json#L10). Trying to use `npm run tauri dev` instead of `tauri dev` always fails, regardless of the `cwd` setting — I'm assuming that's because my `node_modules` directory is in an unexpected location (two folders up from where it would be normally).

**Comment by lodmfjord** [comment]
I really want this feature too. Any reason why you closed this?

**Comment by amrbashir** [comment]
you can now rename it and have it nested too up to three levels. Just rename and move, if the cli doesn't pick it up let us know.

**Comment by franciscoschunk** [comment]
this still does not work.
created a new app following instructions on the website.
changed 'src-tauri' to 'back' and running `pnpm tauri dev` results in
` failed to read plugin permissions: failed to read file: The system cannot find the path specified. (os error 3)`

**Comment by franciscoschunk** [comment]
the solution is to edit the package.json.
change `"scripts": { "tauri": "tauri"  }` to "scripts": {"tauri": "tauri dev --config back/tauri.conf.json"}

**Comment by malyavi-nochum** [comment]
It seems the capabilities folder is locked to the src-tauri directory, I can't seem to figure out how to change that. It just won't find any of the capabilities files if the directory is renamed

**Comment by LukasWillin** [comment]
> the solution is to edit the package.json. change `"scripts": { "tauri": "tauri" }` to "scripts": {"tauri": "tauri dev --config back/tauri.conf.json"}

I tried that but it didn't change anything `"tauri:serve:development": "tauri dev --config src/tauri.conf.json",`

Latest version of tauri (^2) npm (11.10.0) node (25.6.1) as of 2026.02.27.

```powershell
error: failed to run custom build command for `projectname-client-app v0.1.0 (C:\Users\Public\Documents\Dev\ProjectName\Client\Tauri\src)`

Caused by:
  process didn't exit successfully: `C:\Users\Public\Documents\Dev\ProjectName\Client\Tauri\src\target\debug\build\ProjectName-client-app-2dbc83e4cf7039d8\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rerun-if-changed=C:\Users\Public\Documents\Dev\ProjectName\Client\Tauri\src\tauri.conf.json
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=projectname_client_app
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=com_company
  cargo:rustc-check-cfg=cfg(dev)
  cargo:rustc-cfg=dev
  failed to read plugin permissions: failed to read file '\\?\C:\Users\Public\Documents\Dev\ProjectName\Client\Tauri\src-tauri\target\debug\build\tauri-e61c64212d8956c5\out\permissions\app\autogenerated\commands\app_hide.toml': The system cannot find the path specified. (os error 3)
```

I guess I just have to use `src-tauri`. It's not a huge deal. But definitely a bug and the issue should be reopened or a new one created

**Comment by FabianLars** [comment]
Do you think you can come up with a minimal reproduction project for us to try? I'm not using src-tauri in my test projects either and had no such issues yet.

**Comment by LukasWillin** [comment]
Strange I have really just created a new project. I can more or less just push my current setup I guess. Since there really isn't anything that shouldn't go public yet.

**Comment by LukasWillin** [comment]
@FabianLars 
I figured it out while creating a repro repo. :P
The issue is somewhere in the change detection in the build pipeline I guess, since after deleting the `target/`-directory it works just fine.

---

> This is how I got to my solution.

1. ©️ I have copied my setup to a new directory.
2. 😮 After I have replaced all references to my company and project (in naming only) I was able to rename the `src-tauri` directory to `src` and it built just find.
3. 💥 I then renamed the original projects `src-tauri` directory and tried the same build command and it failed.
4. 🤯 I went back to my new copy and tried the debug build again. And it failed as well.
5. 🤔 I renamed the parent directory to something shorter because I was wondering whether I was running into path-length issues on Windows, but that didn't change anything.
6. 🧐 I then noticed that the plugin permissions path pointed back to my original projects `src-tauri` path. 
7. 💥 I nuked the `src/target/`-directory and reran my debug-build command
8. ✅ Now it works

So it seems that not everything that is necessary is rebuilt after renaming the `src-tauri` directory. This either just needs a bit of documentation or a fix.

---
> Reproduction steps:

1. Create a new repo
2. ✅ Make a build `npx tauri dev`
3. Rename the `src-tauri` directory
4. Rerun the build `npx tauri dev`
5. 💥 Now it fails
6. delete the `target`-directory
7. Rerun the build `npx tauri dev`
8. ✅ Now it works

I guess I should have seen that coming but since some of it was rebuilt (but not everything) my mind didn't immediately come to that conclusion. Anything you would like me to do?
