### ISSUE TITLE
msi installer - stretched icon

### ISSUE THREAD

**Issue by fogine** [tauri-apps/tauri#2760]
### **Describe the bug**
After running builded `msi` installer on windows, it shows stretched icon in the top area of msi window
![img-2021-10-18-112810](https://user-images.githubusercontent.com/7884288/137705677-feba48f9-62fd-4e07-9762-55e50edaa7fc.png)

### **To Reproduce**
I generated the icons with the `tauri icon /path/to/source/icon.png` command.

### **Expected behavior**
There should be icon rendered with correct proportions or not rendered at all.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.17763 X64
Webview2 - 94.0.992.50

Node.js environment
  Node.js - 16.7.0
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.20.3
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/bds
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack


App
tauri.rs
build-type
CSP
```

**Comment by FabianLars** [comment]
Soooo, the problem here is your `@tauri-apps/cli` version. In beta.6 there were banner settings introduced (the banners are unrelated to the `tauri icon` command), see [here](https://tauri.studio/en/docs/api/config#tauri.bundle.windows.wix.bannerPath) for config help.

If those aren't provided it should fall back to WiX default ones (no distortion).

btw in theory the latest cli version is `beta.10`, but the latest vue cli plugin pins it to `beta.6` (which can cause problems, but doesn't have to atm)
