### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by Immortalin** [tauri-apps/tauri#279]
**Is your feature request related to a problem? Please describe.**
Build for operating systems different from host system

**Describe the solution you'd like**
Rust, Electron all have mature cross compilation systems

**Comment by nothingismagick** [comment]
Yup, it's on our roadmap.

**Comment by nothingismagick** [comment]
Right now we offer a GH action to build for the big three desktops. Doing this locally for all three is complicated by the fact that to the best of our knowledge, you are required by the Apple T&C to build MacOS (and iOS) apps on 'real' Mac hardware. So from my perspective there are only three options:

1. Use a Mac as host and build from there, potentially using docker / VMs
2. Use our GH action
3. The community creates and maintains an unofficial cross solution for non MacOS systems.

Since #2 technically solved the problem, I am closing this issue. Feel free to drop by the community discord and continue this discussion there.
