### ISSUE TITLE
[docs] Consider updating Svelte instructions

### ISSUE THREAD

**Issue by Immortalin** [tauri-apps/tauri#280]
Svelte by default recommends using the svelte template so just like create-react-app you only need to run `npm run dev`

![image](https://user-images.githubusercontent.com/7126128/71769832-cd07ea00-2ef3-11ea-9d8a-d9cd4aa699ca.png)

Also instructions for npm such as `npm run tauri info` can be replaced with `npx tauri info` as of node 12

**Comment by nothingismagick** [comment]
I actually considered both of those topics - but regarding the dev command preferred to use the actual command hidden behind the scripts.dev value as you can find it in our examples:

https://github.com/tauri-apps/tauri/blob/6c8f310763508dedcda37f667b26068144a73c11/examples/svelte/svelte-app/package.json#L7

Ultimately if the reader doesn't know how to start their own devserver, tauri might be a touch too complicated. But point taken.

Regarding the usage of npx, I sort of go back and forth on this. I haven't personally audited npx, so I am not sure if I trust it. I'll do that and then add it as a third option. Sound good?

**Comment by Immortalin** [comment]
Sounds brilliant! Npx is first party npm code and it will by default use the local copy of the script if you have it listed as a dependency in package.json https://github.com/npm/npx

**Comment by nothingismagick** [comment]
I am not going to suggest `npx` until npm gets their act together. That number of vulns is totally irresponsible for an industry leader.

https://github.com/npm/npx/issues/29#issuecomment-570825075

In fact, I am going to post an advisory on our discord channel right now. Stop by if you want to chat! However, since the `npx` issue is separate from the Svelte instructions, I am going to close this issue. But we really appreciate your input! 

❤️
