### ISSUE TITLE
Windows crash: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by guillemcordoba** [tauri-apps/tauri#2806]
### **Describe the bug**

In **some** Windows 10 computers, the tauri application crashes with error: 

```
Error building the window: runtime error: failed to create webview: WebView2 error: WindowsError(Error { code: 0x80070002, message: "The system cannot find the file specified.", win32_code: 2 })
```

### **To Reproduce**

Don't really know how to reproduce it myself, the application works fine in my Windows...

### **Expected behavior**

The application is executed without errors.

### **Platform and Versions (required):**

Operating System - Windows, version 10.0.17763 X64
Webview2 - Not installed

Node.js environment
  Node.js - 12.22.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.15

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/.github
/node_modules
/public
/scripts
/src
/src-tauri
/tests

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - target/webpack_dist
  devPath - target/webpack_dist
  framework - Vue.js (Vue CLI)
  bundler - Webpack

**Comment by FabianLars** [comment]
I'm pretty sure that's a missing WebView2 installation. I also took a look at the related issue in your repo and it sounds like they indeed cancelled the wv2 installation, quote: "One unusual odd one was to trick(?) me [...] to get my permission to activate and update Microsoft Edge" - the thing is, that's not the case, the WV2 installer calls itself something like "Edge Updater" during installation (don't remember the exact name).
-> This is something MS really has to look into, because it actually looks fishy for the common user. But at the same time it also makes sense that it calls itself something Edge related, as it is basically a modified Edge version.

So the fix is to ask them to install WebView2.

**Comment by guillemcordoba** [comment]
Oh okey thanks, will do. Will close this for now.
