### ISSUE TITLE
Allow app to run in browser through localhost

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#2849]
Sometimes you may want to run your app through localhost and open it in a browser. A few reasons:
- Accessing different devtools
- Checking for some HTML/CSS/JS incompatibility/inconsistency without having to get into another OS.
- Using features like `CTRL+F` or extensions

It would basically mean starting a localhost server, and making commands work over an HTTP interface. I imagine (naively) that this would be fairly straightforward, except how to deal with commands that have `Window` arguments.

Personally I think it would be fine if there are some unsupported things that just panic. This thing could be behind a feature flag.

**Comment by frnco** [comment]
In my experience it's always been easy to test things at a browser in the beginning, and then after the basic stuff is in place and I start using Tauri functionality I stop being able to test outside of Tauri.

I think this would be a very nice addition but I don't know whether it's feasible and what would be the best way to do it. A few additional reasons thay may be relevant are:
- Tauri dev takes a looooong time to start the application, so this might significant improve the feedback loop when developing;
- Besides the differences in Devtools, Tauri Dev Tools are a bit clunky, you can't open them using `F12`, they aren't as responsive as the ones I'm used to in browsers, and at times they didn't reflect changes to the DOM in the Elements tab, which left me unable to check some specific element.

An alternative way to improve the situation would be having a Flag for Tauri to use Chrome/Firefox/whatever instead of Webview, could be just for testing since using something like Chromium would make the application non-free, but depending on how much that improves the development cicle it might be a good thing to consider.

**Comment by Darunada** [comment]
My use case is primarily to use DevTools extensions while building my application

This issue talks about extension support in WebView2:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/98

I haven't explored that much, but it looks like Tauri spins up its own web server (the requests go to localhost:8081 when I am running my server on 8080), perhaps it would be viable to configure it to use one that is already running in development.

**Comment by frnco** [comment]
> This issue talks about extension support in WebView2: [MicrosoftEdge/WebView2Feedback#98](https://github.com/MicrosoftEdge/WebView2Feedback/issues/98)

Just wanted to point out that some of us don't use Windows. I'm actually on Arch Linux, and Webkit2Gtk is a pain in the.... Well, let's keep it civil and just say it feels like I'm back in 2010 dealing with Internet Explorer 6. Most of the stuff I've done in tauri was just so I could share share some of the stuff I build for myself with friends and family, to mention a few there's an eBook reader, an app to translate images (Uses OCR and automatically translates whatever it detects), a video-streaming-thing (Mostly trying to test how well I can integrate it with loads of stuff, unfortunately doesn't work with Netflix, at least not yet), one app to transcribe audio and a Manga Downloader. The Audio Transcriber is pretty much the only one that is actually relevant to someone, I made it to help a family member who was having trouble with transcribing lessons, everything else is pretty much just for fun, but I found out the hard way that a lot of stuff just doesn't work in Linux, probably because of `webkit2gtk`, especially CSS stuff, things like filters, `backdrop-filter`, I have to check pretty much everything I try to do with CSS because many, MANY times stuff just don't work for me, and it'd be nice if I could use something like Chrome to test it under Linux, especially for stuff that is supported by WebView2 in Windows.

It would probably be a good idea to allow developers to choose what to use for each target, I'm not sure how `qt-webview` is coming along, but I wouldn't be surprised if it works better than `webkit2gtk`, and for some projects using Chromium or whatever wouldn't be a problem, and being able to blur stuff behind a semi-transparent element would definitely convince me to use pretty much whatever for my eBook reader, scrolling text behind a transparent header without blurring looks so bad I had to crank up the opacity to pretty much 100%...

Well, ranting aside, the point is, being able to change whatever is used for rendering has loads of benefits besides Devtools, and those benefits should be considered before any decision about this is made.

**Comment by FabianLars** [comment]
First of all, because everything below might suggest otherwise, i'm not against the feature, at least not in dev mode.
I'm also aware that many things are far from perfect in tauri-land.
But anyway, here are some random comments to things said in this thread, just my opinion/knowledge, nothing official!

> I imagine (naively) that this would be fairly straightforward

Actually not reallyyy, the whole current communication process depends on webview specific methods. So that would be a somewhat bigger rewrite. But it's something already considered for post-1.0, at least for data transfer, because the mentioned methods are quite slow.

_If you only want to hear stuff actually related to the inital feature request you can probably stop here i guess_ 🤷

> My use case is primarily to use DevTools extensions while building my application

Actually kinda weird that the WebView2 devs consider adding support for that, because they intentionally disabled/removed that functionality in the first place.
Also this is something that would be windows only (in the context of WebViews).

> it looks like Tauri spins up its own web server

Nope, it doesn't. Sounds more like your `beforeDevCommand` starts the frontend dev server.

> and Webkit2Gtk is a pain in the....

Yeah, webkit2gtk is definitely a problem (macOS' webkit too, but not as much because it's not as buggy lol)

> CSS stuff & backdrop-filter

Yeah that's unfortunetly what happens if you don't use chromium based things under the hood. In general you have to orientate yourself to Safaris css support. They're in general on par, as long as you don't target the latest safari version (which wouldn't work for macOS too, because the system webkit only gets updated on new macOS releases).

For backdrop-filter specially, it should work already, but with a -webkit- prefix (like in safari), expect if you mean in transparent windows, then it's actually not supposed to work (it's just not how it works in general, with electron being kinda an exception), see #2827.

_(also, backdrop-filter support in firefox when??)_

For this kind of testing (aka. design stuff) debugging in a browser still works in general and if something tauri related breaks your frontend you most of the times workaround it with a `if (window.__TAURI__) {}` check.
Obviously not perfect, but it can get the job done. And i know that this is (rightfully) not acceptable for everyone.

> qt-webview

(Actually the Qt WebEngine thingy (which Qt WebView builds on on win and linux) would be more relevant here.)
The chances that they are ahead of webkit2gtk are really high as it uses a slightly outdated chromium version under the hood (latest seems to be 90) instead of webkit. Not to mention that they (Qt) actually get paid (licensing) and therefore should have more resources.
If we ignore the licensing stuff, the biggest problem imo is integrating it into tauri. First of all Qt stuff in general is quite a pain to use with/from rust, but trying to use a part of it, best-case completely independent from Qt, sounds like no fun at all, if it's even possible.

Using chromium itself is even less of an option imo.
First of all, what would be tauris _catchy_ difference to electron then (where you can use rust too)? 
Secondly, that sounds like a _lot_ of work, _if_ it's even possible without completely starting from scratch. Definitely too much work for the relatively small core team.

And that was pretty much only the technical side of things, can't really say much about security, privacy and whatever.

**Comment by lucasfernog** [comment]
It is not trivial, but it was easier than I expected after some experimentations. I think I'll push it tomorrow.

**Comment by lucasfernog** [comment]
You'll probably find success using a combination of https://github.com/tauri-apps/tauri-plugin-localhost and https://github.com/tauri-apps/tauri-invoke-http. If it doesn't work, please file an issue on those repositories.
