### ISSUE TITLE
Add Web assembly support for UI

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [tauri-apps/tauri#2852]
**Describe the solution you'd like**
We are using yew to build pour web application interface.
Based on that we wanna to use Tauri to generate native application with the same user interface, so based on Rust code builded in wasm.

Lot of exemples describes Vue.js integration, but nothing clear about Web Assembly / Yew or other Rust framework.

Does someone has already tested that ?
Do you think it can be complex/crazy or totaly realistic ?

Thanks
Marc-Antoine

**Comment by FabianLars** [comment]
wasm is supported, just like in a normal browser, so if you don't need tauri apis and just want to wrap your website in a tauri window (why tho?), you're already good to go.

But as hinted above, what's currently missing are wasm-native bindings for the tauri api (`@tauri-apps/api`), so until then you have to bind to the js ones. Iirc yew actually supports npm packages, right? Otherwise you can enable `withGlobalTauri` in `tauri.conf.json` to inject the api into `window.__TAURI__`.

There is also this example created by another user: https://github.com/littlebenlittle/tauri-liboath-example, which seems to use yew too. Although this example might need some slight changes to update to the latest versions.

Also, create-tauri-app already provides a [dominator](https://github.com/Pauan/rust-dominator) recipe. A yew one might be a nice addition...

**Comment by amrbashir** [comment]
yew or any webassembly framework can work in Tauri as @FabianLars stated so I am gonna close this and let use know if you need more help, preferably on our discord server.

**Comment by Chralt98** [comment]
When does Tauri support wasm-native bindings for the tauri api? Does this mean that Rust functions can be executed in the web browser using WASM? So currently only the desktop applications of tauri can execute the Rust commands.

**Comment by FabianLars** [comment]
We currently don't have any ETA and nobody is actively working on. The closest thing we have is this https://github.com/JonasKruckenberg/tauri-sys (Jonas is part of the tauri working group) but it doesn't support v2 beta yet.
