### ISSUE TITLE
not sure whether we should use tauri-api-http over other http client?

### ISSUE THREAD

**Issue by conanchen** [tauri-apps/tauri#2935]
not sure whether we should use tauri-api-http over other http client? does it mean tauri-api-http support better bundle size?

**Comment by amrbashir** [comment]
the tauri-api-http mainly exists to be an alternative to the webview `fetch` in cases where you don't need to be blocked by CORS or simply want to make the requests from the rust process instead of the webview. Out http client is sufficient for most use cases in rust or in js but you can still use other http clients without a problem. It is up to your preference.
