### ISSUE TITLE
RLS fills a folder with with junk until disk is full everytime it is run. Only happens with tauri.

### ISSUE THREAD

**Issue by JussiVJ** [tauri-apps/tauri#3083]
I'm developing on manjaro on linux 4.19. I use VSCode and its rls plugin. It started randomly one time and I have no idea why. The issue stops by running "killall rls" after shutting down vscode or doing it until vscode no longer restarts it. I have not found even a temporary fix for this issue.

The directory of the files is "src-tauri/target/rls/debug/app-RANDOMID/out/tauri-codegen-assets

This is the view from a disk space analyzer
https://pasteboard.co/1J2f2PlnX6b1.png

Here is the RLS log from VSCode. 
https://pastebin.com/8eRgwQUs

I can provide more info if needed.

**Comment by FabianLars** [comment]
Lol that's wild. Do you have to use RLS extension tho? What about rust-analyzer, it's pretty much better in every way and is supposed to replace the RLS extension.

This looks more like a bug in the RLS extension than in tauri, and tbh this is something I really don't want to triage (especially since ra is such a better alternative).

Edit: Wait, actually this could be a misconfiguration in tauri.conf.json i think. is your devPath/distDir set correctly? The folders specified are not supposed to include folders like node_modules or target (because tauri will try to include them). -> btw that's why there's an issue template. Especially the block that's annotated with "**required**" where you're supposed to paste the output of `tauri info`...
