### ISSUE TITLE
[bug] Very slow and expensive to create multiple invisible windows in the splashscreen page

### ISSUE THREAD

**Issue by xuchaoqian** [tauri-apps/tauri#3534]
### Describe the bug
Our app could take long time to load, so we show a splashscreen page first, then create or recover multiple windows in it.

It works on macOS, but it's very slow and expensive to do that on Windows.

### Reproduction

1. clone the [demo repo](https://github.com/xuchaoqian/tauri-examples.git)
2. cd create-multiple-windows && npm install && cargo tauri dev
3. see the result

### Expected behavior
None.

### Platform and versions

```shell
Operating System - Windows, version 10.0.19043 X64
Webview2 - 98.0.1108.56
Visual Studio Build Tools:
   - Visual Studio ���ɹ��� 2019
   - Visual Studio Community 2019

Node.js environment
  Node.js - 14.18.2
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 6.14.15
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc

App directory structure
/build
/config
/node_modules
/public
/scripts
/src
/src-tauri

App
  tauri - git+https://github.com/tauri-apps/tauri.git?branch=dev#080755b5377a3c0a17adf1d03e63555350422f0a (1.0.0-rc.3)
  tauri-build - git+https://github.com/tauri-apps/tauri.git?branch=dev#080755b5377a3c0a17adf1d03e63555350422f0a (1.0.0-rc.3)
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

### Additional context
It may also work on windows if the visible attribute is true, but not very sure.

**Comment by xuchaoqian** [comment]
Fought with the bug for some hours, then found that:  It also does not work even if invoke tauri officail api to create multiple windows in one loop.

```
    for (const props of Object.keys(propses)) {
       new WebviewWindow(label,  props );
    }

```

**Comment by xuchaoqian** [comment]
Hi friends @lucasfernog @amrbashir,  could you help me to investigate this bug? Thanks a lot.

**Comment by lucasfernog** [comment]
Sure thing, I can take a look tomorrow.

**Comment by lucasfernog** [comment]
Seems like it's a threading issue on the event loop. There's some cases:

- creating two visible windows works
- creating two invisible windows does not work with the tao `dev` branch
- creating one invisible window works if I change `execute_in_thread` to always run `PostMessageW` (seems like it was deadlocking on the ShowWindow call on window_state.rs, maybe because it was executed directly on the event loop thread?)
- creating two invisible windows works if I change `execute_in_thread` to always run `PostMessageW` and comment out the code that sends `Focused` events (it seems like it is stuck sending such events, blocking the event loop).

@amrbashir I think only you can fix this LOL

**Comment by xuchaoqian** [comment]
@lucasfernog  Thank you so much. 

I also found a weird case.

If I change the following code
`WindowUrl::App(PathBuf::from("index.html"))`
to
` WindowUrl::External(url::Url::parse("https://www.youtube.com/watch?v=BhmXTi0X7Kg").unwrap())`

### The pages are NOT loaded successfully first:
![image](https://user-images.githubusercontent.com/1064052/156907389-4b9de1de-8ec8-439f-80d5-63643e44ea0f.png)

### Now if I click one of the windows, all pages will be loaded at once together:
![image](https://user-images.githubusercontent.com/1064052/156907489-5a0b2e51-2942-4f89-a489-ff3e2c6d086c.png)

### Seems like we will encounter this case if the pages need long time to load.

**Comment by xuchaoqian** [comment]
I found another weird case: it will cause the app to be Not Responding if I click the dock icon multiple times as quickly as possible during the loading process.

https://user-images.githubusercontent.com/1064052/156909160-a41ab5e7-a525-426c-a9fa-b4f0cfea0025.mov

**Comment by amrbashir** [comment]
That's a lot of bugs in one issue, I will focus on the first one then see if it solves the other two or if they aren't related.



> Seems like it's a threading issue on the event loop. There's some cases:
> 
> * creating two visible windows works
> * creating two invisible windows does not work with the tao `dev` branch
> * creating one invisible window works if I change `execute_in_thread` to always run `PostMessageW` (seems like it was deadlocking on the ShowWindow call on window_state.rs, maybe because it was executed directly on the event loop thread?)
> * creating two invisible windows works if I change `execute_in_thread` to always run `PostMessageW` and comment out the code that sends `Focused` events (it seems like it is stuck sending such events, blocking the event loop).
> 
> @amrbashir I think only you can fix this LOL

I tracked it to this tao [commit](https://github.com/tauri-apps/tao/commit/01fc43b05ea41463d512c0e3497971edc543ac9d) and I don't know how did this go unnoticed for so long but I will look more into it today.

Edit: Since that commit is just porting winit's `new-keyboard` branch, it is worth noting that this bug exists there too.

Edit2: A little progress, it deadlocks in the call to `KeyEventBuilder::process_message` in https://github.com/tauri-apps/tao/blob/11dac10241330c30aae660a2621d43ee5eb3775d/src/platform_impl/windows/event_loop.rs#L906-L911

Edit3: turned out go be a different deadlock

**Comment by amrbashir** [comment]
Hopefully fixed in https://github.com/tauri-apps/tao/pull/338. @xuchaoqian If you can, try test it by adding the following in your `Cargo.toml`.
```toml
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tauri", branch = "fix/windows/keyboard-deadlock" }
```

**Comment by lucasfernog** [comment]
Typo alert: it's `tao = { git = "https://github.com/tauri-apps/tao", branch = "fix/windows/keyboard-deadlock" }` instead of `tao = { git = "https://github.com/tauri-apps/tauri", branch = "fix/windows/keyboard-deadlock" }`

**Comment by lucasfernog** [comment]
Also you need to run `cargo run -p tao` on your example.

**Comment by xuchaoqian** [comment]
Awesome! All three bugs have gone away on the tauri-examples project!
I am going to try this in our app and give the feedback here soon.

**Comment by xuchaoqian** [comment]
I have tried this in our app, and it works just like a charm!

Thank you very much. @amrbashir @lucasfernog
