### ISSUE TITLE
[bug] can't connect to tauri.localhost

### ISSUE THREAD

**Issue by alvaroblanco1** [tauri-apps/tauri#3647]
### Describe the bug

Using angular when opening a router link on the build version always gives a 
This site can’t be reached; tauri.localhost refused to connect;
This does not happen on the dev version due to the fact that the dev version is not running on tauri.localhost but on http://localhost:4200.

In order for a route link to work on angular every link must lead back to index.html. I assume this works on the dev version since it receives information from the local webpack server. However, on the build version when a new window opens there is no information being sent so the routes always fail to complete. This happens on something as simple as a <a target="_blank"> or even left click open link on a new window.

I don't understand what the issue could be or if there is a way to resolve it so that on the installed version these new windows actually complete.

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 99.0.1150.30
Visual Studio Build Tools:
   - Visual Studio Build Tools 2019

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.7
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.5.3
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.cache
/.firebase
/.git
/.github
/dist
/e2e
/node_modules
/src
/src-tauri

App
  tauri - 1.0.0-rc.4
  tauri-build - 1.0.0-rc.3
  tao - 0.6.3
  wry - 0.13.3
  build-type - bundle
  CSP - unset
  distDir - ../dist/my-app
  devPath - http://localhost:4200/
  framework - Angular
  bundler - Webpack
```

**Comment by amrbashir** [comment]
Please provide a minimal repro or steps to reproduce with some snippets.

**Comment by alvaroblanco1** [comment]
Yes I put together this version. You can test it out yourself. The dev build routes work fine. And each work no matter if they open using target="_blank" or by left clicking open on a new window but they do not work on the build version.

https://github.com/alvaroblanco1/angular-router-tauri

**Comment by lucasfernog** [comment]
Thanks for the repro app, we'll take a look.

**Comment by lucasfernog** [comment]
Couldn't reproduce on macOS. I'll try Windows tomorrow.

**Comment by lucasfernog** [comment]
If I understood correctly, your problem is that you want to open your build content in the browser and it's failing right? If that's the case, it's indeed the correct behavior, your application assets are only visible to the app webview itself for security reasons. On dev this works because the development server is external (generated by Angular) and visible to the entire OS.

If you need to open your app URL in the browser, you'll need something like [tauri-plugin-localhost](https://github.com/tauri-apps/tauri-plugin-localhost).

**Comment by jiangzihan** [comment]
I had the same problem, how did you solve it?

**Comment by wis-graph** [comment]
I had the same problem

I checked the build settings because it seemed that Tauri did not read any of the front-end code during the build. 

The front-end build folder was configured as ./build, 
but the default Tauri setting is configured as ./public for the front-end build folder. 

After changing the option, it worked well.

**Comment by naruto00fa** [comment]
I had the same and solved by this, hope helps you too:

https://github.com/tauri-apps/tauri/discussions/4052
