### ISSUE TITLE
[bug] dotenv not work in production

### ISSUE THREAD

**Issue by red010182** [tauri-apps/tauri#3825]
### Describe the bug

I'm using dotenv crate to save some important informations like access keys and secrets by saving them in the `src-tauri/.env` file. It works perfectly in dev but fail to load in release mode.

[dotenv](https://crates.io/crates/dotenv)

```rust
//.env
KEY=ABC
SECRET=DEF


// main.rs
fn main() {
    dotenv::dotenv().ok();
    let key_id = dotenv::var("KEY").unwrap_or_default(); // empty in release mode
    let secret = dotenv::var("SECRET").unwrap_or_default();  // empty in release mode
    // ...
}
```

### Platform and versions

```shell
Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.5 (outdated, latest: 1.0.0-rc.8)
  @tauri-apps/api - 1.0.0-rc.1 (outdated, latest: 1.0.0-rc.3)

Global packages
  npm - 8.3.1
  pnpm - 6.24.3
  yarn - Not installed

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-apple-darwin 

App directory structure
/test
/dist
/node_modules
/public
/src-tauri
/.git
/.vscode
/src

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-rc.3
  tao - 0.6.2
  wry - 0.13.2
  build-type - bundle
  CSP - default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost; connect-src *
  distDir - ../dist
  devPath - http://localhost:8080/
  framework - Vue.js (Quasar)
  bundler - Webpack
```

**Comment by JonasKruckenberg** [comment]
This will not work in release mode because the released binaries does not have the folder structure you have during development (specifically there is no `src-tauri` folder in release mode). The dotenv crate reads the file dynamically at runtime. So it's reasonable that this does not work in production, as there is not dotenv file. 

As for workarounds, you can try to include the dotenv file into the final bundle using Resources: https://tauri.studio/docs/api/config#tauri.bundle.resources but that might not work because resources are not necessarily placed in the same folder as the binary.

In general its worth noting that the dotenv crate really is meant for servers written in rust, where you deploy into a known and controllable environment and need a way to declaratively set env variables. In the context of desktop apps, anything that requires additional files at runtime to work correctly is a bit suboptimal.

**Comment by red010182** [comment]
Thanks for reply. Ok, let's forget about dotenv. 

So, where should I save config that can be read at runtime in rust while at the same time protect these files from being accessed by user?

**Comment by JonasKruckenberg** [comment]
That depends, what do you need that config file for anyway? Can you just replace a config file with compile time constants? That would be the safest option.
