### ISSUE TITLE
[docs] Improve docs on tray icon template

### ISSUE THREAD

**Issue by elvinaspredkelis** [tauri-apps/tauri#3857]
### Describe the problem

It seems to be rather difficult to set different variants of the tray icon depending on the display mode.

For example, on macOS the tray icon is either black or white, therefore it is impossible to have a "universal" icon for both modes. If a white icon is set, it is barely visible in the system tray if light mode is enabled.

### Describe the solution you'd like

I was told on discord that it is possible to do it manually somehow, however, it appears to be difficult to do.

1. Have an example in the docs on how to set the tray icon depending on the display mode in addition to the current instructions (https://tauri.studio/docs/guides/system-tray/#updating-tray-icon).
2. It would be amazing if there would be some tooling built in for handling such use case. If I am not mistaken, electron somehow adjusts the image settings on the mode switch (https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image). Perhaps this could be an option?

**Comment by elvinaspredkelis** [comment]
Turns out it was supported by setting `"iconAsTemplate": true`. Might still be an issue with non-macOS.

Closing this issue. Perhaps expanding the docs on this would be amazing?

**Comment by betamos** [comment]
I'm using `iconAsTemplate: true`. On MacOS, it enforces monochrome + alpha (no color), including for dynamic `TrayHandle.set_icon` updates.

This option seems to do nothing on Windows and Linux, so the icon is full color. This is consistent with many other apps in these environments. Windows, KDE and Gnome are much more relaxed in their design guidelines - that said, anecdotally modern DEs and apps seem to be slowly moving in Apple's direction of monochrome/low-color tray icons.

There's no support in Tauri AFAIK for knowing if the tray bar is dark or bright, which means that white or black could both go wrong. Instead, make sure you have an icon that works on both dark and bright backgrounds if you want it to be visible on all platforms (I have a two-color icon myself). Gnome/KDE is highly configurable and so different backgrounds are common.

**Comment by FabianLars** [comment]
> This option seems to do nothing on Windows and Linux

Yep, macOS only

> Instead, make sure you have an icon that works on both dark and bright backgrounds if you want it to be visible on all platforms

Yeah, as said on discord too, i totally second that. It's pretty much impossible to get the tray color right on linux and windows.
For example on gnome no matter if dark mode (talking about both the new gnome 42 dark mode and the "old" adwaita-dark thingy) the top bar is black, but it can probably be styled too. Don't remember the situation with the dash-to-panel extension. And not the mention the >10 other DEs out there...

Then there is windows, which on first glance looks easier since we at least can easily detect if the system has dark mode enabled. But this approach breaks as soon as the user ticks the "Use accent colors for Start, Taskbar and info center"(translated) option, with that the taskbar _and_ the systemtray can have _any_ color... Of course supporting every color is pretty much impossible, but i still wanted to highlight that it's not as easy as it might seem.
