### ISSUE TITLE
[feat] Read_dir could add some new options

### ISSUE THREAD

**Issue by PuffMeow** [tauri-apps/tauri#4114]
### Describe the problem

l want to read specified files and hide the hidden files when l call read dir function.Or is there any other solutions?

### Describe the solution you'd like

The read_dir api can add some new options, such as "filter" and "is_show_hidden", the "filter" option can filter specified files based on file suffixes.  And the "is show_hidden" option can determine whether to find hidden files based on the conditions.

**Comment by PuffMeow** [comment]
Maybe I can write a Rust function that can be called by JS. But I think the options above I mentioned is still neccessary.

**Comment by JonasKruckenberg** [comment]
This is generally difficult to archive since what you consider hidden files (or unwanted files) might be different from what other people consider unwanted files.

You can always do the filtering as a second step, go through all the entries returned by `read_dir` and filter them based on your requirements. You can do trivially do that both in JS and Rust.

**Comment by PuffMeow** [comment]
Ok. Thanks, I got you.
