### ISSUE TITLE
[bug] Command line output disabled on release build

### ISSUE THREAD

**Issue by dolphin54** [tauri-apps/tauri#4118]
### Describe the bug

Probably not exactly a bug but basically on the main function depending on the args passed in, i would like to output to the command line (where the app is typed out to be executed).
e.g. mycli runwinapp -> run windows app
mycli show status -> shows output in the same cmd window, as normal dos output.

Obviously if they kicked it off from windows explorer or something it could either show nothing or open a cmd window for output.

This all works in dev mode but as for release, you (probably rightly) removed the cmd output (remove cmd libaries).

I would like to keep it working the same way showing the output.
I have tried various ways include the allowlists true etc... can't get it to work.
All windows box.

Would love to get this working.

Regards
Den

### Reproduction

place println!("hello world") 
first line in main before opening the window.

### Expected behavior

e.g. mycli runwinapp -> run windows app
mycli show status -> shows output in the same cmd window, as normal dos output.

### Platform and versions

```shell
> vitetest@0.0.0 tauri
> tauri "info"


Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.39
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Community 2019
  › Node.js: 17.8.0
  › npm: 7.6.3
  › pnpm: Not installed!
  › yarn: 1.22.4
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.10)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.5)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Sooo, this is one really weird thing about windows. Remember the first 4 lines in your main.rs function that say something with `windows_subsystem`? This is for changing the app into "gui" mode, which basically uncouples it from the console. To see why this is needed, remove it and double click the exe.

Afaik you _can_ dynamically re-attach the console so that you can print again, but idk how (it needs platform apis and isn't implemented in tauri).

This is why half of our built-in CLI feature is kinda useless on windows :/

**Comment by lucasfernog** [comment]
I'll close this issue since you need to either remove the `windows_subsystem` thing or find a way to attach a console to your app, we won't provide this kind of thing. At least the first option is an easy one, thanks Windows.

I had to find out about this the hard way at work because someone changed the file to always set the `windows_subsystem` attribute, then dev was completely weird lol
