### ISSUE TITLE
[feat] Add an API that can open a folder directly. Not the dialog.open()

### ISSUE THREAD

**Issue by PuffMeow** [tauri-apps/tauri#4150]
### Describe the problem

I can't find any related API in the document.  

### Describe the solution you'd like

I hope the API can open the folder directly based on a path parameter.

**Comment by PuffMeow** [comment]
When this function be called, it can open the OS's file explorer.

**Comment by FabianLars** [comment]
You can do this already with shell.open which will open the explorer if given a file path; or shell.Command which needs to be manually set up per OS, but can be expanded, for example if you want to preselect files, see tauri-apps/plugins-workspace#999.

That said i'm closing this as a duplicate because tauri-apps/plugins-workspace#999 should cover this too.
