### ISSUE TITLE
`Cmd+Option+I` not working on macOS 10.15

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#4239]
**Describe the bug**
`Cmd+Option+I` does not open the devtools on macOS 10.15

**Platform and Versions (please complete the following information):**
OS: macOS 10.15.7
Rustc: 1.61.0

**Would you assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Additional context**
cc @lucasfernog

**Comment by FrankenApps** [comment]
Did you click into the HTML content before executing the shortcut?
Are you running in debug mode (e.g. `cargo run`)?
For me this works on the latest macos, but it is not sufficient to focus the window (by clicking at the titlebar for example).

**Comment by lucasfernog** [comment]
For now you need to click in the HTML content like Franken said above, because we're using [hotkeys](https://github.com/jaywcjlove/hotkeys) since tao doesn't offer any window-specific shortcut API (and it seems like the keyboard events are not fully implemented, it doesn't trigger on macOS at all and on Linux it only triggers on regular keys, not modifiers).

**Comment by probablykasper** [comment]
It does seem to work now actually, not sure why it didn't before

**Comment by Isaac-Leonard** [comment]
I'm experiencing this too and can't seem to make it work no matter what I do
