### ISSUE TITLE
[bug] AppImages made with tauri do not run on all still-supported Ubuntu releases

### ISSUE THREAD

**Issue by probonopd** [tauri-apps/tauri#4276]
### Describe the bug

AppImages made with tauri do not run on all still-supported Ubuntu releases in case they contain binaries built on systems newer than the oldest still-supported Ubuntu release.

### Reproduction

1. Run the oldest still-supported Ubuntu LTS release
2. Download the AppImage from https://github.com/nymtech/nym/ (made with tauri)
3. Try to run it; you will get `libc.so.6: version 'GLIBC_2.29' not found (required by nym-wallet)`

### Expected behavior

Runs

### Platform and versions

```shell
I don't have this information, as neither npm nor cargo are installed on the system I am trying to run the AppImage on
```

### Stack trace

```shell
https://github.com/AppImage/appimage.github.io/runs/6744305757?check_suite_focus=true#step:4:402
```

### Additional context

To avoid this kind of issue, tauri could
* Ensure that all ingredients that go into the AppImage are built on sufficiently old build machines (i.e., no newer than the oldest still supported LTS Linux distributions) - this is what major projects like Firefox, LibreOffice, Electron, etc. are doing
* As a last resort, bundle _everything_ privately, down to and including glibc (or something more bundling friendly like musl libc)

Note that this is not AppImage specific. The same considerations would need to be made if one would want to distribute executables for Linux in e.g., zip files.

**Comment by FabianLars** [comment]
This is not about any "ingredients" of the appimage, but mainly about the binary itself. Generally the mantra is: "_build_ on the oldest system you want to support", for reference our docs on this: <https://tauri.studio/v1/guides/distribution/linux#limitations>.

Taking nym-wallet as an example they use "ubuntu-latest" in their workflow instead of "ubuntu-1804".

And as you said, it's not just appimage specific, .deb has the same problem and _we_ can't really do anything about that one for example.

> To avoid this kind of issue, tauri could
> Ensure that all ingredients that go into the AppImage are built on sufficiently old build machines (i.e., no newer than the oldest still supported LTS Linux distributions) - this is what major projects like Firefox, LibreOffice, Electron, etc. are doing

There is absolutely no way for _us_ to ensure that.

> As a last resort, bundle everything privately, down to and including glibc (or something more bundling friendly like musl libc)

"private" bundling: kinda possible, but the tooling that does that is not cross-distro yet (blocker for us) and vastly increases appimage size.
musl: not really possible atm because a) harder to use for the average user and more importantly b) (still) not 100% compatible.

That said we're keep exploring in all directions especially because of [webkit versions](https://togithub.com/tauri-apps/tauri/issues/3961).

**Comment by probonopd** [comment]
> This is not about any "ingredients" of the appimage

That's what I meant by "ingredients", the binaries inside the AppImage, or .zip, or .deb, or whatever ormat.

> And as you said, it's not just appimage specific, .deb has the same problem

Exactly!

> There is absolutely no way for us to ensure that.

Well, here is how I "ensure" (well, at least approximately) it in a similar tool of mine, linuxdeployqt:

https://github.com/probonopd/linuxdeployqt/blob/66d6eeea28efb1a6a03e8c69670b634b27025260/tools/linuxdeployqt/main.cpp#L190-L212

I think that erroring out if the glibc version is too new is a good measure to get developers to fix this right from the beginning, as opposed to putting out packages that then disappoint users later on, leading to issue tickets at a later time.

> Generally the mantra is: "build on the oldest system you want to support", for reference our docs on this: https://tauri.studio/v1/guides/distribution/linux#limitations.

That's my mantra too - but in my tools I add some checks to make sure that developers using my tools are aware of this mantra (surprisingly many aren't). Maybe you'd consider doing that as well?

**Comment by probonopd** [comment]
Just as an indication, out of the handful of applications using tauri that I tested, _none_ ran on my system. Either they need too new libraries, or they are missing libraries like libwebkit2gtk that cannot reasonably be assumed to be installed on all target systems. So it would be great if the tauri tooling could help application developers to produce higher-quality AppImages.

I'd he happy to help with ideas and suggestions as I have accumulated quite some experience with AppImages over the years.

**Comment by FabianLars** [comment]
> That's my mantra too - but in my tools I add some checks to make sure that developers using my tools are aware of this mantra (surprisingly many aren't). Maybe you'd consider doing that as well?

Everytime we add a new warning or similar, we get new issues and tons of discord messages about it (even with something simple like a message about an outdated tauri-cli) 😅
And yeah, really nobody reads the docs so i could agree on a _warning_ (with a link to the docs?) as long as it doesn't stop the bundler, because it's legit and because of webkitgtk really common to build on newer systems, especially if you just want to quickly share your development progress with a friend for example.

> Either they need too new libraries

That's why i wanted to change our tauri-action docs/readme to use ubuntu-1804 but never got around doing it :/

> or they are missing libraries like libwebkit2gtk

This means they built they app >1 year ago (or with dependencies that old), can't do anything about that 😅

**Comment by probonopd** [comment]
> That's why i wanted to change our tauri-action docs/readme to use ubuntu-1804 but never got around doing it :/

:+1:
