### ISSUE TITLE
Prepare for Global Installation

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#43]
**Is your feature request related to a problem? Please describe.**
Installing Tauri locally in projects is bloaty and annoying. 

**Describe the solution you'd like**
```
$ npm install --global @tauri-apps/tauri
```

**Additional context**
Well, this is more of a "does it work? what do we need to change to make it work?" kind of issue.

**Comment by kastenbutt** [comment]
I did a first test drive with a global tauri installation. It works, but with two caveats:

1. The Cargo.toml created by `tauri init` has relative references to tauri and tauri-ui because it assumes tauri is installed in the local node_modules folder. This can be easily solved by changing the path, but its not a great dev experience and brings problems for version control as the global path will be different on each machine. Could this be solved by having both crates at crates.io or another registry?
2. Cargo puts the build results for all dependencies in the local target folder. So, for each tauri project, tauri and its dependencies will be built. I guess this goes against the expectations of a global tauri installation. The bloat introduced by several local tauri installations is small compared to the few hundreds of MB each local target folder will have. This could be mitigated by a [global cargo cache](https://internals.rust-lang.org/t/idea-cargo-global-binary-cache/9002/31).

**Comment by nothingismagick** [comment]
One other concern is also the way in which we are shipping the bundler. Depending on whether people use npm, git, yarn or something else - this just won't work:

```
$ cargo install --path node_modules/@tauri-apps/tauri/tools/rust/cargo-tauri-bundle --force
```

**Comment by nothingismagick** [comment]
@lucasfernog @tensor-programming - we need to have a think about this - and potentially make it a full fledged crate and discard the mono-repo approach.

**Comment by nothingismagick** [comment]
its been proven to work by @lucasfernog - so closing this. will make a note of it in the docs and the forthcoming readme revision.
