### ISSUE TITLE
[feat] The Window Menu does not have a hide function

### ISSUE THREAD

**Issue by MyAlfisti** [tauri-apps/tauri#4401]
### Describe the problem

Windows 10/11 windows have a hidden menu bar by default.
Windows 11 does not have a menu bar in the first place.
Tauri's Window Menu does not have a Show/Hide option.

### Describe the solution you'd like

Provide a Show/Hide argument for the Window Menu as an option.

### Alternatives considered

None

**Comment by amrbashir** [comment]
You can use https://docs.rs/tauri/latest/tauri/window/struct.MenuHandle.html#method.hide

and if you don't want the menu, you can remove it from `src-tauri/src/main.rs` or conditionally enable it for macOS because on macOS, if you don't have a menu with `Copy/Paste/Cut`, the keyboard shortcuts for copy/paste/cut won't work.
