### ISSUE TITLE
[bug] Unable to init server on wsl2

### ISSUE THREAD

**Issue by CaptainKeys21** [tauri-apps/tauri#4478]
### Describe the bug

When I create a tauri app with the `create tauri-app` and I try to initialize the dev script (yarn, npm or cargo), the cli returns `Unable to init server: Could not connect: Connection refused`. Also when I try to access the localhost directly in the browser, it says that " The connection has been reset". I think this is a tauri bug, because when I run dev another normal react project, localhost can be accessed normaly.

### Platform and versions

```shell
Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: 6.11.0
  › yarn: 1.22.15
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
```

**Comment by FabianLars** [comment]
This error is not talking about the frontend devserver or something from tauri.
It's an x11 error that happens when it tries to open/display the gui (the actual tauri app). This specific error should mean that you don't have an xserver installed (on windows) and/or don't have `DISPLAY` configured to point to it.
Hopefully that's enough of a pointer for you to figure it out 😅 

Btw, we currently don't support (as in "help") for developing tauri apps in wsl, mainly because it only really works "good enough" in Windows 11 with wslg.

> Also when I try to access the localhost directly in the browser, it says that " The connection has been reset"

This is probably because the devserver shuts down when the app itself can't start or crashes.

**Comment by CaptainKeys21** [comment]
Yep, that was good enough. Thanks!
