### ISSUE TITLE
[feat] Enable the possibility to dynamic link to vcruntime on Windows

### ISSUE THREAD

**Issue by Berrysoft** [tauri-apps/tauri#4565]
### Describe the problem

Due to #4227 , the vcruntime is statically linked instead of merged module on Windows. It may reduce prompts when installing, but increases the binary size, and it cannot benefit from the patches of Microsoft.

### Describe the solution you'd like

Add a switch in the `tauri.conf.json` to enable dynamic link to vcruntime. It should be `false` as default, as [someone](https://github.com/tauri-apps/tauri/issues/4122) doesn't like the prompts from the installer:(

**Comment by FabianLars** [comment]
Just did a really quick test and we're talking about a 30KB binary file size increase or 16KB in the compressed msi, without the merge module.
Speaking of the merge module, it's 1.15MB in size, so imo the file size argument isn't valid here.

> it cannot benefit from the patches of Microsoft.

Well afaik merge modules can't either. You'd have to use/distribute the Visual C++ Redistributable Package. And while this is recommended over static linking by microsoft it's makes the installation more complicated.

> as https://github.com/tauri-apps/tauri/issues/4122 doesn't like the prompts from the installer:(

Yeah because users, especially less tech-savvy ones, panic hard if an installer for some small app wants to close your browser and _gpu related_ stuff etc.

P.S. you can already do dynamic linking if you don't need the .msi by building the app via
```sh
$env:STATIC_VCRUNTIME="false"
cargo build --release --features=custom-protocol
```
Note that standalone exes are not really distributable, especially not with a dynamically linked vcruntime.

All that said i'm going to close this issue (if a team member thinks it makes sense to account for the env var in the tauri cli they can just re-open it 🤷 -> This wouldn't re-introduce the merge module, but the msi bundler picks it up automatically if you copy it in the target dir)

**Comment by Berrysoft** [comment]
> P.S. you can already do dynamic linking if you don't need the .msi by building the app via

Yes, but the `tauri` cli will set this environmental variable to `true`. I'm asking an option to turn it off with tauri cli.

Anyway, thanks very much.

**Comment by FabianLars** [comment]
Yeah, that's why i used cargo in the example and mentioned that you won't get a msi bundle.

But anyway, see #4601 :)
