### ISSUE TITLE
[bug] The msi setup wizard needs to close the unrelated programs

### ISSUE THREAD

**Issue by l1xnan** [tauri-apps/tauri#4581]
### Describe the bug

The msi setup wizard needs to close the unrelated programs, what are the configurations to avoid it?
![image](https://user-images.githubusercontent.com/6105390/177071985-ec7b4876-1cb8-4d33-9267-53c94cd4942b.png)

### Expected behavior

When installing MSI, do not close the unrelated programs

### Platform and versions

```shell
> tauri "info"


Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.44
  › MSVC: 
  › Node.js: 18.4.0
  › npm: 8.12.1
  › pnpm: 7.5.0
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment]
On issues like this, please always post the full output of `tauri info`, because now the most important info, the tauri versions, is missing :/

Anyway this was fixed in one the last release candidate versions, so please update tauri to stable, _and remove the target/ dir_ (or at least all files with a `.msm` file extension in `target/debug/` and `target/release/`)
