### ISSUE TITLE
[feat] Disable tauri-driver on production build

### ISSUE THREAD

**Issue by jolic** [tauri-apps/tauri#4590]
### Describe the problem

The webdriver (tauri-driver) is available also if we build a production app. 
Wouldn't it be good if we could disable that (with a flag)? 

### Describe the solution you'd like

I would like to not build the tauri-driver stuff in the production build.

**Comment by chippers** [comment]
The reason why we didn't originally add a way to disable WebDriver in builds is that only the Linux implementation supports it (and the builder to enable it `WebContext`), whereas WebView2 on Windows had no way to disable WebView2 support from what I saw when I first implemented it (maybe this changed?).

It's been a while, but I remember the original conversation somewhat and we decided that having a flag/option to disable it on Tauri would be confusing because it would only do it on Linux.  We _could_ still do something even though it would only affect Linux, not sure if it would be a build flag or an option on the builder or similar. It was originally written as a Cargo feature, but a common case of using WebDriver is testing the production application as it is released to users and it was simpler to make the not-really-optional inclusion of it as an env var.
