### ISSUE TITLE
[feat] Support `binstall` for `tauri-cli`

### ISSUE THREAD

**Issue by erayerdin** [tauri-apps/tauri#4651]
### Describe the problem

In order to install `tauri-cli`, you do `cargo install tauri-cli`, which pulls the source and dependencies and compiles them. This is too slow and consuming too much CPU and memory resource.

### Describe the solution you'd like

[cargo-binstall](https://github.com/ryankurte/cargo-binstall) fetches already-compiled binaries and installs them instead of compiling from zero.

### Alternatives considered

[cargo-quickinstall](https://github.com/alsuren/cargo-quickinstall) is another alternative although I have not used it.

**Comment by FabianLars** [comment]
Yeah i thought about this stuff too, the problem is that our CI for publishing the CLI already takes _ages_ (40 minutes _after_ everything else was published) and this would add another ~30 minutes on top :/

But still, we should look into adding it anyway, this is like the only real downside of `cargo install` for most users.

**Comment by JonasKruckenberg** [comment]
I think this is a great idea, the problem with CI times is real though, so adding support for this is out of the question right now imo.
But after we had someone look at our untenable CI situation we should definitely consider this!

**Comment by erayerdin** [comment]
Mine is just an idea. I don't know the internals of this project but I can see you are using Github Actions.

*Maybe*, just for building the CLI, you can use another service, like Travis or CircleCI, *just for CLI*. And then upload the binary to the latest tag.

As I've said, I don't know about the internals. Maybe building CLI requires another step to be successfully completed, in which case, my suggestion just renders useless.

**Comment by FabianLars** [comment]
Maybe we can resurrect the binary-releases repo for this, or would this change nothing about the runner usage limits? 

_Edit:_ And i would only start with more popular architectures and not be as throughout as with the node cli, because in this case missing arches can still be installed via `cargo install`.

**Comment by lucasfernog** [comment]
I don't think changing the repo would enhance it. Opened a PR for this :)
