### ISSUE TITLE
[feat] allow http for local updater distribution

### ISSUE THREAD

**Issue by drwhorx** [tauri-apps/tauri#4687]
### Describe the problem

im on a network where the clients are not exposed to the internet and i need to push updates to their machines. it is terribly inconvenient to have to set up SSL (exhibit a: i don't know how) when my updater server can just be a simple express http server. there is no need for the security hoops to jump through when i'm just pushing updates on a local network.

### Describe the solution you'd like

allow http updater endpoints when just on a local network.

**Comment by qwertasyx** [comment]
Hey, i got kind of the same problem for an internal application. Did you find a way  without adding ssl?

**Comment by dukeeagle** [comment]
Hi everyone! I wanted to bump this and see if anyone else is facing this

**Comment by scarletjack** [comment]
Hey guys, wanted to bump this as I'm also needing the functionality.

**Comment by faramozzayw** [comment]
Hey guys, is anyone working on this feature? I've already implemented this feature for myself by extending `UpdaterConfig` with a new field, `allowHttpEndpoint`, which allows me to bypass the HTTPS requirements. This seems to work very well, but I can't use Github actions (`tauri-apps/tauri-action@v0`) because it doesn't know about the new field.

So I'm just curious should I wait for implementation or is there any way I can help with this feature?

**Comment by domsleee** [comment]
Hello all, I am also interested in this feature, it is more convenient if the security risk is acceptable for the use case.

The changes in @faramozzayw's branch look promising, I will give it a try:

https://github.com/tauri-apps/tauri/compare/dev...faramozzayw:tauri:feat/allow-http-endpoint

**Comment by amrbashir** [comment]
Opened https://github.com/tauri-apps/plugins-workspace/pull/1814 to add an option for tauri-plugin-updater in v2. V1 will not support this for security reasons.
