### ISSUE TITLE
[feat] Marriage with Fresh Framework

### ISSUE THREAD

**Issue by TimSusa** [tauri-apps/tauri#4743]
### Describe the problem

We can be better. Waiting for a one click everything makes world better button...  Fresh ships with (P)React, Typescript and seems to outerperform the nextjs framework and all lame other stuff in my opinion. If we could even come up with an 1,2,3 migration guide for nextjs people you could massively increase your audience

### Describe the solution you'd like

https://fresh.deno.dev/
and
https://www.youtube.com/watch?v=Q4dos7-gX68

**Comment by amrbashir** [comment]
Why would tauri make a migration guide from a web framework to another? tauri doesn't care what you use for your frontend at all.

**Comment by strogonoff** [comment]
> Why would tauri make a migration guide from a web framework to another? tauri doesn't care what you use for your frontend at all.

Tauri shouldn’t make a migration guide just for Next.js (I personally don’t know anyone using it to be honest), but because both are Deno ecosystem (which is traditionally brought up as Deno’s weak point) an integration/interoperation guide for Tauri + Fresh would benefit adoption of both and Deno ecosystem as a whole.

**Comment by FabianLars** [comment]
Well to be fair, that's not a _migration_ guide, but just a plain getting started guide for nextjs, just like vitejs has one. It exists because a) nextjs is really popular, b) it needs a special config (nextjs in SSG mode), and c) we don't really limit what frameworks can have a getting started guide (btw, we'd like to have more of them), though we currently limit it to frameworks that can work in tauri without having to bundle an additional nodejs or deno runtime alongside your app.

> I personally don’t know anyone using it to be honest

Not only is it one of the most used frameworks in general, it's also one of the most used framework in tauri, even though it has it's quirks because of its SSR-first approach.

And just in case the hints weren't obvious, we can't really recommend fresh in tauri apps until it has some kind of server-less mode, or until tauri has a _good_ deno integration.

**Comment by strogonoff** [comment]
> Well to be fair, that's not a migration guide

Oh, somehow I missed the fact that Tauri already has one for Next.js.

> quirks because of its SSR-first approach.

Yeah, unfortunately it turns out Fresh isn’t really SSG-oriented but focuses on SSR. If that’s taken care of, I’d assume Fresh would be much faster and smoother than Next thanks to partial “island” style hydration. But I guess that initial load time is considered less important for apps than for websites.

> until tauri has a good deno integration.

Ah I see, makes sense I guess. I thought they were a natural match because they’re both Deno :)

**Comment by FabianLars** [comment]
> because they’re both Deno :)

There is no trace of Deno in Tauri actually. The only thing they have in common is that they both use Rust.
(Well, and then there's https://github.com/tauri-apps/tauri/pull/5136 which replicates deno's code in some apis but the above point still stands)
