### ISSUE TITLE
[bug] Anchor tag not opening link in default browser

### ISSUE THREAD

**Issue by Matix-Media** [tauri-apps/tauri#4756]
### Describe the bug

When I create an anchor tag with target="_blank" and a href to some other domain and click on that anchor, the link does not get opened in the default browser but in a new tauri window.

### Reproduction

The code base is in a private company repo, but I can share the code snippet. I use svelte if that is for relevance.
```html
            <a href={detailsViewedOptimization.learnMore} target="_blank">
                <span class="underline">Learn more</span>
                <Icon IconName="external-link" />
            </a>
```
1. Startup tauri
2. Click on the link.

### Expected behavior

The link should normally open in the default browser.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.62
  › MSVC: 
      - Visual Studio Build Tools 2019
  › Node.js: 16.13.2
  › npm: 8.1.2
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.0-rc.5
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ .git
  ├─ .github
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment]
Do you have `shell.open` enabled in your allowlist?

Also, you should update `@tauri-apps/api` to a non-rc version too.

**Comment by Matix-Media** [comment]
> Do you have `shell.open` enabled in your allowlist?

I am not the rust developer for this project, but in tauri.conf.json the allowlist is set to:
```json
{
    "all": true
}
```

> Also, you should update `@tauri-apps/api` to a non-rc version too.

I assume the docs tell me how to update a rust crate, because I don't know how (as I stated, I am not a rust dev).

**Comment by lucasfernog** [comment]
`@tauri-apps/api` is not a Rust crate, it's an NPM package.

**Comment by Matix-Media** [comment]
Okay, so I updated `@tauri-apps/api` to version 1.0.2 but the problem is sadly not fixed.

**Comment by FabianLars** [comment]
Didn't expect it to fix it, that was mainly just to not get any other problems in the future 😅 

What does the link roughly look like? Because i can't reproduce this at all. The only thing (other than a special-case url) i could imagine would be that your frontend bundler removes the `target` for whatever reason, but even than the behavior would be different (it would open the link in the _current_ tauri window)

**Comment by Matix-Media** [comment]
The link looks like this: `https://********/optimizations/1` (domain censored).

This is happening in dev mode.  

I just realized something even more weirder, I have another link with a `target="_blank"` on a different svelte page, on which works fully as intended. I don't know what is happening...

The other link:
```html
        <a href={config.registerLink} target="_blank">
            <span class="underline">{$_("login.newHere.2")}</span>
            <Icon height="18px" width="18px" IconName="arrow-forward" />
        </a>
```
The URL: `https://********/register` (domain censored, same domain as other link).

**Comment by lucasfernog** [comment]
We can find the issue if you share a minimal repo we can use to reproduce it.

**Comment by Matix-Media** [comment]
Well, I would need some time to create a reproduction repo, as the app I am working on is closed source, and I am under a NDA.
I would need some time for that though.

**Comment by nguyenvanduocit** [comment]
Here is my solution (vue)

## Html

```template
<button class="btn btn-primary" @click.prevent="openFacebookPage"> <i class="fe fe-phone-call"></i> Contact us</button>
```

## JavaScript

```javascript
import { open } from '@tauri-apps/api/shell';
const openFacebookPage = () => {
  open("https://www.facebook.com/aiocean.io/")
}
```

##

**Comment by Matix-Media** [comment]
> Here is my solution (vue)
> 
> ## Html
> ```
> <button class="btn btn-primary" @click.prevent="openFacebookPage"> <i class="fe fe-phone-call"></i> Contact us</button>
> ```
> 
> ## JavaScript
> ```js
> import { open } from '@tauri-apps/api/shell';
> const openFacebookPage = () => {
>   open("https://www.facebook.com/aiocean.io/")
> }
> ```

I used that solution too, but it sadly wont work with everything. for example, in one place i need to put in translations, and inside of that translations is an anchor tag. That way I cant call svelte/vue component functions from that control.

```ts
{@html $_("optimizer.tagWarning.messages." + warningTag.tag, {
                values: {
                    tweak: warningTag.optimization.name,
                    beginFeatureBreaking: `<a class="underline" href="${warningTag.optimization.learnMore}" target="_blank">`,
                    endFeatureBreaking: "</a>",
                    beginReportProblem: `<a class="underline" href="${config.reportProblemLink}" target="_blank">`,
                    endReportProblem: "</a>",
                },
            })}
```

**Comment by lucasfernog** [comment]
An entire HTML element in a translation value is crazy though, you could probably just translate the URL.

**Comment by Matix-Media** [comment]
> An entire HTML element in a translation value is crazy though, you could probably just translate the URL.

Would it be smart to put an HTML element in the translations? Also, this doesn't change the tauri issue.

**Comment by lucasfernog** [comment]
If you only translate the URL then you could use the workaround calling `open` directly. I'm just waiting for a reproduction example to fix the issue.

**Comment by nguyenvanduocit** [comment]
> If you only translate the URL then you could use the workaround calling `open` directly. I'm just waiting for a reproduction example to fix the issue.

Totally agree. If you still want to translate whole DOM. you have to listen to the click event then call `open`.

**Comment by nikunjitaliya2** [comment]
if you want to jump into app to chrome when click on button you can use this code in angular


 shell.open("example.com")

**Comment by wangzhigang1999** [comment]
> Here is my solution (vue)
> 
> ## Html
> ```
> <button class="btn btn-primary" @click.prevent="openFacebookPage"> <i class="fe fe-phone-call"></i> Contact us</button>
> ```
> 
> ## JavaScript
> ```js
> import { open } from '@tauri-apps/api/shell';
> const openFacebookPage = () => {
>   open("https://www.facebook.com/aiocean.io/")
> }
> ```

This works for me !  ❤️❤️❤️

**Comment by 12a6** [comment]
I found the best approach:
1. In Cargo.toml `tauri = {version = "x.y z", features = [..., "shell-open"] }`
2. In tauri.conf.json 
```
"tauri": {
    "allowlist": {
      "shell": {
        "open": true // enable opening files/URLs using the default program
      }
    }
  }
```

Hope that helps

**Comment by FabianLars** [comment]
Closing this due to OP's inactivity and the missing reproduction. Once a reproduction is provided we will reopen this issue, thanks :)

**Comment by SpikeHD** [comment]
I have a theory as to what the original user, or maybe others, were experiencing! The Tauri shell plugin injects [this event listener](https://github.com/tauri-apps/plugins-workspace/blob/bc7eecf4202e7d23b987440c1cbd2da0f68c8bef/plugins/shell/guest-js/init.ts#L9) for use in opening links with `target = _blank`. Under most circumstances it works fine of course, but if there is an element within the anchor tag that also has a `click` event listener, and it calls `event.stopPropagation()`, then Tauri's event will never get triggered.

This could (I say *could* because just changing this would be a somewhat sizable breaking change, ie. for people that actually desire/expect/intentionally implement this behaviour) be solved by simply passing `true` to the `addEventListener` call, which is to enable `useCapture` ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#usecapture)). Consider the following example ([JSFiddle](https://jsfiddle.net/mzvhcusk/19/)):

```js
document.addEventListener('DOMContentLoaded', () => {
  const s2 = document.querySelector('#two span')
  const a1 = document.querySelector('#one a')
  const a2 = document.querySelector('#two a')

  s2.addEventListener('click', (e) => {
    e.stopPropagation()
    e.preventDefault()
  })
  
  a1.addEventListener('click', (e) => {
    console.log('It\'s me, anchor one!')
  })
  
  a2.addEventListener('click', (e) => {
    console.log('It\'s me, anchor two! But you\'ll never see this message...')
  })
  
  a2.addEventListener('click', (e) => {
    console.log('It\'s me, anchor two! But this time I work, because addEventListener is passed "true"!')
  }, true)
})
```

```html
<body>
  <div id="one">
    <a href="https://github.com/tauri-apps/tauri" target="_blank">
      <span>Click me! I will log to the console!</span>
    </a>
  </div>
  <div id="two">
    <a href="https://github.com/tauri-apps/tauri" target="_blank">
      <span>Click me! I will NOT log to the console!</span>
    </a>
  </div>
</body>
```

I have been experiencing this in both v1 and v2 for a long time, and would love to see even just a shoehorned-in option to pass somewhere that will make the shell plugin pass `true` :P

**Comment by delebash** [comment]
The solution In Cargo.toml` tauri = {version = "x.y z", features = [..., "shell-open"] } `  no longer works.  The feature shell-open is not available for tauri v2.  What is the proper way to have all external links with target="_blank" open in the default browser window and not in the tauri window..  I do not want to have to use shell open('http://...) in my frontend code for each link I want to open in a new browser.  Example code for vue3 
 
```
<a :href="`${getAuthUrl}`" target="_blank">Login to your Account here and
                  enter your authorization code in the field below. Then click get access key. </a>
```

Since target is blank this should open in the default browser window.  Thanks.

**Comment by delebash** [comment]
Figured it out.  For v2 if you are using the tauri cli you can run `npm run tauri add shell` this will setup the plugin correctly.  In your capabilities folder default.json make sure you add  "shell:default" to your permissions. Once shell is installed _blank is respected and all links are opened in the default browser, otherwise without shell installed it will open inside of the tauri window.

**Comment by mert-kurttutan** [comment]
> Figured it out. For v2 if you are using the tauri cli you can run `npm run tauri add shell` this will setup the plugin correctly. In your capabilities folder default.json make sure you add "shell:default" to your permissions. Once shell is installed _blank is respected and all links are opened in the default browser, otherwise without shell installed it will open inside of the tauri window.

@delebash On windows, the hyperlinks work fine without shell plugin, but on Linux, they don't.

**Comment by SleekGeek-254** [comment]
```
import { open } from '@tauri-apps/plugin-shell';

await open(url); 

```

Works fine on PC but on Andorid it opens the in app browser and i cannot close it or navigate back to my app
