### ISSUE TITLE
[feat] Nim integration

### ISSUE THREAD

**Issue by geotre** [tauri-apps/tauri#4829]
### Describe the problem

The homepage states 

> Go, Nim, Python, C++ and other bindings are possible with the stable API

Are Nim bindings planned by the core team or are they just a suggested possibility? If the latter do you have any pointers on how this integration should be created?

### Describe the solution you'd like

A rough timeline for Nim support _or_ guidance on how to get started adding it

**Comment by lucasfernog** [comment]
We're not planning any bindings at the moment, the focus is to ship mobile support first.

The integration will likely be done via a C FFI, similar to https://github.com/tauri-apps/tauri/tree/dev/examples/tauri-dynamic-lib

Unfortunately there's no timeline yet, we really want to ship mobile first. I'll close this since it won't be really discussed until v2 lands - and I'm also not sure if the Nim integration will be a priority since I haven't seen much interest in the community for it, I see much more Node.js requests.

**Comment by PhilippMDoerner** [comment]
Just for reference, I would hereby like to display interest in nim-bindings.

**Comment by mildred** [comment]
The tauri-dynamic-lib disappeared as part of #8723 in commit 8de308d1bf6a855d7a26af58bd0e744938ba47d8

**Comment by FabianLars** [comment]
It's still available in the 1.x branch and should probably still work in v2 with minimal changes (the usual v1 -> v2 migration)
