### ISSUE TITLE
[bug]  failed to bundle project - error running appimage.sh - Cannot deploy non-existing library file: target/release/bundle/appimage/linux-vdso.so.1

### ISSUE THREAD

**Issue by fogine** [tauri-apps/tauri#4937]
### Describe the bug

When running `yarn tauri:build` to build release bundle I get error:

> failed to bundle project - error running appimage.sh - Cannot deploy non-existing library file: project-root/target/release/bundle/appimage/linux-vdso.so.1

### Platform and versions

```
Environment
  › OS: Arch Linux Unknown X64
  › Node.js: 14.19.3
  › npm: 6.14.17
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: Set automatically by Vue CLI plugin
  › devPath: Set automatically by Vue CLI plugin
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ src
  ├─ dist
  ├─ bdscli
  ├─ public
  ├─ .git
  ├─ bds
  ├─ node_modules
  └─ src-tauri

```

**Comment by FabianLars** [comment]
Unlucky timing, some minutes before you someone created the same issue https://github.com/tauri-apps/tauri/issues/4936

Root cause: https://github.com/linuxdeploy/linuxdeploy/issues/210 - with a proposed fix in 211.

There's also a possible workaround on our side: https://github.com/harenber/qmapshack-AppImage/commit/b33b6f323d5b8fa0a15b370a223973f792f33f3b, but i don't think it's worth it because we'd probably need more time to release a new cli then for their fix to be released. And not to forget that arch appimages aren't distributable anyway.

I'll leave this open for now in case someone else stumbles upon this.
