### ISSUE TITLE
[bug] spawned children cannot be killed under windows

### ISSUE THREAD

**Issue by lukasbach** [tauri-apps/tauri#4949]
### Describe the bug

Under windows, children spawned with `const {kill} = await new Command(...).spawn()` cannot be killed with `kill()` under Windows. The kill command completes successfully, but the child process continues to run.

### Reproduction

[Repro repo](https://github.com/lukasbach/tauri-windows-kill-repro) (the implementation that reproduces the bug is here: https://github.com/lukasbach/tauri-windows-kill-repro/blob/main/src/App.tsx)

The repo only contains the result of `npm create tauri-app`, as well as a change to the tauri config to allow all shell commands, a dummy cli script to run `/dummy-cli-program.js` and the changes in `App.tsx`.
![tauri-windows-kill-repro](https://user-images.githubusercontent.com/4140121/184714033-3662edee-7e47-4391-b225-106e063182c8.gif)

I could reproduce this under two different Windows machine, one Win 10 and one Win 11.

### Expected behavior

The child should terminate and not run anymore when killed.

### Platform and versions

npm run tauri info

> tauri-windows-kill-reprod@0.0.0 tauri
> tauri "info"

Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 104.0.1293.54
  › MSVC:
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2017
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ .git
  ├─ .idea
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment]
I'm not really a react guy so i don't know what's happening and why, but if i remove the destructuring of Child it works again, so this seems to work:
```ts
        command.spawn().then((child) =>
            setTimeout(() => {
                child.kill();
                setOutput((output) => `${output}\nKILL SIGNAL SENT`);
            }, 1000)
        );
```
Only noticed this because there were an error with something about the pid in the console.

**Comment by lukasbach** [comment]
Hm yes, that fixed it for the repro 😅 But that wasn't the actual issue I had in my actual project, there this wasn't sufficient. I dug into this deeper, and found what I think was the issue for my actual project: Am I right in the assumption that processes spawned with `const child = await command.spawn()` and killed with `await child.kill()` will not terminate processes that themselves where spawned by `child`? In my project, `child.kill()` would not terminate the process, but running `taskkill /pid 123 /f /t` in a shell spawned also in tauri would do the trick. I guess that would be a workaround for me, but I'm wondering if this is how the `child.kill()` tauri command is intended. I won't bother for now to change my repro to demonstrate this, because I think if someone from the tauri team can confirm that this is the case that would be enough. 

So I'm wondering if someone can confirm that `child.kill()` is in fact not terminating subsequently spawned children by design?

**Comment by FabianLars** [comment]
> So I'm wondering if someone can confirm that child.kill() is in fact not terminating subsequently spawned children by design?

Well, i wouldn't call it by design because that sounds like it's intentional, but it's how it currently works, yes.

And this is also not a rare issue, for example this is also a problem with pyinstaller in single-file mode (mentioning it because python sidecars are getting somewhat popular rn), because it always spawns 2 processes, and the "parent" the rust side sees is just a small helper process x)

Edit: Yes, we do want to improve this.

**Comment by lukasbach** [comment]
Okay, thanks for the confirmation! Do you already have a ticket for that, than I would close this as duplicate? Or do you want me to create a ticket to track this/change this ticket's description to supporting recursively terminating spawned children?

**Comment by amrbashir** [comment]
We shouldn't care about killing subprocesses, we should only care about the one that we started via `Command`. Subprocesses are the responsibility of the process that spawned them.

**Comment by amrbashir** [comment]
It doesn't make sense for us to kill the subprocesses that we don't know about, because there is a use-case where you'd want to use `Command` to run a script or something and that script needs to be kept running as a daemon so you fork the process and keep it alive.

**Comment by FabianLars** [comment]
I used to think the same, but the problem is that as it turns out it's quite uncommon. And in cases like pyinstaller, where the main process is the leftover process, and they don't seem to have any intentions of "fixing" this, this would make it quite complicated for Tauri users, who tend to use python/etc sidecars to not do some (complicated) stuff in Rust.

tbh my main problem here really is pyinstaller because it's a question i get more or less daily and it seems to be impossible to fix from inside the python code (the wrapper/bootstrapper process doesn't send a kill event or anything to the main process).

though to be fair, with this PR https://github.com/tauri-apps/tauri/pull/4836 we will be able to fix it way easier in user's code, but it would still require some Rust code.

**Comment by amrbashir** [comment]
I guess it is fine to provide `chid.kill_all()` or something but default behvaior of `kill` shouldn't kill subprocesses

**Comment by amrbashir** [comment]
@lukasbach please open another issue for that
