### ISSUE TITLE
[feat] Support ARM64 Windows

### ISSUE THREAD

**Issue by be5invis** [tauri-apps/tauri#4968]
### Describe the problem

It looks like that Tauri doesn't have ARM64 Windows support, while [Electron has that](https://www.electronjs.org/zh/docs/latest/tutorial/windows-arm). VSCode is one of the famous examples of Electron applications that supports ARM64 Windows.

### Describe the solution you'd like

Add support for ARM64 Windows (Rust triplet being `aarch64-pc-windows-msvc`).

May need cross-compilation support.

**Comment by FabianLars** [comment]
Unless you add specific rust crates that can't be compiled to arm, you can compile tauri apps to aarch64 just fine. I'll try to add docs for it soon, but for now i'll add the instructions here.
Oh and building _on_ arm is a little tricky because our cli can't be compiled to aarch64 currently (because we do use aforementioned crates in it - `ring`).

0. Compiling Tauri apps for Windows currently only works on Windows (no cross-compilation from Linux etc). Also we only officially support the msvc rust toolchain, which is also the only one i used to test building for arm.
1. Open the Visual Studio Installer, click on "Individual Components" and install the arm64 build tools - As of today the exact name in the english client is `MSVC v143 - VS 2022 C++ ARM64 build tools (Latest)` (may differ if you still use VS2019).
2. Add the rust toolchain via `rustup toolchain add aarch64-pc-windows-msvc`
3. Build the tauri app `npm run tauri build -- --target aarch64-pc-windows-msvc` (yarn and pnpm don't need the extra `--`).
4. You'll find the app in `<src-tauri>/target/release/aarch64-pc-windows-msvc/`

Note that if you're using `tauri-action` (our official github action) then it won't be able to upload the compiled app, as it currently don't support non-default targets, see <https://github.com/tauri-apps/tauri-action/issues/243> (i'll get to it soon ™️)
