### ISSUE TITLE
[bug] Block main ui when excute long task

### ISSUE THREAD

**Issue by anhduca4** [tauri-apps/tauri#4996]
### Describe the bug

backend
```
#[command]
pub fn save_user(argument: UserInfo<'_>, port: State<'_, DatabasePort>) {

  
  println!("insert_result {:?}", port.0);
  thread::sleep(time::Duration::from_secs(30));
}
```
Front end
```
invoke('save_user', { argument: data})
```
When I run this command The UI will block and not reponse.

### Expected behavior

Can action in UI

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.54
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 8.15.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by anhduca4** [comment]
After I used 
```
  let port_db = port.0;
  tauri::async_runtime::spawn(async move {
    thread::sleep(time::Duration::from_secs(30));
    println!("insert_result {:?}", port_db );
  });
```
It work :D.

**Comment by JonasKruckenberg** [comment]
Yes indeed. This is not a bug, it's a fact of nature. In single threaded environments a thread can only execute on thing at a time, execution long-running code on that main thread will block all other logic from running, making the UI "unresponsive".

The solution to this is either A) spawning another OS thread to execute your code on, or
B) using rusts light-weight concurrency model know as async Rust or tasks.

Tasks are usually handled by a thread pool, giving you the same benefits as full-blown OS threads with a smaller footprint. So calling `tauri::async_runtime::spawn` was the correct choice because it creates a Task that in-turn will be executed in that thread pool I mentioned. But changing your function signature to `async fn` instead of `fn` does the same thing.

**Comment by anhduca4** [comment]
@JonasKruckenberg  When I change to `pub async fn save_user(argument: UserInfo<'_>, port: State<'_, DatabasePort>) {` 
It will show error:
```
error[E0597]: `__tauri_message__` does not live long enough
  --> src\commands.rs:54:1
   |
54 |   #[command]
   |   ^^^^^^^^^-
   |   |        |
   |   |        `__tauri_message__` dropped here while still borrowed
   |   borrowed value does not live long enough
   |   argument requires that `__tauri_message__` is borrowed for `'static`
```

**Comment by anhduca4** [comment]
@JonasKruckenberg Thank for suport I used `pub async fn save_user(argument: Option<UserInfo<'_>>, port: State<'_, DatabasePort>) {` and now it work.
