### ISSUE TITLE
[feat] About Source Code Protection

### ISSUE THREAD

**Issue by liesauer** [tauri-apps/tauri#5064]
### Describe the problem

it looks like there are lots of embedded html files, are those the project source codes or?
and i found that the rust side source code file name are exposed, how can we remove them?

![image](https://user-images.githubusercontent.com/8676741/187025008-2ab6ebf8-f368-4b10-9cdc-6ef176f64bb4.png)

![image](https://user-images.githubusercontent.com/8676741/187025052-4382ac0e-deab-4e0b-ac63-61198838395d.png)

### Describe the solution you'd like

i have few questions want to know
1. how does tauri embed the source codes? just embed them as what they are or with some encryption?
2. how does tauri load the resources at runtime? extract them to temp directory and then load them or in memory reading?
3. can we config that do not generate those sensitive infomation into executable binary?

**Comment by JonasKruckenberg** [comment]
> i found that the rust side source code file name are exposed, how can we remove them?

Those are debug symbols, useful when running a debugger on your app or for helpful stack traces when it crashes. You can however (and this is generally recommended anyway) strip those debug symbols. See [this guide](https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary) for details on that.

> 1. how does tauri embed the source codes? just embed them as what they are or with some encryption?

When building in release mode, Tauri will read the files in your `distDir` compress them using `brotli` and *inline* them into the binary as you have seen. Encryption doesn't really make sense in this context, because you would still need to store the decryption key somewhere. Likely in the final binary, in which case you have gained no security whatsoever.

> 2. how does tauri load the resources at runtime? extract them to temp directory and then load them or in memory reading?

Since all your assets are basically `&'static [u8]` references, we store them in a map that relates file paths to references and decompress the content when requested. Your web assets will never touch the file system, that's one of the core security benefits of Tauri.

If you're concerned about protecting the web assets in some way, you should minify and obfuscate them before writing them to disk, all modern bundler have support/plugins for this.

**Comment by erikpa1** [comment]
Not sure why you want to protect html code,.... no code when it in customer PC is protected, it is only very hard (not impossible) to decompile. 

EA (or some other games company, dont remember,....) invested a few millions to anti piracy software, bitches got broken in 3 months,....

**Comment by liesauer** [comment]
i see, pretty detail.
