### ISSUE TITLE
[bug] `menuOnLeftClick` isn't working on Ubuntu

### ISSUE THREAD

**Issue by seahindeniz** [tauri-apps/tauri#5089]
### Describe the bug

I'm successfully able to use the `menuOnLeftClick` config on macOS and Windows but after trying it on Ubuntu, I have noticed that the left click was still making system tray menu to open. 
Basically, I have an app which only opens when user clicks on the tray icon and not being able to open the window, totally breaks the flow.

### Reproduction

https://github.com/seahindeniz/tauri-left-click-menu-issue

### Expected behavior

To make it work like on macOS and Windows

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 104.0.1293.70
  › MSVC: 
      - Visual Studio Build Tools 2022
      - Visual Studio Build Tools 2017
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: 6.16.1
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by FabianLars** [comment]
See https://docs.rs/tauri/latest/tauri/enum.SystemTrayEvent.html#variant.LeftClick
![grafik](https://user-images.githubusercontent.com/30730186/187255411-fd973534-16d8-404c-b9e7-c8c70b220f57.png)

It's because of platform limitations, or actually, limitations of the system tray api/library, not linux per se. Nothing we can really do here :(

**Comment by seahindeniz** [comment]
:( shoot
