### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by lhlovecoding** [tauri-apps/tauri#5097]
如何调用win的定时任务来实现一些定时计划？

**Comment by FabianLars** [comment]
For a solution in rust you can take a look at https://github.com/j-hc/windows-taskscheduler-api-rust and https://crates.io/crates/planif

For a WiX (which created the `.msi`) you can take a look at https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/templates/main.wxs#L283-L305 or ask google something like `wix create scheduled task` or whatever.
As you can see we use powershell in the example i linked, which you could also use if you _need_ a javascript "solution" (not really a js _solution_ because you need to write a powershell script, but you get the idea).
