### ISSUE TITLE
Cannot access "events.EventEmitter" in client code[bug] 

### ISSUE THREAD

**Issue by dudunato** [tauri-apps/tauri#5134]
### Describe the bug

Hey there!

I'm using a library that instantiate an node EventEmitter in its core and it seems that Tauri doesn't allow that. Would there be any workaround?

![CleanShot 2022-09-04 at 16 15 13](https://user-images.githubusercontent.com/4641846/188329878-a33e429f-a663-491d-98f6-dd9335e62635.png)

Thanks appreciate any insight on this.

### Platform and versions

yarn tauri info
yarn run v1.22.19
$ tauri info

Environment
  › OS: Mac OS 12.5.0 X64
  › Node.js: 18.4.0
  › npm: 8.12.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

### Stack trace

```shell
Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code

[Error] Error: Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code.
	get (jsforce.js:15:141)
	node_modules/jsforce/lib/core.js (jsforce.js:60988)
	__require2 (chunk-S5KM4IGW.js:18)
	node_modules/jsforce/lib/browser/jsforce.js (jsforce.js:65226)
	__require2 (chunk-S5KM4IGW.js:18)
	Module Code (jsforce.js:65234)
	evaluate
	moduleEvaluation
	moduleEvaluation
	moduleEvaluation
	moduleEvaluation
	(anonymous function)
	promiseReactionJob
```

**Comment by FabianLars** [comment]
There is no nodejs runtime in tauri apps, so the only "workarounds" are a) don't use packages that need a nodejs runtime _at runtime_ or b) bundle a nodejs runtime with your app https://tauri.app/v1/guides/building/sidecar/.

Maybe in this special case there are other workarounds as reported here for example https://github.com/vitejs/vite/issues/9238

Anyway, since this is a problem with these libraries and/or the frontend bundler, i'm going to close this issue.
