### ISSUE TITLE
[bug] PermissionDenied when using Sidecar in MacOS

### ISSUE THREAD

**Issue by data987** [tauri-apps/tauri#5149]
### Describe the bug

I want to use a `python` file as a sidecar but I'm getting this on `dev` and It doesn't work on `build` version, I already removed the files and put it again and It didn't work.

![Screen Shot 2022-09-06 at 7 20 18 PM](https://user-images.githubusercontent.com/8518699/188762012-d329c183-9194-4c55-a399-2769134c3c4a.png)

### tauri.conf.json

```rust
"allowlist": {
      "all": true,
      "shell": {
        "all": false,
        "execute": true,
        "open": false,
        "sidecar": true,
        "scope": [
          {
            "name": "binaries/python-app",
            "sidecar": true
          }
        ]
      }
    },
    "bundle": {
      "active": true,
      "externalBin": [
        "binaries/python-app"
      ],
```
### Binaires

![Screen Shot 2022-09-06 at 7 23 10 PM](https://user-images.githubusercontent.com/8518699/188762247-1d2aab59-1d89-4b0d-8660-a3717d7fd17c.png)

### View

```js
 onClick={async () => {
          const command = Command.sidecar('binaries/python-app');
          const output = await command.execute();
          setActual(output);
        }}
```

### Terminal

```terminal
Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 18.1.0
  › npm: 8.8.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ build
  ├─ .git
  └─ src
```

**Comment by amrbashir** [comment]
try this instead 
```js
const command = Command.sidecar('python-app');
```

**Comment by data987** [comment]
No, It didn't work and  the console threw me this message

![Screen Shot 2022-09-07 at 11 04 53 AM](https://user-images.githubusercontent.com/8518699/188926653-7b38a4e2-c343-4277-b2a1-9cf05736e96b.png)

and I changed this:

```js
const command = Command.sidecar('python-app');
```
And after that I changed this:

```json
{
            "name": "python-app",
            "sidecar": true
          }
```

and I pull out the files outside the `binaries` folder and I received the first message `Permission denied`

**Comment by amrbashir** [comment]
I think this because you are adding only a python script which is just a text file not an executable. you need to either add the python binary itself or if you want to depend on your users having python pre-installed, then just add your python scripts in your tauri.conf.json `resources` and use a normal `Command`

**Comment by FabianLars** [comment]
Take a look at pyinstaller or pyoxidizer to create a portable executable from your python project.

**Comment by data987** [comment]
Where can I save the resources? I want to use it but I'm receiving this bug now

![Screen Shot 2022-09-07 at 3 13 43 PM](https://user-images.githubusercontent.com/8518699/188968679-560c62b4-b22d-4945-8a18-5fede7f4758d.png)

### Folders

![Screen Shot 2022-09-07 at 3 14 08 PM](https://user-images.githubusercontent.com/8518699/188968722-64fc826c-657d-4df9-a925-03afcd144aed.png)

### tauri.conf.json

```json
{
  "name": "python-app",
  "cmd": "python python-app.py"
 },
....
"resources": [
        "resources"
      ],
```

### Command in react

```js
const output = await new Command('python-app').execute();
setActual(output);
```

**Comment by FabianLars** [comment]
I'll try to explain it from scratch.

With tauri you have 2 ways of bundling additional files, the `sidecar` feature for bundling executables (binaries) and `resources` to bundle basically everything else.

`.py` files are text files, nothing more, so bundling these is a) only possible with `resources` and b) requires the end-user system to have python installed. In this you wouldn't execute your script directly but the user's python installation with your script as an input argument (similar to how you execute it in the terminal)

To bundle python projects with the sidecar feature you must first convert these python project to a single-file executable, for example via pyinstaller (the standard) or pyoxidizer (the new fancy thing). Then you can take this generated binary and bundle it inside your tauri app by following our sidecar guide (basically what you already did but using the binary instead of a `.py` file)
