### ISSUE TITLE
[bug] running tauri dev crash at compiling with no errors on Mac

### ISSUE THREAD

**Issue by jxy202** [tauri-apps/tauri#5150]
### Describe the bug

Running tauri dev randomly crash with no errors at building the following packages:

   Compiling cc v1.0.73
   Compiling xml-rs v0.8.4
   Compiling regex-syntax v0.6.27
   Compiling minisign-verify v0.1.8
   Compiling http v0.2.8
   Compiling syn v1.0.99
   Compiling time v0.3.14
   Compiling tokio v1.21.0

I am not so sure which dependency causes the error.

### Platform and versions

Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.0.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.0-beta.8,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.5.2,
  › wry [RUST]: 0.12.2,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ build
  └─ src

### Stack trace

```shell
Here's the verbose output:

https://pastebin.pl/view/5dffcd9e
```

**Comment by shenghan97** [comment]
I just realized I posted using the wrong account. Now I am posting from my usual account!

**Comment by JonasKruckenberg** [comment]
Do you have a way to test this out on a stable macOS version, through a VM maybe?

The verbose output is also not very enlightening 🤔

**Comment by shenghan97** [comment]
Hi

I just tested it in a virtual machine of using a stable version and the problem still exists. But in the virtual machine, it is stuck at a slightly different set of dependencies:

 Compiling cc v1.0.73
   Compiling glob v0.3.0
   Compiling crc32fast v1.3.2
   Compiling crossbeam-utils v0.8.11
   Compiling block v0.1.6
   Compiling futures-core v0.3.24
   Compiling adler v1.0.2
   Compiling adler32 v1.2.0
   Compiling bytes v1.2.1
   Compiling lazy_static v1.4.0
   Compiling cty v0.2.2
   Compiling futures-channel v0.3.24
   Compiling pkg-config v0.3.25

**Comment by shenghan97** [comment]
I've done some digging and finally found the problem: **all i need to delete the `target` directory in `src-tauri`.**

And this issue is quite weird. It's not a permission issue - I checked before and it was all good. I assume it's some weird issue in the building process. I have to delete the **entire** directory otherwise it wouldn't work at all - for example, emptying the contents of the `target` directory won't work, renaming the contents in the directory won't work I have to delete the directory itself and let the tauri CLI to generate a fresh output, even manually creating a brand new `target` folder wouldn't work.

 I assume it has something to do with the hidden files in the directory like .rustc_info.json and CACHEDIR.TAG. But I'm not sure where the problem is.

**Comment by shenghan97** [comment]
I've done more research and it turned out the cause of the issue is **git**. 

I was being lazy and wanted to include the binary build in the repository itself so I made changes to .gitingnore to include the bundles files. Once i remove the rules i used in git ignore it was all fine. But I'm still not sure why adding exclusion rules to gitignore will crash the building process. Here's my gitignore:
```
# Generated by Cargo
# will have compiled files and executables
!target/

target/*
!target/release/

target/release/*
!target/release/bundle/

target/release/bundle/*/*/
!target/release/bundle/*.msi
!target/release/bundle/*.zip

WixTools

```

**Comment by lucasfernog** [comment]
`tauri dev` runs a watcher that uses the gitignore rules to check which files it shouldn't be watching. When you change the gitignore to include files in the target folder, you mess with the watcher (which has an issue in the 1.0.5 release, it can exit without restarting the build command). If you really want to save the build artifacts in the repo (which is not really a good idea, it'll bloat your repo over time), then either disable the watcher (will be available in the next release) or move the bundled files to a separate folder, outside of target/

**Comment by shenghan97** [comment]
Good to know! Thank you. Do you think that it's worth print some Command line message when that happens? Is it in the newer version already?
