### ISSUE TITLE
How to implement another Backend Service (like C#/ .NET)

### ISSUE THREAD

**Issue by sharpSteff** [tauri-apps/tauri#5174]
I'm curious, if there is any documentation what exactly has to be done to implement and use a Backend-service instead of the existing Rust-Backend (e.g. a C#/.NET)

**Comment by FabianLars** [comment]
> instead of the existing Rust-Backend

I'm not sure that's what you meant, but just in case: You can't ever get rid of the rust backend/core since that's the "heart" of every tauri app.
Bindings to other languages are on our roadmap, but won't be worked on any time soon tbh.

So the only thing left is our sidecar feature: <https://tauri.app/v1/guides/building/sidecar/> where you basically create a separate app and communicate via stdio (default), tcp, http, ws, sockets/named pipes, or whatever else you can think of. Apart from that doc page there is also a nodejs repo example linked at the bottom, and python is quite popular so maybe there are some community resources for that, but i didn't really hear anything specific about C#/.net so far, so you're a little on your own for the C# part, but as long as you can compile it to a single file binary you should be good to go.

Feel free to ask further questions here or on discord along the way if you have encounter any problems :v:

**Comment by sharpSteff** [comment]
I refer to this statement on:
https://tauri.app/about/intro/

_ Today, Tauri uses Rust for the backend - but in the not too distant future, other backends like Go, Nim, Python, Csharp, etc. will be possible. _

I don't know exactly, what the article means with "backend", but it sounds like your "binding"

However my goal would have been to create some kind of api to register commands, add menus, etc.

**Comment by FabianLars** [comment]
> I don't know exactly, what the article means with "backend", but it sounds like your "binding"

Correct.

> However my goal would have been to create some kind of api to register commands, add menus, etc.

This needs these "bindings", so my above answer is still correct.

Edit: If by any chance you only care about Windows, then C# WebView2 support is quite good, but without a C# Tauri alternative it will be a little more low-level.

**Comment by sharpSteff** [comment]
@FabianLars Thanks for your answer. 
We are targeting Windows and Linux. However since M$ does not provide support for Linux on their new Ui-Framework .NET MAUI, I'm looking for different solutions. Maybe the Sidecar-Feature would help here.

**Comment by inson1** [comment]
https://github.com/tauri-apps/tauri/issues/4670
