### ISSUE TITLE
[feat]  allow requiring js/css files from within the filesystem

### ISSUE THREAD

**Issue by Nowaaru** [tauri-apps/tauri#5190]
### Describe the problem

When I am making a TypeScript app, by default it is made as a shell with zero bloat; the app does nothing unless you take time to personalize it. In Electron, this is very easy as I'm allowed to require any file in the filesystem and put the results into some storage interface. In Tauri, however, there is no way to access any form of file in the filesystem. This turns modular applications into something that is very rough to implement without hacks.

### Describe the solution you'd like

I would like to be able to require any file within the application's data folder / same folder that the executable is in. If this is not enough, then maybe a feature with scopes in tauri.conf.json.

### Alternatives considered

One: Reading it from the file system and creating a <script> element with the data.

This is an okay solution, but this is bad for abstraction and it's not very neat. Plus, if we were to use this and only wanted one module to be present at one given time / for one page, solving this problem would prove to be difficult.

**Comment by nothingismagick** [comment]
I am trying to understand what you are really after. Correct me if I am wrong, but what you are trying to do is create a kind of app that you can ship to people and they can modify at runtime with any kind of code that they have sitting around on their operating system? Generally speaking, when people make a Tauri application, they ship the CSS / JS with the app, or in some cases consume it from a remote server, so it seems you are requesting something that we never intended.

> In Electron, this is very easy as I'm allowed to require any file in the filesystem

If true, this is a vulnerability as a service, and not something we are likely to ever introduce into core. Would love to see some documentation about this technique though.

> In Tauri, however, there is no way to access any form of file in the filesystem

This is untrue, you can acquire e.g. read/write permissions by using this interface: https://tauri.app/v1/api/js/fs/#FileEntry / or even look into the fs-extra: https://github.com/tauri-apps/tauri-plugin-fs-extra

I think what you mean, however, is a method by which you can `import` / `require` a file and eval it in the webview. Should be pretty trivial to make with our plugin system, since the webviews support up to ES2020, but for the reasons stated above we will probably never introduce such a feature in core, as this is very much an edge case and a blatant security concern.

That all said, will wait for your response before closing this issue.

**Comment by nothingismagick** [comment]
Is this about your comment regarding the customizing the Suwariyomi you built with Electron and are [now rebuilding with Tauri](https://github.com/Nowaaru/suwariyomi.rs):

```
This isn't likely. The majority of Suwariyomi's troubles came from attempting to implement user customization. If I program with these concerns in mind, maybe we can afford these.
```

Then I would recommend thinking about a different architecture. This sure looks like the kind of "all I have is a hammer" approach, where I would usually recommend stepping back, looking deeply at the functionality you want, investigating other options (like dynamic CSS for example, or WASM based themepacks, that can indeed be loaded at runtime, thanks to the pioneering work undertaken by @probablykasper )

**Comment by probablykasper** [comment]
(pretty sure I didn't do any of that)

It sounds like the goal is to import arbitrary JavaScript files. I can imagine it being useful for having user-installable extensions (For example Raycast lets you download extensions written in React). In Electron I believe you can create a custom protocol and then load it like `<script src="protocol:file" />`

**Comment by Nowaaru** [comment]
> If true, this is a vulnerability as a service, and not something we are likely to ever introduce into core.

Yes, I'm aware of this. This is why I said it should require scopes or required files must reside within the app's config or installation directory, this should allow the developer to have control over what files can be required. 

> This is untrue, you can acquire e.g. read/write permissions by using this interface

My apologies, I worded this very badly. I meant via `require` and `import` and I am aware of the available functions to do so.

> Is this about your comment regarding the customizing the Suwariyomi you built with Electron and are [now rebuilding with Tauri](https://github.com/Nowaaru/suwariyomi.rs):

Yes, it is. The problem doesn't lie inside of requiring CSS (but would be a nice addition), but requiring JS. 

I determined that it would be better to have the user download handlers through an interface within the app and extracted to the app's /sources folder and requiring the "main.js" files within each source folder upon application startup. This reduces potential performance concerns and stops users from being bogged-down by opt-out handler downloads and gives the user more freedom between creating their own handlers or downloading from the repository - this was what the modularity was referring to.

**Comment by amrbashir** [comment]
you can use https://docs.rs/tauri/1.0.5/tauri/struct.Builder.html#method.register_uri_scheme_protocol to register a custom protocol handler and manage how you want to load that, because we probably will never provide this feature out of the box.

here is an [example](https://github.com/tauri-apps/tauri/blob/dev/examples/streaming/main.rs#L42) of a custom-protocol for streaming but the general idea is to parse 
the url, remove the custom-protocol bit of it, then you get the path portion of the url where you can use to load your assets/js/css/html.

in your frontend you will need to use async import like this:
```js
import { convertFileSrc } from "@tauri-apps/api/tauri"
const customModule = await import(convertFileSrc("path/to/your/custom/module", "<use-your-cusomt-protocol-here>"))
```

note that you will need to introduce your own scope mechanism.

If you want more help, please hop into our discord where we and the community can help you.
