### ISSUE TITLE
[feat] Introduce a appDataDir path

### ISSUE THREAD

**Issue by danrot** [tauri-apps/tauri#5263]
### Describe the problem

I am building an application using Tauri in which I would like to store some data in a file on the hard drive, so I was looking into the `fs` module. For available paths I have found [this documentation](https://tauri.app/v1/api/js/path/). I feel like the correct path for storing my data on a linux system would be the `dataDir` path. However, this path only contains the path to the folder, without a folder for the application itself as in `appDir`, therefore I have to handle that on my own, which is a tedious task. Additionally I think that this is so common, that it would warrant another path preset.

### Describe the solution you'd like

I would like to be able to use something like `BaseDirectory.AppData`, that stores data in a folder for my own application within `dataDir`.

### Alternatives considered

No alternatives other than leaving it the way it is and handle that in the application itself come to my mind.

**Comment by caesar** [comment]
It would be worth considering a cohesive scheme for all the different app-specific directories - for example, config, data, cache, and probably others.

I would suggest:
- `appConfigDir` (`appDir` would need to be kept as an alias for now to avoid a breaking change)
- `appDataDir`
- `appCacheDir`
- I can't think of any others but maybe there are more?

Personally I think the current `appDir` is confusingly named anyway because I would expect it to point to the directory where the actual app is located, rather than to a config dir.

**Comment by amrbashir** [comment]
I agree current `appDir` is misleading and as long as we don't introduce a breaking change, this could be a good addition in v1.2. However I think we could just introduce `appConfigDir` as a separate function without aliasing so it could have a documentation and would include `@since` tag

**Comment by caesar** [comment]
`logDir` is another one that could be renamed to `appLogDir` to fit with the rest

**Comment by danrot** [comment]
Wow, that was fast! Thank you, everybody!
