### ISSUE TITLE
Next.JS api is not working after build.

### ISSUE THREAD

**Issue by unripper** [tauri-apps/tauri#5324]
Next JS API (`/pages/api`) is working on development, but its not working after building the application.

**Comment by FabianLars** [comment]
Nextjs uses SSR (server side rendering) by default which doesn't work in Tauri because there is no nodejs runtime. Only next's SSG  mode (`next export`) works in Tauri apps without embedding an external server.
And nextjs' `api` feature doesn't work with SSG, see https://nextjs.org/docs/api-routes/introduction#caveats
