### ISSUE TITLE
[feat] Silent print API

### ISSUE THREAD

**Issue by ibalaji777** [tauri-apps/tauri#5330]
### Describe the problem

Window.print()  alternative 

### Describe the solution you'd like

More printer options 
Margin and size no of copies

### Alternatives considered

Window. Print()

### Additional context

Native printer option margin and size select specific printer

**Comment by amrbashir** [comment]
What OS are you using?

**Comment by ibalaji777** [comment]
Windows 10 os

**Comment by amrbashir** [comment]
I am not sure what you want exactly because the issue title says something but the body says another. Anyways `window.print()` provides options to choose margins, number of copies, size...etc

![image](https://user-images.githubusercontent.com/48618675/194547437-c27bb3c7-7607-48e0-bdc3-023dfbbf8d4b.png)

**Comment by ibalaji777** [comment]
Actually I don't want dialog for every time i print

**Comment by moom-en** [comment]
This is a great idea. Most printing needs to be done silently

**Comment by ong-yy** [comment]
Hi, can I give this a try?

**Comment by amrbashir** [comment]
@Ian-Yy yeah sure, thanks!

**Comment by ibalaji777** [comment]
Any solution?

**Comment by ong-yy** [comment]
Hi, sorry for taking so long. I was working on this in Linux at first but found out I can't cross build it to Windows and took more time setting the project up in Windows. 

After checking things through, I found out that `print` function is calling an API in the `wry` lib which further just execute the following `window.print()` as JS in Microsoft Edge WebView2 as shown [here](https://github.com/tauri-apps/wry/blob/c7cd108c2e764457105920d191cf82e890d465d1/src/webview/webview2/mod.rs#L771). Furthermore, I found that the Microsoft WebView2 is implementing a native way of printing as well [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1331) with silent print supported on experimental now.

So, I am not so sure too where to fix this. Perhaps, a PR is required on the `wry` side to implement the experimental print function first?

**Comment by FabianLars** [comment]
I can't answer your question. But one thing to that part:
> So, I am not so sure too where to fix this. Perhaps, a PR is required on the wry side to implement the experimental print function first?

We can't use experimental apis in wry. webview2-com doesn't support it _and_ users would have to install non-stable webview2 runtimes (and manually set the runtime path). Edit: "non-stable runtime" means a non-stable (like canary) release of _Edge_ afaik

**Comment by nothingismagick** [comment]
But maybe @wravery has an idea here how we could fast-track this...

**Comment by wravery** [comment]
I think @FabianLars summed it up pretty well, it's best to wait for the API to be promoted to stable.

There is a small distinction between the WebView2 SDK and the runtime that's installed, they can be updated independently. Typically, the runtime self-updates, and as long as it's new enough it'll support all of the features in the pre-release SDK. If you don't mind using experimental status APIs, you can usually just update the SDK to unlock them earlier.

In this case, that would mean updating the webview2-com crate and wry, but probably hanging back on the windows-rs versions because of the MSRV requirements in the latest version of those crates. The dependencies would get pretty complicated if we wanted to update just the WebView2 SDK version and expose the experimental APIs.

**Comment by amrbashir** [comment]
closing in favor of #4917

**Comment by ihekui** [comment]
I am looking forward to the silent printing API, because my app needs this API to print small tickets and price tags

**Comment by dev-itzarun** [comment]
@ihekui , @ibalaji777  Have anyone found the solution for this?

**Comment by alimehasin** [comment]
>I found that the Microsoft WebView2 is implementing a native way of printing as well https://github.com/MicrosoftEdge/WebView2Feedback/issues/1331 with silent print supported on experimental now.

Well, this is now stable

**Comment by noearaujo** [comment]
I'm creating an order management system, but until everything stabilizes... I'll continue using electron.

**Comment by dnguyenfs** [comment]
Hi Guys, hope you doing well,  any update on this?

**Comment by dev-itzarun** [comment]
Actually I badly need this , but seems there is no solution till now 😞...

**Comment by dev-itzarun** [comment]
Can we use this Rust libs with js ? 

1. https://crates.io/crates/escpos

2. https://crates.io/crates/recibo

I Dont much knowledge in RUST

**Comment by dev-itzarun** [comment]
Any update on this ?
