### ISSUE TITLE
[feat] Access a session when creating a new WebviewWindow

### ISSUE THREAD

**Issue by myhrmans** [tauri-apps/tauri#5356]
### Describe the problem

Hi there, 

is there a possibility to inject a session into the WebviewWindow when creating it similar to how its done in [Electron Session](https://www.electronjs.org/de/docs/latest/api/session#class-session) when creating a new [BrowserWindow](https://www.electronjs.org/de/docs/latest/api/browser-window)? 

Looking for this feature since I need to handle multiple accounts on the same address within the application. 

### Describe the solution you'd like

As an option to WebviewWindow add a session

**Comment by myhrmans** [comment]
Cant the data_directory be used when creating a webview to create a seperate session from another webview? https://docs.rs/tauri/1.1.1/tauri/struct.WebviewAttributes.html#structfield.data_directory

Seems to be missing in the @tauri-apps/api atleast.

**Comment by amrbashir** [comment]
I think exposing `data_directory` option to JS is not secure since it could potentially allow readding data of other webview windows. I will close this for now but I will cc @tauri-apps/wg-security and will re-open if they approve it is fine to add.

For your use-case, you can create the window from Rust and use the `data_directory` option there.
