### ISSUE TITLE
[feat] Layout like microsoft edge browser

### ISSUE THREAD

**Issue by moom-en** [tauri-apps/tauri#5384]
### Describe the problem

tauri window layout like microsoft edge browser(top tab、left or right menu、main window),
In this way, there is only one menu, and it is also convenient to switch between different windows

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/35919845/195007182-67aa9002-b258-4769-93f0-c145742a8a56.png)

**Comment by simonhyll** [comment]
That sort of thing isn't really something the Tauri project aims to do (currently). I'm not gonna go so far as to say there's no interest to expand the project with more features like this, but it's unlikely to be something you'll see anyone make for a long time to come, especially since it's not something that's easy to add cross platform.

The way to do what you want, currently and for the next at least several years, is to create such tabs and menus yourself in an undecorated window. Done right you won't notice much difference from native menus and faked ones inside the webview.
