### ISSUE TITLE
[bug] Front end data disappears

### ISSUE THREAD

**Issue by rs0d** [tauri-apps/tauri#5395]
### Describe the bug

![1](https://user-images.githubusercontent.com/34772657/195362072-d0500f8a-31f8-446c-8d7d-b46008129428.png)
![2](https://user-images.githubusercontent.com/34772657/195362083-2f5def92-b17f-4b6f-b58f-c307d2aa516b.png)
![3](https://user-images.githubusercontent.com/34772657/195362090-cd7063f1-53a4-4f2c-a2f2-32dce376c400.png)
![4](https://user-images.githubusercontent.com/34772657/195362102-955b8df6-6b98-498d-8922-c66d30d1e697.png)
method Strange disappearance ??   use http_serde::method

### Platform and versions

![5](https://user-images.githubusercontent.com/34772657/195362483-dd850b9b-9498-49cf-ad86-87b4ca4d8c10.png)

**Comment by amrbashir** [comment]
I can't help without you giving us a bit of context and code snippets (not just screenshots).

I am gonna take a guess anyways, the issue is probably with `skip_serializing_if = "is_default"`, `GET` is the default http method and the response screenshot shows that the method is `GET` so serde will skip serializing it since it is the default.
