### ISSUE TITLE
[bug] MacOS Problem accessing video via tauri:// path

### ISSUE THREAD

**Issue by Bukmopbl4** [tauri-apps/tauri#5461]
### Describe the bug

https://user-images.githubusercontent.com/19820469/197306310-0ab1cea5-53d3-4493-a162-5c38406776fa.mp4

I'm trying to open a file index.html with a video tag. Video sample 2.5 mb

`<body><video src="./video/test.mp4" autoplay muted width="640" height="480"></video></body>`

### Platform and versions

gm@0.0.0 tauri
> tauri

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 16.17.1
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .vscode
  └─ src

**Comment by Bukmopbl4** [comment]
through asset path (asset://) works correctly.

**Comment by amrbashir** [comment]
is that video packaged inside the binary, eg exists in the dist dir? if so do you really need it to be package inside the binary?

you should use `asset://` protocol if you need to play a video, because it supports streaming while `tauri://` will just serve the file as whole.

For this type of files (large files especially) it is recommended to embed them as resources see https://tauri.app/v1/guides/building/resources and then use `asset://` if you want to stream them

**Comment by Bukmopbl4** [comment]
yes, I wrote that everything works if I use `asset://`.
