### ISSUE TITLE
Apple blocking Electron apps.. avoid this API

### ISSUE THREAD

**Issue by FractalMatt** [tauri-apps/tauri#552]
Turns out that Apple is blocking many Electron apps because of some restricted APIs that they have been calling for years. To whoever is working on the iOS implementation, please make sure Tauri doesn't call the same functions.

https://9to5mac.com/2019/11/04/electron-app-rejections/

Idk but might also be able to use this to get some developers to pick Tauri.

**Comment by khionu** [comment]
Thank you very much for your concern. It'd be appreciated if you could edit the issue to include specifics.

**Comment by rajivshah3** [comment]
This is particularly relevant for macOS apps that are sent to the Mac App Store instead of being distributed through another channel. It normally occurs when Chromium uses a private API (Google Chrome is not listed in the Mac App Store) and it gets included in Electron without people noticing beforehand. It would be good for Tauri to have a policy of using public macOS APIs whenever possible (unless absolutely necessary)

**Comment by wagnerpv** [comment]
> Thank you very much for your concern. It'd be appreciated if you could edit the issue to include specifics.

Developers are reporting that apps made using Electron are now being rejected by the automated Mac App Store review process.

The apps in question are getting flagged because of their usage of private API calls.

The detected private API symbols include:
- CAContext
- CALayerHost
- NSAccessibilityRemoteUIElement
- NSNextStepFrame
- NSThemeFrame
- NSURLFileTypeMappings

**Comment by rajivshah3** [comment]
Tauri currently uses at least 1 private API (`WKDownloadDelegate`), introduced through `webview-sys`. See https://github.com/Boscop/web-view/blob/076b2f92738cb7101a7be730f56434f2b7e08ac1/webview-sys/webview_cocoa.c#L266-L290

**Comment by nothingismagick** [comment]
That might explain WHY I get this undefined behavior (in the rust console) when I attempt to load in an image in our example app in MacOS:

```
objc[32468]: Class FIFinderSyncExtensionHost is implemented in both 
/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa52ae3d8) and 
/System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10b516f50). 
One of the two will be used. Which one is undefined.
```

**Comment by rajivshah3** [comment]
I think that’s related to something else: https://github.com/sqweek/dialog/issues/24#issuecomment-457574227

**Comment by nothingismagick** [comment]
but this might also be a problematic approach too:
https://bugs.webkit.org/show_bug.cgi?id=208667#c17

**Comment by nothingismagick** [comment]
So I am going to close this issue, I think by now we have all been sensitized to the issue. Thanks again for bringing it up!
