### ISSUE TITLE
[bug] Does line-48 have a bug?

### ISSUE THREAD

**Issue by percy507** [tauri-apps/tauri#5670]
### Describe the bug

> Windows doesn't support custom schemes yet

https://github.com/tauri-apps/tauri/blob/677838ccfadfdf37039be53bfad666bbe1dab8c3/examples/streaming/main.rs#L47-L51

### Platform and versions

None.

**Comment by lucasfernog** [comment]
Not really a bug, though it can be simplified. It does work on Windows.

**Comment by percy507** [comment]
@lucasfernog Thanks for your reply. How do you think of this discussion? https://github.com/tauri-apps/tauri/discussions/5506

**Comment by lucasfernog** [comment]
Fabian is right, the Tauri implementation for custom protocols on Windows uses a "workaround", it's not an actual new scheme but just a custom Web resource request handler, which runs the protocol when a request to `https://$SCHEME.localhost/$PATH` is performed. So that's why the custom protocol URL is different on Windows.

The example code is right because wry converts the `https://$SCHEME.localhost/$PATH` back to `$SCHEME://localhost/$PATH` so you don't need to deal with it in the handler.

**Comment by percy507** [comment]
Thanks. Your answer is very clear.
