### ISSUE TITLE
[docs] Suggestions on front-end api streamlining

### ISSUE THREAD

**Issue by cosoc** [tauri-apps/tauri#5700]
I think the R&D team should focus more on the back end, and should not provide too many apis to the front end. Pages are only presented, and the application developer should have front-end knowledge. Any interaction between the front end and the system and the back end should only be completed through a unified ipc communication The html+js development interface is just a development interface. It can only present data and is only responsible for the logic presentation of the UI. It should not encapsulate the API for background operations such as window creation. I think the front-end API only needs to provide an interface for ipc communication. All other apis are eliminated

**Comment by FabianLars** [comment]
If we were a Rust GUI project, i'd agree, but many (or most) of our users are not familiar with Rust at all and need Tauri's JS APIs to get started with Tauri so removing all the APIs is not an option.
That said it's also not _that_ much work to implement them and keep them working since most JS APIs just expose existing Rust functionality.

**Comment by amrbashir** [comment]
You can disable all APIs using the `allowlist` and it won't be bundled into your application, so you don't nee to use `@tauri-apps/api` package and instead build your own APIs and use `window.__TAURI_INVOKE__` primitive to call them.
