### ISSUE TITLE
[bug] Tauri Path API shows wrong path \\?\

### ISSUE THREAD

**Issue by williamscaramuzzi** [tauri-apps/tauri#5850]
### Describe the bug

I'm trying to do some file manipulation in a simple Desktop App, and I'm stuck. When using File System, everything is OK and I can create a simple text file in my Desktop folder.
But when I try to retrieve the current folder where the .exe is running, the path is shown with this weird characters at the begining: \\?\
![image](https://user-images.githubusercontent.com/22432066/208184229-e6dc7700-a0c3-4fb2-851c-0343490615d5.png)

### Reproduction

1. Download my repository where I put this simple app https://github.com/williamscaramuzzi/tauri-file-attempt
2. I'm using Windows 11 and I installed all the current updates (I did this yesterday)
3. Just execute npm run tauri dev and follow the text on screen.

### Expected behavior

I expected the path to be written as "C:\Users\willi\Desktop\ and so on"

### Platform and versions

![image](https://user-images.githubusercontent.com/22432066/208184786-3bc91bbe-ff67-477d-aa03-cec6ccd9da27.png)

**Comment by FabianLars** [comment]
These are not reallyyy wrong paths. They are indeed valid, and are called UNC paths, the main reason to use them is to allow much larger paths (32k chars instead of 255). Unfortunately it turns out that (too) many libraries don't support them so _imo_ we should look into removing the UNC part :/

**Comment by JohnScience** [comment]
@FabianLars There's a popular [`dunce`](https://crates.io/crates/dunce) library on crates.io, which does precisely that.

**Comment by FabianLars** [comment]
yep, i (we) are aware of that. We just can't change the paths in a 1.X release because it would technically be a breaking change.

**Comment by NaughtyDog6000** [comment]
are there plans to change this for 2.0 or is this remaining as is?

**Comment by FabianLars** [comment]
@NaughtyDog6000 
The change already landed in v2 a while ago but only paths returned from JS apis will be changed. The rust apis will return the paths as-is (like the underlying rust methods do).

**Comment by WSH032** [comment]
This is definitely unfortunate! When I naively passed `PathResolver::resource_dir()` to Python, [I got bitten by Python](https://github.com/pallets/jinja/issues/1675#issuecomment-1323555773).

I think the biggest problem is that the path format returned by `PathResolver` is inconsistent:

- `resource_dir()` returns a UNC path `\\?\E:\xxx`
- `video_dir()` returns a simple path `E:\xxx`

I haven't checked other directories yet, but I suspect that paths returned by `tauri_utils` are UNC paths, while those returned by `dirs` are simple paths.

I believe `PathResolver` should either return a consistent path format or **document which APIs return UNC paths**.

Otherwise, for users who do not look at the implementation code of `PathResolver`, they can only wait to get bitten before coming to this issue. 😥
