### ISSUE TITLE
[docs] tutorial for android/ios app development using tauri

### ISSUE THREAD

**Issue by strasdat** [tauri-apps/tauri#5895]
Yes, we're working on it right now!

_Originally posted by @nothingismagick in https://github.com/tauri-apps/tauri/issues/3884#issuecomment-1345237561_

**Comment by strasdat** [comment]
Can't wait!

**Comment by amrbashir** [comment]
please see https://next--tauri.netlify.app/next/mobile/

**Comment by marrocksd** [comment]
It isn't clear. The tutorial didn't have Environment Setup as well as how to spin up the project. Could you please update if you have time, thanks

**Comment by amrbashir** [comment]
https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/macos#android
https://next--tauri.netlify.app/next/mobile/development/integrate

**Comment by LetrixZ** [comment]
I followed all steps in the new guide but I'm stuck with Vite waiting for the frontend servert at `localhost:1420`. I should try with a vanilla project.
Is there any working project that's also crossplatform desktop and mobile?

**Comment by amrbashir** [comment]
see `examples/api` project in the `next` branch.

**Comment by amrbashir** [comment]
and for vite, make sure to follow this bit too https://next--tauri.netlify.app/next/mobile/development/configuration#vite

**Comment by LetrixZ** [comment]
> and for vite, make sure to follow this bit too https://next--tauri.netlify.app/next/mobile/development/configuration#vite

That is what's giving me that problem but without that it works only on desktop.

**Comment by amrbashir** [comment]
change the port in tauri.conf.json to match the one in the vite config

**Comment by marrocksd** [comment]
https://next--tauri.netlify.app/next/mobile/development/integrate

I'm following all the steps here (MacOS compiles for iOS). Then "tauri dev" still gives me the desktop version, what should I do next? 
After all the configurations, you should tell what people should do next to start the project.

I was trying to put the --target x86_64-apple-ios flag but no luck. It gave me the error
` DYLD_ROOT_PATH not set for simulator program`

I don't think I'm having problem with my env setup because I'm running things normally with flutter. Really wish to switch to Rust so hope you can help

**Comment by amrbashir** [comment]
the commands to start mobile dev env are:
`tauri ios dev` and `tauri android dev`

Also note that mobile is in alpha phase so expect the documentation to be a bit lacking.

**Comment by marrocksd** [comment]
@amrbashir works like a charm. It's the moment that I've been waiting for lol

**Comment by edsky** [comment]
I created a minimal [example](https://github.com/edsky/tauri_yew_ios.git) to use for app development until the docs come out.

**Comment by Ifeanyi55** [comment]
I am trying to open the tutorial links, but I am getting a "Site not found" error in my browser.
