### ISSUE TITLE
[bug] Unhandled Promise Rejection: path not allowed on the configured scope

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri#5907]
### Describe the bug

I tried multiple configurations, but they all failed. Everything works fine in development mode, but once built with tauri-action, the problem occurs.

```json
"fs": {
  "all": true,
  "scope": [
    "$HOME/*",
    "$HOME/.chatgpt/*",
    "$HOME/.chatgpt/cache_mode/*"
  ]
}
```

<img width="492" alt="Screenshot 2022-12-24 at 21 31 46" src="https://user-images.githubusercontent.com/16164244/209438242-c070942f-898c-4288-8246-3e91dc4ef256.png">

### Platform and versions

> chatgpt@0.0.0 tauri
> tauri

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 18.7.0
  › npm: 8.15.0
  › pnpm: 7.18.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-apple-darwin

**Comment by FabianLars** [comment]
I only were able to test in on Windows so far and there were 2 issues i could see. The first one, probably windows-only, was your usage of the `join` function in conjunction with `isRoot == true` because this resulted in a path that looked like this `\C:\Users\...` (notice the additional `\`). This can be fixed by replacing it like the `join` lines in `readJSONOpts` and `writeJSONOpts` with
```ts
let file = path;
if (!isRoot) {
    file = await join(root, path);
}
```
The second one, probably problematic on all platforms is the scope config itself. Try using `**` instead of `*`, so like `"$HOME/.chatgpt/cache_model/**"` (btw there was a typo in `cache_model` here)

**Comment by lencx** [comment]
Thanks, I'll try again.

**Comment by lencx** [comment]
Thanks, it is useful.

```js
let file = path;
if (!isRoot) {
    file = await join(root, path);
}
```
