### ISSUE TITLE
[macos] lottie-react freezes my app in tauri release mode

### ISSUE THREAD

**Issue by CarbonPool** [tauri-apps/tauri#5915]

**Comment by FabianLars** [comment]
Please use the `bug` [issue template](https://github.com/tauri-apps/tauri/issues/new?assignees=&labels=type%3A+bug%2Cstatus%3A+needs+triage&template=bug_report.yml&title=%5Bbug%5D+) and fill out the required information. Also a small reproduction may be appreciated.
(I'll re-open this issue if you copy&paste it in here, otherwise you can open another issue)
