### ISSUE TITLE
[feat] Reduce Source Code Folder Size

### ISSUE THREAD

**Issue by KiddoV** [tauri-apps/tauri#5955]
### Describe the problem

**Disclaimer: I'm new in Tauri and Rust**

The source code folder size is extremely big, ~2GB - ~4GB. That is crazy amount for just an ``hello-world`` app.
I thought ``node_modules`` is the only one that can take that much space!!!

I noticed this folder: ``src-tauri/debug`` is taking the most space.
Is there anyway that we can move this folder out of scope so we can use it for all the Tauri project instead of just one?

### Describe the solution you'd like

Move all the big folders to use globally for every Tauri project.

**Comment by FabianLars** [comment]
These are Rust's build artifacts. You can change the target dir with this config https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir
Note that this also changes tauri's output dir (where it creates the app bundles).

**Comment by JonasKruckenberg** [comment]
Also note that to share build artifacts between projects you can use tools like sccache, but it's out of scope for Tauri

**Comment by j787701730** [comment]
I also think the folder is too big. my used pnpm create tauri-app with vanilla .
2.5GB in the first pnpm tauri dev; 
![image](https://user-images.githubusercontent.com/23625690/210294863-260884b2-5a0a-4308-a5bf-c412e8aff9e3.png);
4GB in the first pnpm tauri build; 
![image](https://user-images.githubusercontent.com/23625690/210295390-2a9a6535-8554-49c2-98a7-d4b506baef1a.png).

this is use pnpm create tauri-app with svelte: 
![image](https://user-images.githubusercontent.com/23625690/210296729-b34f3d9f-cfe1-4b0e-adf0-1ac32b7b24fd.png)

**Comment by j787701730** [comment]
I also think the folder is too big; 
First run in  pnpm tauri dev and pnpm tauri build.
![image](https://user-images.githubusercontent.com/23625690/210298311-b6a32bec-d7d3-456d-8e52-9a1c2a2356ab.png)

**Comment by FabianLars** [comment]
> I also think the folder is too big;

There really is not much we can do, other than maybe reducing our dependencies, i don't know. This is really a Rust "issue" not a Tauri issue :/

> First run in pnpm tauri dev and pnpm tauri build = 5GB

tauri dev and tauri build do not share build artifacts since they translate to `cargo build` and `cargo build --release` so you end up with twice the build artifacts.

**Comment by KiddoV** [comment]
I think we need an ``official detailed guide`` for this issue to reduce source folder size.

**Comment by nothingismagick** [comment]
This is a situation common to many rust projects and "Not something Tauri can do anything about. :tm:". Something I have personally used in the past is this:

https://github.com/holmgr/cargo-sweep

But a headsup in the docs is a good idea @KiddoV

**Comment by FabianLars** [comment]
I'm not sure what we should add to the docs for this specific scenario. We're not talking about old/leftover build artifacts, but the ones from a fresh build. For this specifically the only thing we can add is a warning that users should expect a ~2GB target folder (or 4-5 if debug _and_ release builds are present)

If you guys mean we should add tips about keeping it at ~2gb then sure, we can add a note about cargo-sweep and `cargo clean`, and that it should be run once in a while and especially after each new Rust release.
-> Where should that go in the docs? In the `Development` category?

Edit: Oh and ~~sccache +~~ shared target dirs too right?
Edit2: Actually sccache may be counter-productive since it stores even more build artifacts...
