### ISSUE TITLE
[feat] Webkit2GTK4.1

### ISSUE THREAD

**Issue by mrquantumoff** [tauri-apps/tauri#6151]
### Describe the problem

Webkit2GTK 4.0 is deprecated, and most of gtk crates used in tauri are as well

### Describe the solution you'd like

Update all the gtk-related crates and use webkit2gtk4.1 (webkit2gtk rs 0.19.x)

### Alternatives considered

Do nothing

**Comment by FabianLars** [comment]
Will be part of tauri v2. We can't introduce it in 1.x since it's a _huge_ raise in the minimum supported Linux version. Closing this since all the upstream deps already updated today.

**Comment by jon-chuang** [comment]
@FabianLars I've managed to build Tauri to use webkit2gtk. But it was a pain to install (mainly because of installing `libwebkit2gtk-4.1`). The shared object dependency is 4.4 GB. It will be quite a pain to get users to have this dependency available in order to run WebGL2.

Would you be able to provide any information on when it may be that the stable release of webkit2gtk on Linux may include webgl2 support? (seems like it is actually this month?: https://discourse.gnome.org/t/webkitgtk-for-gtk-4-status-update-and-api-changes/11033)

Alternately, I may be able to work around the issue by running the webGPU version of three.js (seems to be supported here? https://github.com/tauri-apps/tauri/issues/6381). But I don't think this is feasible as we are using webGL APIs at the moment.

**Comment by FabianLars** [comment]
@jon-chuang webkitgtk 4.1 is completely unrelated to webgl2. It should be available in 4.0 too. That said, if you want to use 4.1, use tauri v2, if not stick to v1.

Either way you have to wait for webkitgtk v2.40 no matter if you use 4.0 or 4.1 for webgl2 which indeed should be released in a few weeks.

> Alternately, I may be able to work around the issue by running the webGPU version of three.js (seems to be supported here? https://github.com/tauri-apps/tauri/issues/6381)

That issue showed that it works on windows (only). Pretty sure it doesn't work on macos and linux yet.
