### ISSUE TITLE
[bug] SCSS not properly working with vue/vite

### ISSUE THREAD

**Issue by Phill030** [tauri-apps/tauri#6198]
### Describe the bug

When using SCSS in vue, it won't actual work as a scss file but instead only applies effects like in a css file which means nested classes or elements in scss won't create an actual result.

### Reproduction

1. Create a Tauri + Vue(TS) Project
2. Install following NPM packages: `sass` & `sass-loader`
3. Create a `scss` file and import it with `@import url('./style.scss')` in your App.vue
4. Create 2 elements in App.vue which are nested like:
```html
<div class="obj1">
  <div class="obj2">
  
  </div>
</div>
```
5. Change your `style.scss` to following:
```scss
.obj1 {
  background-color: black;
  .obj2 {
    background-color: white;
  }
}
```
The above code is working with normal Vite and SCSS but in Tauri not. Using two seperate classes not nested, results in the expected behavior. 

### Expected behavior

SCSS should be working as in normal Vite + Vue and result in applying the effects to the components instead of not doing anything.

### Platform and versions

```
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 109.0.1518.70
  › MSVC: 
      - Visual Studio Community 2019
      - Visual Studio Community 2022
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
  ```

### Stack trace

```shell
None
```

**Comment by FabianLars** [comment]
1) sass-loader shouldn't be needed in a vite project
2) if i import it in App.vue like this it works fine for me
```ts
<style lang="scss">
@import './style.scss';
</style>
```
No idea why `url()` doesn't seem to work here.

**Comment by amrbashir** [comment]
This is not a tauri issue, the behavior is the same in normal browser and in tauri.

I am not sure how vite (or vite-vue-plugin) treats `@import url()` but based on looking at the generated `<style>` inside `<head>`, vite (or vite-vue-plugin) doesn't compile your scss if it is imported using `@import url()`. I think this is because with `@import url()`, you maybe importing a file with a relative url (i.e. a public asset, so `@import url('./style.css')` actually wants `https://website.com/style.css`, this is usually a compiled file inside your `public` directory) and vite (or vite-vue-plugin) can't know for sure whether you mean a compiled file or you want to compile it.

Anyways, since the behavior in tauri is the same as the browser, I will close this issue but feel free to open an issue in vite repo if you think this is a bug.
