### ISSUE TITLE
[docs] How to install the CLI + broken link

### ISSUE THREAD

**Issue by strogonoff** [tauri-apps/tauri#6253]
- The docs say:

  > Even though installing the CLI through Cargo is the preferred option, 

  yet there is no steps (for a complete Rust newbie) for actually installing the CLI through Cargo.

  Presumably that’d be `cargo install tauri-cli`—unless globally installing the CLI is discouraged in favour of project-specific install, and thus it’d be `cargo add tauri-cli`?

- There are guides over the Web that link to https://tauri.studio/v1/guides/getting-started/beginning-tutorial#alternatively-install-tauri-cli-as-a-cargo-subcommand, but that page is no longer available. Perhaps a redirect could be added?

**Comment by FabianLars** [comment]
> The docs say: Even though installing the CLI through Cargo is the preferred option,

That should only be on the faq page right? (if not please tell me 😅), in which case it doesn't really need instructions, _imo_ because the instructions are in the actual guides for example, which link to the faq entry in the first place. -> open to discuss this.

> There are guides over the Web that link to https://tauri.studio/v1/guides/getting-started/beginning-tutorial#alternatively-install-tauri-cli-as-a-cargo-subcommand, but that page is no longer available. Perhaps a redirect could be added?

Not even sure anymore what that link was supposed to link to tbh. anyway, the install instructions are in each getting started guide in the `Create the rust project` section: <https://tauri.app/v1/guides/getting-started/setup/vite#create-the-rust-project>.

Thanks for your feedback on this!

**Comment by strogonoff** [comment]
You’re right, it’s in the guides. I did not look through all guides and searching failed me.On 13 Feb 2023, at 4:14 PM, Fabian-Lars ***@***.***> wrote:﻿
Closed #6253 as completed.
