### ISSUE TITLE
CalVer Support

### ISSUE THREAD

**Issue by Firaenix** [tauri-apps/tauri#6267]
Hi,

I was wondering if there's any plans to support [CalVer](https://calver.org/)? Id like to use my own versioning format along the lines of YY.M.DD+Build eg. 23.02.14+1 for the first build on the 14th of Feb 2023.

**Comment by FabianLars** [comment]
i think "official" support for formats that are not semver (or semver compatible) are highly unlikely, _but_ isn't calver basically semver compatible? `23.02.14+1` should be valid semver, and tauri 1.3 will also support the `+1` suffix, at least on Windows.

**Comment by Firaenix** [comment]
Hmm, I was under the impression that +BuildNumber wasn’t working on windows, I’ll give it another shot. Thanks

**Comment by FabianLars** [comment]
just to be safe: i said _will_ be supported in 1.3 (not yet released), it needs this: <https://github.com/tauri-apps/tauri/pull/6096> for the msi target. The new nsis target will support it out of the box with full semver support = non-numeric build and prelease identifiers.

**Comment by Firaenix** [comment]
Ahh ok not a problem, I misread. Alright, looking forward to it.

**Comment by JonasKruckenberg** [comment]
Hey @Firaenix I'm a bit late to the party, but here's a workflow I've been using to have nightly releases with the current version of Tauri (doesn't give you the build tag thing you wanted, but `YY.M.D` definitely works. Note that the format is `YY.M.D` not `YY.MM.DD` since windows doesn't allow leading zeros in the version (i.e. `23.2.19` is fine, but `23.02.19` isn't)
https://github.com/JonasKruckenberg/pisano/blob/main/.github/workflows/release-nightly.yml
