### ISSUE TITLE
[feat] Make `EventHandler` honour RAII

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri#6393]
### Describe the problem

Currently unlistening to an event must be done like this:

```rust
let handler_id: EventHandler = window.listen("foo", |_| {});

window.unlisten(handler_id);
```

which is very javascript-y and doesn't follow Rusts RAII pattern at all. This means that when the `EventHandler` above goes out of scope, it does not clean up after itself (unlisted) and it will also be impossible to unlisten at a later time since the id went out of scope, this effectively leaks event handlers.

This also makes it nearly impossible to use event handlers together with abortable futures, since aborting futures relies heavily on destructors to fully clean up their resources.

### Describe the solution you'd like

Refactor `EventHandler` to hold a reference to the `Window` it was created by so it can expose a simple method:

```rust
impl EventHandler {
   pub fn unlisten(self) {

   }
}
```

as well as implement drop:

```rust
impl Drop for EventHandler {
   pub fn drop(&mut self) {

   }
}
```

**Comment by FabianLars** [comment]
tbh not too much of a fan of the drop implementation because of the amount of rust beginners we have here. you'd have to store all event listeners in tauri::State or something so that they don't get immediately dropped in the setup hook for example.
So i'm not sure if this could potentially cause more harm than good. Definitely something to think about though!
