### ISSUE TITLE
[feat] Support image tags to access through http?

### ISSUE THREAD

**Issue by maoyutofu** [tauri-apps/tauri#6395]
### Describe the problem

Http will be automatically upgraded to https. Make the picture inaccessible.

Automatic upgrade to HTTPS is prohibited.

### Describe the solution you'd like

"security": {
      "key?": false
}

**Comment by maoyutofu** [comment]
I am using tauri 1.2.4, and I can't find a way to disable this option.

**Comment by FabianLars** [comment]
There actually is no way to directly disable this. It's a chromium internal thing.
The only workarounds i know of are 
a) don't serve the frontend over https, see https://github.com/tauri-apps/tauri/issues/3007
b) only "recommended" if we're talking about network-local servers: use some browser flags via https://github.com/tauri-apps/tauri/pull/5799 to tell chromium to treat the http origin as secure like `--unsafely-treat-insecure-origin-as-secure=http://ip123` - note that according to a discord member this stopped working recently.
c) the obvious recommendation (if possible): make the images available over https...

Closing for now since as far as i know this is not something we want to add to Tauri directly at the moment.
