### ISSUE TITLE
[bug] Warn Waiting for your frontend dev server to start on http://localhost:1420/...

### ISSUE THREAD

**Issue by licheng1013** [tauri-apps/tauri#6413]
### Describe the bug

I created the project according to the documentation, but it won't start.
![image](https://user-images.githubusercontent.com/46236080/223615889-7bec6067-d262-4cc2-b81b-e64d47894a54.png)
files:
![image](https://user-images.githubusercontent.com/46236080/223616125-f0afcaa7-0dda-43e5-958a-86c61f223b66.png)
![image](https://user-images.githubusercontent.com/46236080/223616157-ee83dde4-6d88-4827-ad38-72125311f92c.png)
![image](https://user-images.githubusercontent.com/46236080/223616351-dbe3567e-ddc2-4564-be6f-4289721f1b4b.png)

### Platform and versions

```text
> tauri "info"


Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 110.0.1587.63
  › MSVC: 
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.18.2
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ .idea
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by lbnongxiangang** [comment]
@licheng1013  你好，请问这个issue怎么close了？是怎么解决的？刚从Electron转过来，不太熟悉这个，遇到一样的问题，给整懵逼了，感谢。

**Comment by licheng1013** [comment]
> @licheng1013 你好，请问这个issue怎么close了？是怎么解决的？刚从Electron转过来，不太熟悉这个，遇到一样的问题，给整懵逼了，感谢。

我这里是本地的localhost无法正常访问了，所以导致出现的问题。你可以试下用localhost:端口，访问前端项目看是否能正常访问。

**Comment by lbnongxiangang** [comment]
> > @licheng1013 你好，请问这个issue怎么close了？是怎么解决的？刚从Electron转过来，不太熟悉这个，遇到一样的问题，给整懵逼了，感谢。
> 
> 我这里是本地的localhost无法正常访问了，所以导致出现的问题。你可以试下用localhost:端口，访问前端项目看是否能正常访问。

感谢，参考这个项目成功运行了：https://github.com/yooneskh/vite-tauri-template

## Development

There are two ways you can develo your app.

### In Browser
- `yarn serve`
  - launches vite and you can test and develop your app in the browser at http://localhost:8080.

### In Tauri Window

Launch two terminals and in

1- `yarn serve:tauri`

This launches Vite and configures [Unified Network](https://github.com/yooneskh/unified-network) (which is mine) to use Tauri for api calls (to get around CORS problems).

2- `yarn serve:native`

This launches Tauri window and you would see your app in the native window.

**Note:** There are mainly 2 differences between development in browser and in Tauri window.

- One is who executes your http calls, because when in browser, you are subject to CORS rules, but when testing in Tauri mode, Tauri's native module is executing the http calls so CORS will not be a problem.

- Second is the renderer engine. In browsers, it is usually the latest modern engine, but in Tauri, it will be the OS's web engine, which is good, but maybe not as good as the browsers.

镜像加速参考了这个：https://rsproxy.cn/

**Comment by licheng1013** [comment]
> > > @licheng1013 你好，请问这个issue怎么close了？是怎么解决的？刚从Electron转过来，不太熟悉这个，遇到一样的问题，给整懵逼了，感谢。
> > 
> > 
> > 我这里是本地的localhost无法正常访问了，所以导致出现的问题。你可以试下用localhost:端口，访问前端项目看是否能正常访问。
> 
> 感谢，参考这个项目成功运行了：https://github.com/yooneskh/vite-tauri-template
> 
> ## Development
> There are two ways you can develo your app.
> 
> ### In Browser
> * `yarn serve`
>   
>   * launches vite and you can test and develop your app in the browser at http://localhost:8080.
> 
> ### In Tauri Window
> Launch two terminals and in
> 
> 1- `yarn serve:tauri`
> 
> This launches Vite and configures [Unified Network](https://github.com/yooneskh/unified-network) (which is mine) to use Tauri for api calls (to get around CORS problems).
> 
> 2- `yarn serve:native`
> 
> This launches Tauri window and you would see your app in the native window.
> 
> **Note:** There are mainly 2 differences between development in browser and in Tauri window.
> 
> * One is who executes your http calls, because when in browser, you are subject to CORS rules, but when testing in Tauri mode, Tauri's native module is executing the http calls so CORS will not be a problem.
> * Second is the renderer engine. In browsers, it is usually the latest modern engine, but in Tauri, it will be the OS's web engine, which is good, but maybe not as good as the browsers.
> 
> 镜像加速参考了这个：https://rsproxy.cn/

好的

**Comment by cathaysia** [comment]
第一次执行 serve 的时候会下载依赖。因此前端会卡住。可以先用 trunk serve 把前端跑起来再用 cargo
