### ISSUE TITLE
[feat] Expose file's path in html File api

### ISSUE THREAD

**Issue by BoooMaaa** [tauri-apps/tauri#6456]
### Describe the problem
`fileDropEnabled` has a conflict with `html drag`.
### Describe the solution you'd like
Like Elctron's [File Object](https://www.electronjs.org/docs/latest/api/file-object), if file's path is added to file object,users can implement `fileDrop` on the frontend without conflict.

**Comment by FabianLars** [comment]
This is unfortunately not possible, we do not have enough control over the browser to change the File object implementation. Otherwise we probably wouldn't even have the conflict and could resolve it inside the webview 🤔

We're actively trying to find a way to get rid of the conflict though.

Thanks for your feature request :)
