### ISSUE TITLE
Tooling: Bundler - Use from non Tauri apps

### ISSUE THREAD

**Issue by JessicaTegner** [tauri-apps/tauri#6474]
It says in the tooling/bundler/readme.md file

Tauri automatically loads configurations from the tauri.conf.json > tauri > bundle object, but this library doesn't rely on it and can be used by non-Tauri apps.

Implying that the Tauri bundler can be used to bundle a non Tauri app.
How would this be accomplished, considering that the bundler

* Download the webview
* And errors out because it doesn't look like a Tauri app (missing web assets/dist and so on)

If it's indeed possible to bundle a non-Tauri app with the Tauri-bundler, how would this be done?

**Comment by FabianLars** [comment]
You're right, it currently does not work outside of Tauri's (or _very_ similar) use-cases. The readme note comes from the fact that it _used_ to work and because it was a fork of `cargo-bundler`, a general purpose bundler.

And i _think_ we briefly mentioned once that we would like to have at least parts of it available for a wider audience (aka non-tauri users) again at some point :) -> No promises of course! (interpret this comment as my own opinion, not a tauri team statement)

**Comment by JessicaTegner** [comment]
Hi

Thanks for the response

Maybe it would be nice of the tauri team, to push some of the changes upstream to burtonageo/cargo-bundle (see burtonageo/cargo-bundle#116 ). Or alternatively, make a roadmap for how to make the tauri bundler work with non-tauri-app.
A roadmap as in what changes would be required in the tauri-bundler codebase to make it able to be used on non-tauri-app

**Comment by FabianLars** [comment]
The issue you linked is a bit unfortunate timing since we're basically moving tauri's msi target to be a second class citizen too, and will promote the new nsis target as the default one (because using WiX doesn't spark joy)

A roadmap would probably would probably entail something like "rewrite the whole bundler" 😂 Seriously there needs to happen a lot to a) make it more modular and b) make tauri specific stuff optional. Especially for targets like the appimage where the bundle format itself is really brittle by itself already.

So yeah, this will be a long running process, so upstreaming parts of it may be _easier_ but then the issue would be that nobody has time to do that anytime soon which may make the "long running process" faster in the end.

----

That was really weirdly phrased, sorry. i hope you get what i mean. There are just so many weird things we had to change for webview specific reasons (and the updater too i guess).

----

I'll do some more thinking and add a more concrete list of things i'd like to see happening here (in a way that would be possible for us to handle in a sane manner). Like for example the appimage bundler is one thing i don't see upstreamed any time soon from our side.

**Comment by JessicaTegner** [comment]
It makes sense. Or in any case, it would be nice with more people weighing in on the upstream issue. Cause I totally agree that WiX kills my joy from the inside.
I like the NSIS target myself, but again would be nice with more voices telling that WiX is dang impossible.

On that note (and without looking into it much), it sounds like the app package format for MacOS (dmg) should be easy enough to bundle regardless of the included app file(s). I mean, isn't it basically just a reskinned zip file with a custom background image.

But yeah, on the topic of Windows, it would be nice with more voices upstream.

**Comment by FabianLars** [comment]
idk if we just messed something up with our dmg bundler but in terms of problems it's the second place after appimages tbh. dmg is a disk image format so ig more similar to iso than zip.

We currently depend on a fork of https://github.com/create-dmg/create-dmg which tbh is not going too great for us, it is a bit brittle and many people have problems with it, so i hope that we can investigate a more rust native solution like https://github.com/indygreg/apple-platform-rs in the future - which imo would also be more suitable for upstream, _if_ it works.

**Comment by FabianLars** [comment]
I'd say that https://github.com/crabnebula-dev/cargo-packager which is based on tauri's bundler "fixes" this issue. The aforementioned cargo-bundle is of course also an alternative.

At this point i highly doubt we'll make tauri bundler itself more generic and instead make it (or rather, the tauri cli) use one of the other 2 projects, or mostly unmodified fork of them.
