### ISSUE TITLE
[bug] Cannot play youtube video in iframe

### ISSUE THREAD

**Issue by LemonAniLabs** [tauri-apps/tauri#6512]
### Describe the bug

The iframe can load the youtube web page, but after I click any video to watch it dosen't work.

This issue  happen on my Ubuntu 22.04, but I found Windows is ok.

### Reproduction

1. Add iframe with youtube url in html sample code body.
2.  Click any video to watch.
3. The loading circle rotate forever

### Platform and versions

```text
ubuntu 22.04 has this issue
windows 11 is ok.
```

**Comment by FabianLars** [comment]
We talked about this a few days ago on discord and it looks like youtube in general stopped working in webkitgtk (which is what tauri uses on linux). Can you test if it also doesn't work if you directly open the youtube website in your app?

**Comment by LemonAniLabs** [comment]
It's looks like this issue
[Link](https://github.com/void-linux/void-packages/issues/25852)

Any ideas to work on this in Tauri?
Thank you.

**Comment by FabianLars** [comment]
I don't think that's related. The youtube issues we're facing just started in Feb/March this year (no recent Tauri releases around that time). Either way, the issue you linked was fixed in the distro's packages themselves -> Not something we could do on our side.

**Comment by FabianLars** [comment]
Soooo, there were a few webkitgtk (related) updates and i also re-installed everything that may be related since i last checked on this issue and it works fine for me again.

Can you guys make sure to also install gstreamer plugins (including ones with "bad" and "ugly" in its name), quick search: https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c though they install dev packages too which we don't need here so if you find a more appropriate guide for our use case feel free to post it.

Edit: To be clear, i don't think there actually was a bug in webkitgtk, i think i just messed up something with the plugins, and also didn't mention them when we talked about this on discord... Sorry!

**Comment by wfc66986** [comment]
我现在就是http嵌套web 一直被拒绝访问 有什么办法解决在iframe内嵌时候
