### ISSUE TITLE
[feat] Support disable specific window

### ISSUE THREAD

**Issue by ch1ny** [tauri-apps/tauri#6660]
### Describe the problem

I wish I could disable a specific window by using an API like `tauri::Window.get_window("target").unwrap.set_enabled(false)`, just like `BrowserWindow.setEnabled` in `Electron`.

This would be helpful to prevent users from interacting with a certain window while opening a window to configure some options.

### Describe the solution you'd like

I'd like to use an API like 'set_enabled' to enable or disable a certain window.

**Comment by amrbashir** [comment]
I know it is possible on Windows but do you know if this electron API works on macOS and Linux?

**Comment by its-monotype** [comment]
It would be nice to have the ability to disable windows, for example, I need to disable additional windows when dialog is shown because it might be related not only to the parent window, let's say I have a main window and menu window, when I show dialog using tauri-plugin-dialog, only parent is disabled, in that case, menu window, but this dialog also related to main window and main window interaction should be disabled as well
