### ISSUE TITLE
[feat] Fedora official support

### ISSUE THREAD

**Issue by Apogeum12** [tauri-apps/tauri#6756]
### Describe the problem

I think that Tauri need more official support for fedora, like packages, flatpaks and dependencies for example webkit2gtk version bellow is only for Debian and ubuntu https://tauri.app/v1/references/webview-versions 

When the Flatpak support will added, then more developers like me will prefer developing own applications running as Flatpak on fedora. Fedora is more fresh then Ubuntu and have a lot better support for flatpaks, so it's obvious that the better will be creating on the fedora env.

### Describe the solution you'd like

Support last 2 verssion fedora:
Currently this'll 38 and 37. Ending support and bug fixes for 36

### Alternatives considered

Currently this'll 38. Ending support and bug fixes for 37.

### Additional context

The most support for linux should be for snap in Ubuntu env and flatpak in fedora env. Other like deb, rpm could be as additional. This would help reduce and tidy up a linux environment.

**Comment by FabianLars** [comment]
fedora is officially supported, and making sure of that is one of the main reasons why i'm using fedora (because no other team member uses it).

> https://tauri.app/v1/references/webview-versions

Adding the webkitgtk versions here honestly doesn't make much sense. Similar to how we shouldn't add the versions for Arch. Fedora and arch always use the latest versions (plus 1 or 2 weeks delay) so updating the versions in the docs all the time would be super annoying to be honest.

> and dependencies

The getting started guides show fedora specific instructions? Or are you talking about something else?

> so it's obvious that the better will be creating on the fedora env.

Fedora's "freshness" can also cause issues if it updates its glibc version before the flatpak runtime does, meaning apps compiled on the fedora system itself (not inside the flatpak sdk env) wouldn't work inside the flatpak runtime.

> Support last 2 versions of fedora

What exactly do you have in mind here? webkitgtk itself is updated as long as the fedora version isn't EOL. Tauri itself doesn't really have do anything specific to fedora so idk what we should change to improve the support. Feel free to expand on that point to add something more specific.

> The most support for linux should be for snap in Ubuntu env and flatpak in fedora env.

Snap support is worked on in https://github.com/tauri-apps/tauri/pull/6532 and flatpak is still mostly in research phase and i'm trying to find the time to actually add support for it in Tauri (hopefully soon as i know how important flatpak is, especially for tauri v2)

**Comment by Apogeum12** [comment]
@FabianLars 
> What exactly do you have in mind here? webkitgtk itself is updated as long as the fedora version isn't EOL. Tauri itself
> doesn't really have do anything specific to fedora so idk what we should change to improve the support. Feel free to 
> expand on that point to add something more specific.

If webkit2gtk is upgrade in any main version fedora like 36, 37 and now 38 to the most fresh then this point don't have sense indeed. Because I mainly meant support for current packages in these versions, with an emphasis on webkit.

> The getting started guides show fedora specific instructions? Or are you talking about something else?

In fact, I expressed myself badly here, I was thinking about binary files and final packages, i.e. rpm or flatpak. The same installation in prerequisites https://tauri.app/v1/guides/getting-started/prerequisites is very intuitive and sufficient to run the project after creating the project. 

Then all that's left in the request here is to add the ability to build rpm and flatpak packages. For Webkit2gtk I already understand the situation. Well, it turns out that fedora is currently officially supported, although without final files, so the topic can be closed. I'll hope that support for Flatpak and rpm soon will be available. Thanks for answer

**Comment by FabianLars** [comment]
ah alright, cool! And for reference, here's the PR for rpm support: https://github.com/tauri-apps/tauri/pull/5202. But yeah, for now appimages have to suffice :/
