### ISSUE TITLE
Please add all linux targets for build  ...

### ISSUE THREAD

**Issue by amirhossein-fzl** [tauri-apps/tauri#6772]
### Describe the problem

While the electronjs framework is a direct competitor to tauri, it produces output for the following purposes:

AppImage, flatpak, snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir ... [reference](https://www.electron.build/configuration/linux)

### Describe the solution you'd like

Add all Linux targets for output 😊...

**Comment by astudentinearth** [comment]
Related: #3619 #4402 
We can approach Arch support with a PKGBUILD that can create a .zst from the .deb bundle, there are such PKGBUILD files available for some proprietary apps on the AUR. I have never written a PKGBUILD despite using Arch for the last 2 years or so.
I think Flatpak should be prioritized since it's not distribution dependent and will fix the Tauri Linux distribution issues by a big portion. Fedora already uses Flatpak, which has quite a big userbase.
ps: FreeBSD isn't Linux though 😄

**Comment by amirhossein-fzl** [comment]
> Related: #3619 #4402 We can approach Arch support with a PKGBUILD that can create a .zst from the .deb bundle, there are such PKGBUILD files available for some proprietary apps on the AUR. I have never written a PKGBUILD despite using Arch for the last 2 years or so. I think Flatpak should be prioritized since it's not distribution dependent and will fix the Tauri Linux distribution issues by a big portion. Fedora already uses Flatpak, which has quite a big userbase. ps: FreeBSD isn't Linux though smile

The distribution is not only Arch and Debian... there are other distributions like RedHat and opensuse and... by the way, I should add that not everyone likes flatpak and snap like you...

**Comment by astudentinearth** [comment]
@amirhossein-fzl All I did was mention how we could approach it for Arch and distros that support flatpak. There is nothing wrong with sharing ideas. Also "not everyone likes snaps and flatpaks" is completely your opinion and this doesn't mean Tauri should not support it. You are looking only from your perspective now and not thinking of the end user. There are Ubuntu users that don't even know what snap is. They simply want to find the app in the app store and they don't care about the format. If we do it your way, I would say let's not bundle for macOS because Apple is a terrible company.
Also I never said I liked snaps, I would much rather see it disappear. I like Flatpaks because they are actually doing what they are doing in the open and trying to solve the packaging format hell. "Liking" something is never a software development criteria, and if it provides convenience to your customer, you should do it.

**Comment by amrbashir** [comment]
A build target is not a trivial thing to add so it may take some time until all targets are added. Ofc any help is appreciated. Also, I think each build target should have its own issue so we people can discuss and collect relevant issues together. We already support AppImage and Deb btw, feel free to open tracking issues for other formats.

**Comment by amirhossein-fzl** [comment]
> @amirhossein-fzl All I did was mention how we could approach it for Arch and distros that support flatpak. There is nothing wrong with sharing ideas. Also "not everyone likes snaps and flatpaks" is completely your opinion and this doesn't mean Tauri should not support it. You are looking only from your perspective now and not thinking of the end user. There are Ubuntu users that don't even know what snap is. They simply want to find the app in the app store and they don't care about the format. If we do it your way, I would say let's not bundle for macOS because Apple is a terrible company. Also I never said I liked snaps, I would much rather see it disappear. I like Flatpaks because they are actually doing what they are doing in the open and trying to solve the packaging format hell. "Liking" something is never a software development criteria, and if it provides convenience to your customer, you should do it.

That's what I meant... just because you like Flatpak doesn't mean other output targets shouldn't be considered... or because I like snap for example, so we shouldn't settle for snap... I In this issue, I requested that all Linux output targets be added like the competitor (electronjs)...
