### ISSUE TITLE
[bug] listen EACCES: permission denied ::1:1420

### ISSUE THREAD

**Issue by AriesChengYan** [tauri-apps/tauri#6804]
### Describe the bug

when start tauri app, listen EACCES: permission denied ::1:1420 error found

### Reproduction

![QQ截图20230427104503](https://user-images.githubusercontent.com/126456766/234747161-f953b67d-7d05-4281-85ef-61e435b857a7.png)

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 112.0.1722.58
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 18.16.0
  › npm: 8.19.2
  › pnpm: 8.3.1
  › yarn: Not installed!
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
```

**Comment by AriesChengYan** [comment]
![image](https://user-images.githubusercontent.com/126456766/234747279-37057bc6-a699-45f3-a080-d6a26041377f.png)

Port 1420 should be the system management port range

**Comment by JonasKruckenberg** [comment]
Interestingly looking up port 1420 on wikipedia lists it as "reserved" while browsing the real IANA list reveals that it is registered to some long since discontinued remote control software called Timbuktu.

I've seen people report this kind of issue on Windows in connection to hyper-v but ultimately it's apparently hard to debug. As a workaround you can set a different port in you `vite.config.ts` and `src-tauri/tauri.conf.json` files (make sure they are the same port)

As for a proper fix @amrbashir why was this changed from vites default port anyway (5173)? This seems like something that slipped through review and should be reverted

**Comment by amrbashir** [comment]
> As for a proper fix @amrbashir why was this changed from vites default port anyway (5173)? This seems like something that slipped through review and should be reverted

@JonasKruckenberg  We used to get multiple issues about port `3000` or `8080` is taken or the tauri app shows a different web app and that's because `3000`, `8080` and such were common in web dev and so we decided to choose a different port specific to tauri apps since almost no one runs two tauri-apps at the same time so collision was less common. And now that vite is so popular we had to also stay away of `5173`

**Comment by liudonghua123** [comment]
I have the same problems. 

You can also show/add/delete the via `netsh int ip show excludedportrange protocol=tcp`/`netsh int ip add excludedportrange protocol=tcp numberofports=1 startport=1420`/`netsh int ip delete excludedportrange protocol=tcp numberofports=1 startport=1420`.

  >for me restarting host network service solves EACCESS issue temporarily. I even created an bat script for this issue!
  >
  >sc stop HNS
  >sc start HNS

See also https://stackoverflow.com/questions/59428844/listen-eacces-permission-denied-in-windows/77990399#77990399


```shell
Liu.D.H  ~   0ms  08:52 > netsh int ip show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      8450        8549
      8550        8649
      8650        8749
      8750        8849
      8850        8949
      9129        9228
      9229        9328
      9329        9428
      9429        9528
      9529        9628
     50000       50059     *

* - Administered port exclusions.


Liu.D.H  ~   70ms  08:52 > netsh int ip add excludedportrange protocol=tcp numberofports=1 startport=3121
Ok.


Liu.D.H  ~   58ms  08:53 > netsh int ip show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      3121        3121     *
      8450        8549
      8550        8649
      8650        8749
      8750        8849
      8850        8949
      9129        9228
      9229        9328
      9329        9428
      9429        9528
      9529        9628
     50000       50059     *

* - Administered port exclusions.


Liu.D.H  ~   71ms  08:53 > netsh int ip delete excludedportrange protocol=tcp numberofports=1 startport=3121
Ok.


Liu.D.H  ~   68ms  08:53 > netsh int ip show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      8450        8549
      8550        8649
      8650        8749
      8750        8849
      8850        8949
      9129        9228
      9229        9328
      9329        9428
      9429        9528
      9529        9628
     50000       50059     *

* - Administered port exclusions.


Liu.D.H  ~   65ms  08:53 >
```
