### ISSUE TITLE
[feat] Improve HTTP API

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#6824]
### Describe the problem

1. Inconsistent naming. HTTP client struct is called "Client" whereas the request builder struct is "HttpRequestBuilder" so I have to import like this: `use tauri::api::http::{ClientBuilder as HttpClientBuilder, Client as HttpClient, HttpRequestBuilder, Body as HttpBody, FormBody as HttpFormBody, FormPart as HttpFormPart};`
2. Lacks basic features, documentation and overall it's just poorly designed. 
    - Why does `Response::bytes()` return `RawResponse` instead of `Vec<u8>`? There is no need for that `status` field, you can get it from `Response`.
    - Why is there no enum for HTTP methods? 
    - `HttpRequestBuilder::body` should just be `Option<Vec<u8>>`, users can take care of serialization themselves and the way it is currently implemented is very annoying.
    - There is no way to set a proxy to debug all this mess. That is the reason I opened this issue by the way.
3. `attohttpc` is a questionable crate. Poorly documented and no HTTP/2 support.

### Describe the solution you'd like

I would like a new HTTP API in tauri 2.0 or just remove it completely.

**Comment by FabianLars** [comment]
Thanks for your feedback :)

The HTTP api was indeed removed in v2 (moved into an external plugin). And to explain a bit why the api is so weird (point 1 and 2): It was primarily created for internal use especially for the js endpoints (and for the updater etc), and we just ended up publicly exporting it in case it may help someone, but in general the `reqwest` crate (or similar) is still recommended for the rust side.

And about point 3: attohttpc was removed from the codebase and the new plugin in v2 and we'll likely back port it to v1.4 because it has more issues than the 20kb file size savings are worth.

**Comment by ghost** [comment]
> Thanks for your feedback :)
> 
> The HTTP api was indeed removed in v2 (moved into an external plugin). And to explain a bit why the api is so weird (point 1 and 2): It was primarily created for internal use especially for the js endpoints (and for the updater etc), and we just ended up publicly exporting it in case it may help someone, but in general the `reqwest` crate (or similar) is still recommended for the rust side.
> 
> And about point 3: attohttpc was removed from the codebase and the new plugin in v2 and we'll likely back port it to v1.4 because it has more issues than the 20kb file size savings are worth.

Sounds reasonable, thank you.
