### ISSUE TITLE
[bug] custom base lead to wrong content-type

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#6963]
### Describe the bug

see repro

### Reproduction

1. set `base='./xxx'` in `vite.config.ts`
2. `pnpm tauri build`
3. click `.exe` in `target/release`
4. open devtools then see errors: `*.js` & `*.css` are regard as `text/html`

It seems that `/assets/index.js` (asset protocol?) is broken by `/xxx/assets/index.js`. and similarly, access `https://tauri.localhost:8080` ,which is a http service, also got the same errors.

### Platform and versions

```text
1.3.0
windows 11
```

**Comment by amrbashir** [comment]
The reason why it is not working in release because custom base is an option specific to vite and `vite build` with a custom base will build the following `dist` dir:
```
dist/
  |_ assets/
  |_ index.html
```
which is the same structure as if the custom base option wasn't used so tauri can't know if you're using a custom base or not.

we could add an option in `tauri.conf.json` to specify a custom base and use it to resolve assets in production build but I am not sure if it is really needed/worth it. 

why do you need to use a custom base?

**Comment by xdewx** [comment]
> why do you need to use a custom base?

In my use case, i would like to access the page with both exe and browser at `dev mode`. When browser, i need nginx `reverse proxy` which needs a base path.

Of course, i could remove base when build for production, but need to change codes. 

---

And, why `tauri.localhost:otherport` can't bypass tauri? I start a http server with rust, but i can't get the expected `json` data from target api which seems intercepted by tauri.

**Comment by amrbashir** [comment]
you could check if `TAURI_PLATFORM` env var is defined and disable the custom base while building for tauri.
```js
export default defineConfig(async () => ({
	base: process.env.TAURI_PLATFORM ? undefined : 'xxx'
})
```
