### ISSUE TITLE
[docs]  How to dynamically modify the "window[0].theme" in tauri.config.json?

### ISSUE THREAD

**Issue by Maydisease** [tauri-apps/tauri#7027]
How to dynamically modify the "window[0].theme" in tauri.config.json? I only see the "change" and "get" methods.

**Comment by FabianLars** [comment]
This is not implemented yet, see https://github.com/tauri-apps/tauri/issues/5279.

**Comment by Maydisease** [comment]
> This is not implemented yet, see #5279.

Is it possible to achieve this through some method, such as restarting the application to read the modified tauri.config.json or configuration?

**Comment by FabianLars** [comment]
You can close and re-open the windows like i showed here: https://github.com/tauri-apps/tauri/issues/5279#issuecomment-1263643559 - rust equivalent: https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.theme

**Comment by Maydisease** [comment]
> You can close and re-open the windows like i showed here: [#5279 (comment)](https://github.com/tauri-apps/tauri/issues/5279#issuecomment-1263643559) - rust equivalent: https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.theme

Is it possible to configure in the setup phase in Rust? Or can we create a new WebviewWindow instead of doing it at the render layer in Rust? Could you kindly provide some code examples for reference?

**Comment by FabianLars** [comment]
> Is it possible to configure in the setup phase in Rust?

Yes, scroll all the way to the top of the WindowBuilder doc page i sent. It uses the .setup hook there. Normally you'd remove the window config from tauri.conf.json if you use these apis, but there's now also a method to get a WindowBuilder from the config: <https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html#method.from_config>. Combining both these things you'd end up with something like this:
```rs
tauri::Builder::default()
  .setup(|app| {
    let window = tauri::WindowBuilder::from_config(&app, app.config().tauri.windows.get(0).unwrap().clone())
      .theme(Some(tauri::Theme::Dark))
      .build()?;
    Ok(())
  });
```

Doing this in JavaScript will be tricky since you need an existing window to run any js code.
