### ISSUE TITLE
如何在生产中 将本地nodejs存放本地调用使用！ 

### ISSUE THREAD

**Issue by wfc66986** [tauri-apps/tauri#7082]
### Describe the bug

如何在生产中 将本地nodejs存放本地调用使用！ 

### Expected behavior

如何在生产中 将本地nodejs存放本地调用使用！ 

### Platform and versions

```text
如何在生产中 将本地nodejs存放本地调用使用！
```

**Comment by FabianLars** [comment]
Could you explain your question a bit more, maybe with some examples? I honestly have to idea what you're asking for - the english translation didn't make much sense to me tbh.

Since you're mentioning nodejs, one thing so we're on the same page: There is no nodejs runtime in a tauri app. - I doubt that this will answer your question...

**Comment by FlysoftBeta** [comment]
用[pkg](https://github.com/vercel/pkg)打包你的nodejs代码为exe，然后通过[sidecar](https://tauri.app/v1/guides/building/sidecar/)调用，这里有一个[官方提供的示例](https://github.com/tauri-apps/tauri/tree/dev/examples/sidecar)
