### ISSUE TITLE
Bundler Crates out of date.

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#72]
![Screen Shot 2019-11-27 at 01 12 03](https://user-images.githubusercontent.com/35242872/69682808-f8a4e280-10b2-11ea-927a-eb8c54268797.png)

**Comment by tensor-programming** [comment]
Ill go through and clean up the ones that can be cleaned.  Most of them should be able to be updated without breaking anything.

**Comment by jbolda** [comment]
@tensor-programming it may be easier to let the Renovate bot to take care of that after #71 merges.

**Comment by nothingismagick** [comment]
@kastenbutt - feel like giving this a shot? I'm not sure I trust the Renovate bot yet, because it is "merely" seeing that stuff can be updated. It doesn't know for example that `phf` needed to be at a specific version.

**Comment by kastenbutt** [comment]
@nothingismagick Yes, I'll try :)

**Comment by jbolda** [comment]
@nothingismagick it will just blindly update to whatever the latest is as far as I know. If you manually update something that it has a PR for already, it will just autoclose the PR for you. Ideally, we want to add tests that break if our code breaks or something needs to be a specific version. I _think_ the Rust implementation in Renovation is still in a beta state so it could certainly be missing some of the version resolution stuff though. I am not super familiar with how Rust deals with that. Sounds good to me too to update these in one shot 👍

**Comment by kastenbutt** [comment]
I went through all dependencies, checked how they were used, checked the respective documentation, updated the dependency and fixed any errors coming up. See the respective PR for the fixes.

- winit:  It's not used -> remove
- ar: Seems fine, usage in the bundler complies with the crates's documentation
- cab: Is not used anywhere -> remove
- dirs: Only used to osx_bundle.rs to obtain home dir. Major version update should be fine.
- glob: Seems fine, usage in the bundler complies with the crates's documentation
- images: Here a few minor changes are necessary to update to the latest version.
  1. PNGDecoder::new now returns a PNGDecoder wrapped in a Result
  2. ImageDecoder::dimensions returns a u64 instead of a u32 tuple. As icon files won't be so large as to warrant dimensions of type u64 I propose to cast them down.
- md5: Seems fine, usage in the bundler complies with the crates's documentation
- strsim: Seems fine, usage in the bundler complies with the crates's documentation
- term: Seems fine, usage in the bundler complies with the crates's documentation
- toml: Seems fine, usage in the bundler complies with the crates's documentation
- uuid: Some changes are necessary:
   1. from_bytes does not take a reference anymore and returns a Uuid instead of a Result
   2. Uuid::new_v5 expects a u8 array instead of a str as its second parameter
- lazy_static: Seems fine, usage in the bundler complies with the crates's documentation
- handlebars: Major version upgrade seems fine. The way it is used still complies to the crate's documentation
- hex: Seems fine, usage in the bundler complies with the crates's documentation

**Comment by tensor-programming** [comment]
looks good to me, @kastenbutt

**Comment by nothingismagick** [comment]
Thanks!
