### ISSUE TITLE
[feat] Windows default notification sound should be optional

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#7210]
### Describe the problem

https://github.com/tauri-apps/tauri/pull/6680 added default sound when notification is shown. This should be optional.

### Describe the solution you'd like

Make the default sound opt-in

### Alternatives considered

Make default sound opt-out

### Additional context

For my cross-platform app I want to have consistent sound being played on all systems so I play custom sound along with showing the notification.

**Comment by killua1zoldyck** [comment]
@FabianLars , can I work on this?

**Comment by FabianLars** [comment]
Sure, unfortunately we moved the convo to discord so this issue is missing a bit of context: https://discord.com/channels/616186924390023171/986184168998330371/1118907743269564498

Summary:
- Linux and macOS seem to not emit a sound right now.
- The windows sound should be reverted in a patch
- There should be a new sound_name api in a minor patch adding support for all 3 oses. Problem is that the sound names are very different on the 3 oses so we'll probably go for a simple string input
  - macOS sound options: Basso, Blow, Bottle, Frog, Funk, Glass, Hero, Morse, Ping, Pop, Purr, Sosumi, Submarine, Tink
  - Windows: https://allenbenz.github.io/winrt-notification/0_2_0/winrt_notification/enum.Sound.html
  - Linux: https://0pointer.de/public/sound-naming-spec.html (via https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html)

**Comment by killua1zoldyck** [comment]
Oh ok. I will look for smaller and easier to fix issues then since I am new to the stack as well as this project. Thank you!

**Comment by amrbashir** [comment]
1.4.1 has been released that removed this default sound, stay tuned for 1.5 where we will add support for specifying the notification sound
