### ISSUE TITLE
[bug] NSIS installer fails if installing into protected folder

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#7295]
### Describe the bug

The installer never asks for elevated privileges and it results into failed install

![image](https://github.com/tauri-apps/tauri/assets/3622532/5f3908cd-961f-43a2-b9ac-7eed0615085f)

### Reproduction

Manually change the installation path to a protected folder like Program Files, proceed with installation.

### Expected behavior

UAC prompt pops up to require elevated privileges.

### Platform and versions

```text
[✘] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.58
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.2
    - pnpm: 8.6.2
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.4.0
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:8080/
    - framework: React
    - bundler: Webpack
```

### Additional context

Tauri configs are here https://github.com/openscopeproject/TrguiNG/blob/master/src-tauri/tauri.conf.json

Same issue happens with updates: https://github.com/openscopeproject/TrguiNG/issues/15

**Comment by FabianLars** [comment]
There's a setting for that here https://tauri.app/v1/api/config#nsisconfig.installmode (just noticed that we broke the link there, just scroll below the table for the possible values). Setting it to `perMachine` or `both` will make it _always_ ask for admin permissions.
"On demand" privileges were deemed too difficult since it requires multiple installer executables (internally) iirc, therefore i'm closing this - will re-open if someone knows of a sane way to implement it :)

**Comment by qu1ck** [comment]
I see, thanks. I was hoping that the UAC plugin could be used https://nsis.sourceforge.io/UAC_plug-in but it seems to be deprecated.
