### ISSUE TITLE
' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by lanxuan4444** [tauri-apps/tauri#7298]
### Describe the bug

ps://www.dataco.com/api/ozon-report-service/v1/home/homeData?type=5&tenantId=13&_t=1687750319609' from origin 'https://tauri.localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Reproduction

The interface fails after the production of the packaged build cross-domain
![image](https://github.com/tauri-apps/tauri/assets/17310230/3f84cf0d-6b47-4045-bd0c-9e8f89c06612)

### Platform and versions

```text
yarn tauri build
```

**Comment by FabianLars** [comment]
This is not something we have much (or any) control over. For an actual fix it needs server-side changes to include the correct response headers. Note that this sometimes is a false-positive and there may be other connection issues, so maybe try doing the same requests in the browser (from a secure context) or via curl.

If the problem is indeed the ACAO header but you can't change the server then you could try tauri's http api https://tauri.app/v1/api/js/http#functions which doesn't care about cors.

**Comment by Quietly-20201113** [comment]
2.0呢
