### ISSUE TITLE
[docs] Accesing AppHandle guide need to be updated

### ISSUE THREAD

**Issue by hckhanh** [tauri-apps/tauri#7316]
When I am using Tauri and try to access `AppHandle` in `tauri::command`, I realized that the interface of param is used for `AppHandle` was changed to `AppHandle<R: Runtime>`. Please update the old docs according to the changes:

```rust
#[tauri::command]
async fn my_custom_command(app_handle: tauri::AppHandle) {
  let app_dir = app_handle.path_resolver().app_dir();
  use tauri::GlobalShortcutManager;
  app_handle.global_shortcut_manager().register("CTRL + U", move || {});
}
```

**Comment by FabianLars** [comment]
The docs are still correct. In normal commands the type parameter is not used. That said, the intellij-rust plugin will complain if it's missing though that seems to be fixed in an [upcoming release](https://github.com/intellij-rust/intellij-rust/issues/9128) (merged 5 days ago). -> If this is your issue, try actually compiling the app and it should work fine.

Lastly, in _plugin_ commands this is indeed required but i'd prefer to explain that in the plugin docs, not in the general guide.
