### ISSUE TITLE
[bug] windows NSIS uninstall.exe is not code signed

### ISSUE THREAD

**Issue by jetli** [tauri-apps/tauri#7348]
### Describe the bug

the uninstall.exe file created by NSIS installer is not code signed in building process, so when uninstall an app, warning of UAC is still shown.
The bundle process should also code sign the uninstall.exe file when using NSIS installer.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Community 2019
        - Visual Studio 生成工具 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.18.0
    - yarn: 3.2.4
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by jetli** [comment]
see some issues related to NSIS: https://github.com/tauri-apps/tauri/issues?q=is%3Aissue+is%3Aopen+nsis+
and this makes NSIS installer a little bit unusable now, I think a minor release to improve NSIS is a great idea.

**Comment by amrbashir** [comment]
What type of certificate are you using to sign your app?

**Comment by jetli** [comment]
EV certificate of DigiCert with a hardware usb key.
the uninstall.exe is in the installed directory, not sure it is generated on fly by NSIS or could be pre code signed in the bundle.

**Comment by amrbashir** [comment]
it is generated by NSIS, you will need to provide a custom NSIS https://tauri.app/v1/api/config#nsisconfig.template and use [`uninstfinalize!`](https://nsis.sourceforge.io/Docs/Chapter5.html#uninstfinalize) macro to insert a command that could be used to sign your uninstaller as well.

**Comment by jetli** [comment]
Can we add this step to tauri built-in process, so everyone does not need to use custom template everytime?

**Comment by amrbashir** [comment]
yeah I plan to add that but as far as I know, we support signing with OV certificates only (more specifically, those issued before prior to 2023) so if you have an EV certificate, you must have a different signing workflow and in that case you will need to directly use, `uninstfinalize!`.

cc @FabianLars since he knows more about Windows signing

**Comment by FabianLars** [comment]
> cc FabianLars since he knows more about Windows signing

I can only confirm what you said 👍 We currently don't support signing with hardware tokens (including cloud HSM) so manual steps are required either way. And imo it doesn't make sense to add support for it just for the nsis uninstaller if the rest of the build pipeline doesn't support it (It's also not straight forward to add it since the cli differs if you use a local token vs a cloud one, especially since we have access to neither...)

That said, we should look into supporting old OV certificates at least to match the rest of tauri's bundler legacy-OV support.

**Comment by amrbashir** [comment]
> That said, we should look into supporting old OV certificates at least to match the rest of tauri's bundler legacy-OV support.

Yup that is pretty much what I intend to do.
