### ISSUE TITLE
[feat] Component based splash screen

### ISSUE THREAD

**Issue by ArthurFleischman** [tauri-apps/tauri#7485]
### Describe the problem

Some rust web frameworks such as yew updates the dist folder in every build making impossible to have an splashscreen.html inside.

### Describe the solution you'd like

To solve the problem, would be nice to render the splashscreen as a component example:
```rust
tauri::Builder::default()
.setup(|app| {
let splashscreen_window = app.render_component(Component);
app.append_splashscreen(splashscreen_window);
});
```

### Alternatives considered

make possible to during the build trunk/tauri add the splashscreen.yml to the built project

**Comment by FabianLars** [comment]
Thanks for the request! Unfortunetly i think this is completely out of scope of Tauri as this would be highly framework dependent.
Since yew doesn't have a multi-page feature i'd probably either just use the router if you need yew in the splashscreen, or copy a standalone html file into the distDir either by having a build script wrapper around the trunk/yew build command, or by using trunk's built-in asset feature: https://trunkrs.dev/assets/

**Comment by ArthurFleischman** [comment]
> Thanks for the request! Unfortunetly i think this is completely out of scope of Tauri as this would be highly framework dependent.
> 
> Since yew doesn't have a multi-page feature i'd probably either just use the router if you need yew in the splashscreen, or copy a standalone html file into the distDir either by having a build script wrapper around the trunk/yew build command, or by using trunk's built-in asset feature: https://trunkrs.dev/assets/

Thanks, and sorry for any inconvenience.
