### ISSUE TITLE
[bug] Updating menu items not working

### ISSUE THREAD

**Issue by grzianod** [tauri-apps/tauri#7562]
### Describe the bug

Updating menu items not showing to be updated after calling methods to manipulate them

### Reproduction

https://github.com/grzianod/screencrab

### Expected behavior

Expected menu items to be selected 

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.67.1 (d5a82bbd2 2023-02-07)
    ✔ Cargo: 1.67.1 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (fae52a197 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.14.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0
```

**Comment by pewsheen** [comment]
It's acting weird with multiple windows initialized.

Here are some documents that I think you might want to reference since the project is using multiple windows and want to show the main window only:
- [Create a window using the App instance](https://tauri.app/v1/guides/features/multiwindow#create-a-window-using-the-app-instance): You could disable the original window from `tauri.conf.json` and create a main window manually to add the menu to a specific window.
- [Adding the menu to a specific window](https://tauri.app/v1/guides/features/menu#adding-the-menu-to-a-specific-window): While you manually create the main window, you can add the menu to the main window instead of all windows.
- [Listening to events on window menus](https://tauri.app/v1/guides/features/menu#listening-to-events-on-window-menus): Also, you may want to listen to the menu events that emit from the main window only.

The weird part that I tested out is the latter-built window's menu (even if you didn't set a menu for that window, it would use the default menu) will replace the former one, so you may need to build the main window with the menu after the area (selector) window is built.
