### ISSUE TITLE
[bug] i cannot set windows center in windows 10

### ISSUE THREAD

**Issue by salmidiv** [tauri-apps/tauri#7649]
### Describe the bug

hi i have screen with 1366*768

when i set this config for window: 

> `
> "windows": [
>       {
>         "fullscreen": false,
>         "height": 700,
>         "resizable": true,
>         "title": "tauri app",
>         "width": 1250,
>         "minHeight": 700,
>         "minWidth": 1250,
>         "center": true
>       }
> `

the window disappear inder the windows taskbar, 
i tray to set "height": 650, 
The distance between the top of the screen and the window is greater than the distance between the window and taskbar
![image](https://github.com/tauri-apps/tauri/assets/16426510/970d83d3-36d4-45fd-a02a-a4774bb25222)

### Platform and versions

```text
npm run tauri info

> school-manager-app@0.1.3 tauri
> tauri info


[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 115.0.1901.203
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.71.0 (8ede3aae2 2023-07-12)
    ✔ Cargo: 1.71.0 (cfd3bbd8f 2023-06-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.2
    - pnpm: 8.6.0
    - yarn: 1.22.19
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0
```

**Comment by i-c-b** [comment]
There was some previous discussion in Discord: https://discord.com/channels/616186924390023171/1139502800162791455.

**Comment by amrbashir** [comment]
The window is actually centered because it doesn't care for the taskbar size and position.

Explanation: because the monitor height is `768px` and your window is `700px` and so we are left with only `68px`, `34px` at each end, and your window position will start at `34px` on the Y axis and ends at `34 + 700 = 734px` on the Y axis and since the taskbar size on Windows 10 is `40px`, its position will start at `768 - 40 = 728px` and since `728(taskbar start) < 734(your window end)`, it makes sense that it goes under the taskbar.
