### ISSUE TITLE
How to run .exe located in document path

### ISSUE THREAD

**Issue by kingsanu** [tauri-apps/tauri#7650]
### Describe the problem

I tried number of way, but i can't able to open a .exe file located in document path in window. please help me to do it from javascript or rust.

### Describe the solution you'd like

I tried number of way, but i can't able to open a .exe file located in document path in window. please help me to do it from javascript or rust.

**Comment by FabianLars** [comment]
So from rust it should be just something like this, using https://doc.rust-lang.org/std/process/struct.Command.html (untested and typed directly on github so there may be typos):
```rs
let doc_dir = tauri::api::path::document_dir().unwrap(); // Be careful with the unwrap here. If there's no doc dir, or depending on the OS the env vars aren't set, your program will crash.
let exe_path = doc_dir.join("my_binary.exe");

std::process::Command::new(exe_path).output().expect("failed to execute process");
```
I could imagine that you already tried this so please also describe the actual issues you had so we can give more specific help.

For JS, you first have to define the allowlist/scope
```json
{
  "tauri": {
    "allowlist": {
      "shell": {
        "execute": true,
        "scope": [{
           "name": "run-bin"
           "cmd": "$DOCUMENT/my-binary.exe" // This may have to be written without the .exe extension, not sure.
        }]
      }
    }
  }
}
```
Then you can execute that in js like this: <https://tauri.app/v1/api/js/shell#command> using `new Command('run-bin')` instead of 'node' as shown on that page.
