### ISSUE TITLE
[feat] windowsOS titleBarStyle configure

### ISSUE THREAD

**Issue by drl990114** [tauri-apps/tauri#7674]
### Describe the problem

https://tauri.app/v1/api/config/#windowconfig.titlebarstyle 

In tauri 1.x, It only supports macos，Will it appear on 2. x?

Or is there any other way for me to achieve something similar to `TitleBarStyle::Overlay`  on WindowsOS

### Describe the solution you'd like

 To achieve something similar to TitleBarStyle::Overlay on WindowsOS
 
e.g
```rs
main_win.title_bar_style(TitleBarStyle::Overlay).hidden_title(true);
```

**Comment by FabianLars** [comment]
This was talked about a few times for example here https://github.com/tauri-apps/tauri/issues/4973 (windows specific) and also in the general/macos issue starting here https://github.com/tauri-apps/tauri/issues/2663#issuecomment-1300707015 and the tldr is basically that the reason why tauri has that setting on macos but not on windows is because macos itself has system apis for this while windows doesn't. We thought about providing prebuilt html elements (the icons are part of windows' default fonts i think, or at least freely available) but i don't think we can make the DX of that nice enough.

The only you can't do with html/css/js is the new snap overlay added in windows 11, but that's tracked here: https://github.com/tauri-apps/tauri/issues/4531

**Comment by drl990114** [comment]
Thanks, sorry I only searched for the term "titleBarStyle" and found no related questions.
I will continue to pay attention and look forward to the release of this feature
