### ISSUE TITLE
[feat] support multiple values for    "devPath": "http://localhost:1420",     "distDir": "../dist",

### ISSUE THREAD

**Issue by conanchen** [tauri-apps/tauri#7687]
### Describe the problem

My application has mixed access to local resources/webpages bundle in tauri-apps and remote resources/webpages from my web-server. 

### Describe the solution you'd like

I think if good to support multiple values for devPath and distDir like:

    "devPath": ["default":"http://localhost:1420", "local":"http://localhost:1420", "remote":"https://www.example.com"]
    "distDir": ["default":"../dist","local":"../dist","remote":"https://www.example.com"]

so that in index.html I can code like below for example:

    <div class="row">
      <a href="https://vitejs.dev" target="_blank">
        <img src="/src/assets/vite.svg" class="logo vite" alt="Vite logo" /> 
         this will load image from default location dev:http://localhost:1420, dist:../dist
      </a>
      <a href="https://tauri.app" target="_blank">
        <img src="remote://assets/tauri.svg" class="logo tauri" alt="Tauri logo" />
        this will load image from remote web-server: www.example.com
      </a>
      <a href="https://www.typescriptlang.org/docs" target="_blank">
        <img src="local://src/assets/typescript.svg" class="logo typescript" alt="typescript logo" />
         this will load image from local location dev:http://localhost:1420, dist:../dist
      </a>
    </div>

**Comment by simonhyll** [comment]
I'm not sure that's the most appropriate location for such a setting. That feels more like a configuration of the asset protocol rather than a change in the dev url or dist directory, and should therefore probably be configured one way or another in an asset protocol config.

You can already implement this sort of logic btw by registering your own custom uri scheme protocol, simply use the `asset` protocol as per usual for local files and register a new `remote` protocol for fetching remote files. Though then again, if it's a remote file there's not really much use in fetching it via a protocol, you can just fetch it directly in the frontend.
