### ISSUE TITLE
[feat] File explore context menu

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/tauri#7748]
### Describe the problem

I would like to insert custom right-click context menu options when I right click within a **file explorer**.

I could not find this API in the current documentation or issue. 

I found this issue about native context menu (https://github.com/tauri-apps/tauri/issues/4338). The proposed [tauri-plugin-context-menu](https://github.com/c2r0b/tauri-plugin-context-menu/) works but only within the Tauri app. 

### Describe the solution you'd like

Add APIs for inserting items into file explorer context menu.

Here is an example of my Mac Finder context menu, all of the extra options are added by an app called **iRightMouse**.

It would be nice if we can do similar things, making Tauri apps much more powerful.

![image](https://github.com/tauri-apps/tauri/assets/33727687/704976ef-1c95-4b2a-af63-70c98fda9491)

**Comment by amrbashir** [comment]
This is out of tauri scope. It is a niche use-case and an implementation detail of the app not the framework. If you feel like I am overlooking something, please let me know

**Comment by dukeeagle** [comment]
@HuakunShen do you intend to make a plugin that does this? Would love to discuss if so.

**Comment by HuakunShen** [comment]
@dukeeagle I want this feature, but didn't have a chance to research on this yet.

**Comment by ok-nick** [comment]
Hi, I implemented this for my app on macOS (currently). You can check out the project [here](https://github.com/ok-nick/c2pa-preview) and the finder extension code [here](https://github.com/ok-nick/c2pa-preview/blob/main/backend/src/file_ext/finder.rs) and [here](https://github.com/ok-nick/c2pa-preview/blob/main/backend/Info.plist).

I decided not to implement a "[finder sync extension](https://developer.apple.com/documentation/findersync)" because they require compiling a separate `.appex` program and you'd have to use IPC which can get cumbersome. Rather, I used (the less powerful) [NSServices](https://developer.apple.com/documentation/bundleresources/information_property_list/nsservices) which you can find defined in my [Info.plist](https://github.com/ok-nick/c2pa-preview/blob/main/backend/Info.plist) file.

It looks something like this:
<img width="1031" alt="finder" src="https://github.com/tauri-apps/tauri/assets/25470747/6639ebd9-d24a-4bfa-9217-3d526abdf42f">
