### ISSUE TITLE
How to access plugins from javascript when not using NPM, using simple vanila javascript

### ISSUE THREAD

**Issue by kingsanu** [tauri-apps/tauri#7804]
### Describe the problem

![image](https://github.com/tauri-apps/tauri/assets/47456495/5a884459-d979-4d22-b842-de691001fd90)

Here it's not work because i don't using NPM so how can i access it from javascript.

### Describe the solution you'd like

![image](https://github.com/tauri-apps/tauri/assets/47456495/5a884459-d979-4d22-b842-de691001fd90)

Here it's not work because i don't using NPM so how can i access it from javascript.

**Comment by Morsmalleo** [comment]
I think filling a Bug Report out would be more ideal and would probably help the Devs further understand your problem, as the issue template you have filled out is for Feature Requests (requests to add something new), your issue seems more suited to a [Bug Report](https://github.com/tauri-apps/tauri/issues/new?assignees=&labels=type%3A+bug%2Cstatus%3A+needs+triage&projects=&template=bug_report.yml&title=%5Bbug%5D+] 😁

**Comment by amrbashir** [comment]
This is not really related to tauri and is more of a general JS question so please keep the issue tracker for bugs and feature requests related to the tauri project.
