### ISSUE TITLE
[bug] Dialog asynchronous execution wait end of current function to start

### ISSUE THREAD

**Issue by NicsTr** [tauri-apps/tauri#8107]
### Describe the bug

It seems that the asynchronous dialog API is delaying the execution of the actual opening of the dialog until the end of the function it has been defined.

The blocking API is also not working as expected.

### Reproduction

This bug can be reproduced using this project: https://github.com/NicsTr/test-tauri-dialog-api

Launch the project (`cargo tauri dev`) then input anything in the text form and click the "Greet" button.

A delay of ten seconds has been purposefully inserted to demonstrate the bug. Another way to demonstrate the bug is to use the sender/receiver paradigm that will freeze indefinitely (because it is blocking on the receiver end).

After closing the "Open file" dialog, you should see in the logs:
```
[2023-10-18][13:21:54][INFO][test_tauri_dialog_api] Before!
[2023-10-18][13:22:04][INFO][test_tauri_dialog_api] After!
[2023-10-18][13:22:05][INFO][test_tauri_dialog_api] Here!
```

### Expected behavior

I expected the blocking API not to freeze the app and the asynchronous one to be able to start executing before leaving the current function.

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.42.1
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.15.1
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.5.3 (outdated, latest: 1.5.6)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1421/
```

**Comment by FabianLars** [comment]
So first of all, the blocking api can only be used in non-main thread contexts. Here this would mean to change the tauri command from `fn` to `async fn` (or `#[tauri::command(async)]`). Then this one should work fine.

For the async api i'm not exactly sure but i'd imagine that, because blocking the main thread (which the `sleep()` call is doing) also blocks the gtk loop, the latter doesn't have a change to start or drive it.

I'm a bit unsure about the async api so i leave this issue open for other people to check out first, but _i_ think it's all behaving as expected 🤔

**Comment by NicsTr** [comment]
I followed your recommendation and it (indeed) works.

I guess the async part also is working fine and I'm not doing things as I am supposed to do.

Thanks for your help.
