### ISSUE TITLE
Files won't load properly on Windows

### ISSUE THREAD

**Issue by beeequeue** [tauri-apps/tauri#812]
**Describe the bug**
I'm trying to set up [a project](https://github.com/BeeeQueue/yuna-tauri/tree/not-working) with Tauri and [Vite](https://github.com/vitejs/vite), but I'm running into issues with loading files.

When using the dev server it simply shows a white screen, as the script file doesn't execute itself. However when checking the devtools it shows that it does in fact [load all the files](https://user-images.githubusercontent.com/472500/87223000-3ff98e00-c379-11ea-9488-958176ee8b09.png), but nothing happens afterwards. The app doesn't mount and the css isn't applied to the page.

When building the project the resulting application will [manage to mount the Vue app, but then fail to load any other assets](https://user-images.githubusercontent.com/472500/87223258-9798f900-c37b-11ea-8497-f3fff7c4f107.png).
If you reload the page via the devtools it will manage to load all of the JS, and properly run the app, but still fail to load anything else.

None of this happens when I set up and build it on my Mac, and I haven't been able to test it on another Windows machine.

**To Reproduce**
See [repro branch in my repo](https://github.com/BeeeQueue/yuna-tauri/tree/not-working)

**Expected behavior**
The app should load normally.

**Platform and Versions (please complete the following information):**
```
Operating System - Windows_NT(10.0.19041) - win32/x64
Edge 83.0.478.61 (64-bit)

Node.js environment
  Node.js - 14.5.0
  tauri.js - 0.9.0

Rust environment
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.5

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/.git
/.idea
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.7.4
  mode - no-server
  build-type - bundle
  CSP -
  Windows - Edge
  distDir - ../dist
  devPath - http://localhost:4000
```

**Comment by nothingismagick** [comment]
Dang. We've been struggling with windows the past couple days. Can you post the results of `tauri info`

**Comment by beeequeue** [comment]
It's at the bottom of the OP.

**Comment by lucasfernog** [comment]
Will take a look at it this afternoon.

**Comment by nothingismagick** [comment]
Right, but it's not complete

**Comment by nothingismagick** [comment]
Specifically tauri.rs

**Comment by beeequeue** [comment]
Whoopsie... 😓

**Comment by nothingismagick** [comment]
Can you check if you are using the windows insider program? (I assume you are not - and hopefully this will not remain a requirement.) The thing that bothers me though, is the service worker error in your image. Can you turn the no-server mode off?

**Comment by beeequeue** [comment]
I am in the insider program for WSL2, did I miss something about it in the guide? I've tried to set Tauri up for both Windows and WSL but got stuck on having an X server and installing `appmenu-gtk3-module` (apt couldn't find it).

I've tried playing with the different recipes but they don't make a difference for me. 😢

**Comment by nothingismagick** [comment]
We just pushed a bunch of new releases. Can you please update your dependencies and confirm that the problem has been fixed?

**Comment by beeequeue** [comment]
I updated all the dependencies and pushed it, but it doesn't seem to have fixed the issue.

It seems like it uses the old Edge now, instead of the new Chromium one:
```
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.1.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.16.3
  tauri.js - 0.11.0

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.4
  yarn - 1.22.4

App directory structure
/.git
/.idea
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.9.0
  mode - no-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000
```

**Comment by dljsjr** [comment]
I'm seeing the same thing under `embedded-server` mode, using Powershell (no WSL/WSL2), and using a regular stable/consumer build of Win10 Pro (No Windows Insider):

`yarn tauri info` output:

```
PS C:\Developer\Personal\tauri-tester> yarn tauri info
yarn run v1.22.4
warning package.json: No license field
$ C:\Developer\Personal\tauri-tester\node_modules\.bin\tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.18363) - win32/x64
Microsoft Edge - 44.18362.449.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.13.0
  tauri.js - 0.11.0

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.12.0
  yarn - 1.22.4

App directory structure
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000
Done in 2.91s.
```

Repro conditions: I'm using the Vite Hello World app `yarn create vite-app <app name>` and then adding `tauri` to it using the manual setup setps (not the Vue CLI steps since the app is entirely Vite based).

1. `yarn create vite-app tauri-tester`
2. `cd tauri-tester`
3. `yarn add tauri`
4. `yarn tauri init`
    - set distDir to `"../dist"`
    - set devPath to `"http://localhost:3000"`
5. Run `yarn dev` in one terminal to start the Vite hello world
6. Run `yarn tauri dev` in another terminal

As @BeeeQueue mentioned, I *do* have the new Chromium-based version of Edge installed as well, if that matters.

EDIT: Also confirming that the exact steps above work just fine on macOS, just as @BeeeQueue noted as well.

**Comment by dljsjr** [comment]
Hey just wanted to add some more info here to see if it might help anyone:

I was able to get Tauri apps running on my Win10 setup by simply installing the [Evergreen Webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) runtime. It might be of interest to know that I'm on [a PC that is being held back from the May 2020 and Oct 2020 updates](https://support.microsoft.com/en-us/help/4592819/error-when-plugging-in-a-thunderbolt-nvme-ssd), but I also have the Chromium-based version of Edge installed. So I wonder if this issue is related to PC's that have the "optional" Chromium-based Edge installed but are on Win10 builds from before the promotion of the new Edge to the core browser?

**Comment by nothingismagick** [comment]
Yeah, I think that @dljsjr is right here, and this should absolutely be resolved with WRY. If it so happens that we continue to see problems here, then we should reopen this issue over at the WRY repo.
