### ISSUE TITLE
[bug] How do you dynamically observe files in a directory and log a new file as it appears

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#8141]
### Describe the bug

I'm new to rust, and the feature I want to implement is to watch the folder under "D:/ working directory /tools" and whenever a new file appears, return a line of text to the front-end textarea with id=log_content.

But my code is not doing my job correctly. It just outputs a log line when the program runs. How can I change that?
(The backend uses rust+tauri,Front-end html+css+js)
The code is as follows：

1.The get_log function:
![fc5adf596534e7d6c418912eb40ac95](https://github.com/tauri-apps/tauri/assets/109945614/ff6ab3b8-89e5-4d01-b9bc-7b2f4d09b5ac)
2.discoroboy.html:
![93882b905c08863f927fb402fec5cce](https://github.com/tauri-apps/tauri/assets/109945614/d3632948-cf88-444a-94d5-f486559f3325)

Or is there another function I can use to listen to a directory and display a message to textarea as soon as there are new files?

### Platform and versions

```text
[package]
name = "tauri-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
encoding_rs='0.8.33'
tauri = { version = "1.4.0", features = ["fs-all", "http-all", "shell-open", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = {version = "0.11",features = ["json"] }
tokio = {version = "1",  features = ["full"] }
diesel = {version = "2.0.3", features = ["sqlite"] }
xml-rs = { version = "0.8.4"}
chrono = "0.4"
notify = "6.1.0"
hotwatch = "0.5.0"
tracing = "0.1"
log="0.4.19"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
```

**Comment by FabianLars** [comment]
So, instead of using println in the watcher (in `match res`) you can use [tauri events](https://tauri.app/v1/guides/features/events/) to send the path to the frontend. You of course have to also _listen_ to them on the js side (shown in the linked guide) and then update the textarea from that.

**Comment by Tek-Ce** [comment]
On 30 Oct 2023 5:58 pm, Rookie ***@***.***> wrote:
Describe the bug
I'm new to rust, and the feature I want to implement is to watch the folder under "D:/ working directory /tools" and whenever a new file appears, return a line of text to the front-end textarea with id=log_content.
But my code is not doing my job correctly. It just outputs a log line when the program runs. How can I change that?
(The backend uses rust+tauri,Front-end html+css+js)
The code is as follows：
1.The get_log function:

2.discoroboy.html:

Or is there another function I can use to listen to a directory and display a message to textarea as soon as there are new files?
Reproduction
No response
Expected behavior
No response
Platform and versions
[package]
name = "tauri-app"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

[dependencies]
encoding_rs='0.8.33'
tauri = { version = "1.4.0", features = ["fs-all", "http-all", "shell-open", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = {version = "0.11",features = ["json"] }
tokio = {version = "1",  features = ["full"] }
diesel = {version = "2.0.3", features = ["sqlite"] }
xml-rs = { version = "0.8.4"}
chrono = "0.4"
notify = "6.1.0"
hotwatch = "0.5.0"
tracing = "0.1"
log="0.4.19"
[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

Stack trace
No response
Additional context
No response

**Comment by trookie2000** [comment]
![image](https://github.com/w3c/mediacapture-screen-share/assets/109945614/540e0cfc-b8ba-4285-b2cf-a200f2986bcd)

**Comment by trookie2000** [comment]
> So, instead of using println in the watcher (in `match res`) you can use [tauri events](https://tauri.app/v1/guides/features/events/) to send the path to the frontend. You of course have to also _listen_ to them on the js side (shown in the linked guide) and then update the textarea from that.

how to use tauri events to send the path to the frontend.？

**Comment by trookie2000** [comment]
> So, instead of using println in the watcher (in `match res`) you can use [tauri events](https://tauri.app/v1/guides/features/events/) to send the path to the frontend. You of course have to also _listen_ to them on the js side (shown in the linked guide) and then update the textarea from that.

How can I use tauri events to send the path to the frontend so that I can listen for changes in the path in real time？

**Comment by FabianLars** [comment]
You really just have to replace that println line with a call to `emit` as shown in the guide. Here's an example from our fs-watch plugin: https://github.com/tauri-apps/plugins-workspace/blob/v1/plugins/fs-watch/src/lib.rs#L53
