### ISSUE TITLE
[bug] tauri init using bun run on Raspberry Pi 4 8GB causes terminal bug

### ISSUE THREAD

**Issue by dominus10** [tauri-apps/tauri#8445]
### tauri init terminal bug on Bun
After installing Tauri as dev dependency, initializing the tauri init with Bun cause the terminal to have input bug.

Device: Raspberry Pi 4 8GB
OS: Ubuntu 23.10 (Mantic)

### Reproduction

1. Install Bun [ `$ curl -fsSL https://bun.sh/install | bash` ]
2. Init new app ( in this case React + Vite) [ `$ bun create vite@latest` ] -> React -> Typescript + SWC
3. Install tauri as dev dependency [ `$ bun install --save-dev @tauri-apps/cli` ]
4. Initiate tauri app [ `$ bun run tauri  init` ] 

### Expected behavior

![image](https://github.com/tauri-apps/tauri/assets/38601700/2c418c05-79fc-418b-9e92-ac0319f93348)

### Full `tauri info` output

```text
ubuntu@ubuntu:~/dev/app-fe$ bun run tauri info
$ tauri info
ubuntu@ubuntu:~/dev/app-fe$
```

### Stack trace

```text
-
```

**Comment by ggemre** [comment]
The reason for this is how node.js and bun handle asynchronous functions at root-level differently.

In [tauri.js](https://github.com/tauri-apps/tauri/blob/45384ab3aa44687f25323ebf367058270ec3a4d3/tooling/cli/node/tauri.js#L54) of the cli:

```js
cli.run(args, binName).catch((err) => {
  cli.logError(err.message)
  process.exit(1)
})
```

`cli.run()` returns a Promise. The function is called from the root level in the `tauri.js` file, which in node.js will run to completion, (catching any errors in a catch block). With bun, my guess is that its promise handling is structured differently, so when running `cli.run()` without `await` or `.then` leads to nothing actually resolving.

[This issue](https://github.com/oven-sh/bun/issues/9117) in the bun repo seems to describe the same problem you are having, so the bug is within bun, not tauri. From the issue conversation:

> what is happening is somewhere in this line of async work, bun does not realize there are active operations happening, so it quits thinking the async work is done.
>
> the await prevents the main file from finish running before that.
>
> this is still a bug its just not immediatly clear what part of the async chain is forgetting to keep the event loop alive.

Unfortunately, bun has thousands of issues open at the time of this writing, so a resolution may not be timely. 

If the tauri team wants to provide some kind of explicit asynchronous indication to allow bun support, I would be happy to open a PR for this, so long as it does not also break things for node.js. If not, bun may not be the ideal engine for tauri.
^ @lucasfernog
