### ISSUE TITLE
[bug] 卸载软件时点击清除软件数据会将整个父级目录删除

### ISSUE THREAD

**Issue by zenitsu97** [tauri-apps/tauri#8469]
### Describe the bug

高危！卸载软件时点击清除软件数据会将整个父级目录删除

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.91
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.12.1
    - pnpm: 8.6.2
    - yarn: 1.22.19
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.2 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.5.8 (outdated, latest: 1.5.9)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

打包方式：wix311 + nsis-3
默认配置

**Comment by FabianLars** [comment]
Hi, thanks for the report. Just to clarify, do you mean that if you installed your app into this path:
```
C:/Users/username/AppData/Local/appname/
```
Will it delete the whole `appname/` folder or `Local/` too?

Maybe it's a bad example because `Local` is protected so i assume you're choosing a custom path.

To be clear, deleting the whole app installation folder is expected since that's one of the application data folders. Deleting its parent folder (in my example `Local/`) would of course be a major bug we'd have to fix asap but i couldn't see this behavior in my own tests.

**Comment by zenitsu97** [comment]
感谢您的回复，我在安装应用程序时没有创建tauri单独使用的文件夹例如`C:/Users/username/example/appname`，而是直接安装`C:/Users/username/example`中，从而导致卸载时对`example/`目录的删除，这并非一个程序上的BUG。
