### ISSUE TITLE
[bug] Panic in tauri-runtime-wry 0.14.3 during init on wayland

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#8515]
### Describe the bug

On wayland starting the app crashes with following:
```
thread 'main' panicked at /run/build/TrguiNG/cargo/vendor/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55: called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"
```

This is caused by switching to arboard in 0d0501cb7b5e767c51a3697a148acfe84211a7ad

To work properly on wayland it needs "wayland-data-control" feature enabled.

See similar issues in other apps: 
https://github.com/1Password/arboard/issues/98
https://github.com/YaLTeR/wl-clipboard-rs/issues/32

### Reproduction

Attempt to run a demo app under wayland. Possibly only reproducible in flatpak environment or when xwayland is not available.

The error above is from this app: https://flathub.org/apps/org.openscopeproject.TrguiNG

### Expected behavior

App starts without crash

### Full `tauri info` output

```text
[✔] Environment
    - OS: Debian 12 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.10.0
    - npm: 10.2.3
 
[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9
 
[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:8080/
    - framework: React
    - bundler: Webpack
```

**Comment by qu1ck** [comment]
Why are crashes not prioritized? Another issue with tauri crashing has been open for months with 0 engagement
https://github.com/tauri-apps/tauri/issues/7566

It does not look good if you don't care about issues that completely break apps built with your framework on supposedly supported platforms.

**Comment by FabianLars** [comment]
> Why are crashes not prioritized?

Full transparency: Because we're only 3 (active) devs with very very few outside contributions and we made the mistake to hype up mobile for v2 way too early and now with the audits ramping up we have to focus on getting the last big api changes done asap for the auditors...

Once tauri v2 is in a freeze for the audit we will focus more on bugs and docs, including v1 issues. We also hope that the huge refactors in v2 will make it easier for interested people to contribute. And we also have plans to make contributing a more guided experience and just easier, but that again needs time.

----

To talk about your specific issues here.

This one here has an open PR where we're waiting for the contributor to follow up on our feedback so we can merge it.

The one you linked is probably not as high of a prio as other breaking bugs because it's easy to work around by just not giving it an empty path (on the other hand this of course also means it would be easy to fix in Tauri so it's not a _good_ excuse).

----

I hope this clears it up a bit and believe me, we are at least as frustrated as you are :/

**Comment by qu1ck** [comment]
Thanks for the transparency.

Only thing I would add is for the future probably it would make sense to make some policy around being very cautious and defensive around unsafe code and use of `unwrap()` and such as that seems to be the common cause.

**Comment by FabianLars** [comment]
The unwrap part i totally agree with, the bare minimum would be to convert them to expect calls though of course, not panicking is better...
The unsafe code thing is tricky. It's unfortunately part of FFI heavy code bases like ours. We could maybe abstract it better but that probably wouldn't help with bugs like these, especially when it's not even happening in our own code but in a dependecy.

**Comment by qu1ck** [comment]
Any ETA on when this will be in v1 patch release?
