### ISSUE TITLE
[feat]  Add a shortcut to uninstall

### ISSUE THREAD

**Issue by 107295472** [tauri-apps/tauri#8523]
### Describe the problem

nsis,Now there is only one application shortcut in the start menu

### Describe the solution you'd like

tauri Bundle

**Comment by amrbashir** [comment]
I don't know if we want to add this feature, since most applications (at least the one I use) stopped shipping a shortcut for the uninstaller which is better IMO as it doesn't pollute the start menu.

I will still keep this issue open and see if more users desire this feature.

BTW, you can still access the uninstaller relatively easy by double clicking the app icon and selecting uninstall.
