### ISSUE TITLE
[feat] export FileResponse

### ISSUE THREAD

**Issue by Sahasrara** [tauri-apps/tauri#8555]
### Describe the problem

Would it be possible to export the FileResponse interface?

### Describe the solution you'd like

I'd just like to be able to access type information for the FileResponse interface. I figured exporting it would be pretty simple.

**Comment by FabianLars** [comment]
Duplicate of https://github.com/tauri-apps/plugins-workspace/issues/835, fixed in https://github.com/tauri-apps/plugins-workspace/pull/837. If you update the `@tauri-apps/plugin-dialog` package to the latest version you should have access to it.

(Or do we use the same interface somewhere else outside the dialog plugin? Couldn't find it anywhere.)
