### ISSUE TITLE
Where are cookies and localstorage data stored

### ISSUE THREAD

**Issue by pokecheater** [tauri-apps/tauri#8635]
Hey Tauri-Team :),

Since this feature https://github.com/tauri-apps/wry/issues/518 has not been implemented for almost 2 years since the first request, I need a workaround for this. If I can access the cookie storage by myself inside the rust backend everything would be fine, but, inside the docs, I can't find out where they are stored.

I tried to find it out with the following code snippet:

```javascript
import { appDataDir, dataDir, localDataDir } from '@tauri-apps/api/path';
const appDataDirPath = await appDataDir();
console.log("appDataDirPath", appDataDirPath);
```

and  it states:
[Log] appDataDirPath – "/Users/c3po/Library/Application Support/XXX-app/"

but that path does not exist.

I tried to set a custom data_directory as proposed in https://github.com/tauri-apps/wry/issues/518 but that does not work either since the path gets created but remains empty all the time:

```javascript
tauri::Builder::default()
        .setup(|app| {
            let path_str = "/Users/c3po/session_data/cookies";
            let data_directory: PathBuf = PathBuf::from(path_str);
            let path_string: String = data_directory.to_string_lossy().to_string();
            let window = tauri::WindowBuilder::new(app, "label", tauri::WindowUrl::App("index.html".into()))
            .data_directory(data_directory)
            .build()?;

            // let cookies = std::fs::read_to_string(path_string).expect("could not read cookies");
            // println!("{cookies}");
            Ok(())
        }) 
```

Can anyone help me here out?
Thx in advance <3.

**Comment by FabianLars** [comment]
`/Users/c3po` means you're on macos right? We can't control the data dir on macos so that's probably why it's empty, though i would have expected that i won't be created at all.
macos/wkwebview will store its data in /Users/c3po/Library/WebKit/<bundle-id>/` (or appname instead of bundleid in `tauri dev` mode). Though i'm not sure what format(s) it uses. On Linux for example cookies are stored as plain text, on Windows it's an sqlite database.
There's also `/Users/c3po/Library/Cookies/` but i think the webview ones are not part of that, not sure 🤔
