### ISSUE TITLE
[bug] tauri resource directory is hard-coded

### ISSUE THREAD

**Issue by nyabinary** [tauri-apps/tauri#8679]
### Describe the bug

Tauri resource directory location is hard-coded making Tauri fail when it can't read or write from it, this is especially a problem in immutable distros like NixOS.

### Reproduction

https://github.com/NixOS/nixpkgs/pull/265771 - build this without the tauri patch in it.

### Expected behavior

For it to succeed in building.

### Full `tauri info` output

```text
N/A
```

### Additional context

There is a fix in the Github pr I linked in the files it's called [tauri-env-resource-dir.patch](https://github.com/NixOS/nixpkgs/blob/728e957b03d9194b7d277907cb1bc154081cf35a/pkgs/by-name/do/dorion/tauri-env-resource-dir.patch)

**Comment by FabianLars** [comment]
To be honest i am super confused, probably because i have no nix(os) experience.
Are you saying that rust's `target/` folder is read-only in nixos? How can the app itself be compiled then?

Do you have any error logs from before the patch was applied?

**Comment by lilyinstarlight** [comment]
Hi there! I actually wrote that patch. Basically the issue is that `/usr` does not exist and packages are built into and later run from an immutable directory like `/nix/store/[hash]-name` with exe installed to `/nix/store/[hash]-name/bin/exe` and resources installed to `/nix/store/[hash]-name/lib/cargo_name`

The assumptions in this code snippet do not hold for that layout because it assumes either `/usr` exists, `$APPDIR` is set in the environment, or that the path ends in `/data/usr/bin`: https://github.com/tauri-apps/tauri/blob/d70470f868511adb551afcd17acade6dd08b14da/core/tauri-utils/src/platform.rs#L253-L275

The [patch linked above](https://github.com/NixOS/nixpkgs/blob/728e957b03d9194b7d277907cb1bc154081cf35a/pkgs/by-name/do/dorion/tauri-env-resource-dir.patch) basically adds an escape hatch so that any downstream which conforms to a filesystem hierarchy that is not one of those 3 options can use to override the resource directory (which that need is not Nix-specific and would occur elsewhere as well, like with AppImages which already had to be hardcoded)

Alternatively, if the code path could try to use `exe_dir.join(format!("../lib/{}", package_info.package_name()))` regardless of the path ending in `/data/usr/bin` or the existence of `/usr` (either as a fallback or as an initial check), that would also work for our and I imagine most any other downstreams

Thank you for the prompt response!

> Are you saying that rust's target/ folder is read-only in nixos? How can the app itself be compiled then?

Also just to be clear, this doesn't have to do with it. The target directory gets written to just fine, but when it does `cargo install` it gets put not in `/usr` and that is the part that Tauri trips up on

**Comment by nyabinary** [comment]
> To be honest i am super confused, probably because i have no nix(os) experience. Are you saying that rust's `target/` folder is read-only in nixos? How can the app itself be compiled then?
> 
> Do you have any error logs from before the patch was applied?

This should be an easy fix right?

**Comment by nyabinary** [comment]
Bump :P
