### ISSUE TITLE
Can't scrub on local HTML5 video on Windows

### ISSUE THREAD

**Issue by janek** [tauri-apps/tauri#8725]
When I try to scrub (move playback indictator to jump to another place in the video) it doesn't work, instead jumping back to where I was. I'm on Windows, using vanilla HTML/JS.

Additional things I've noted:
- It only breaks when playing a local file, the same file streamed from a remote server works fine
- I've tested the raw video element and 4 different HTML5 video players ([Plyr](https://plyr.io/), [MediaElement](https://www.mediaelementjs.com/), [Playerjs](https://playerjs.com/), [VideoJS](https://videojs.com/)) and got the same behaviour on all of them
- I've tested `.webm` and `.mp4` and got the same
- I've tested opening the html file directly Firefox and Edge, as well as serving with a local python server, and all seems to work. At one point I thought I'd reproduced the problem Edge, but I can't get a reproduction now.

I'm not sure if it's an issue with Tauri itself and so I'm not reporting it as a bug. I'm nevertheless including `tauri info` and a way to reproduce below. I have a vague suspicion it might be something with WebView2 (maybe related: [Working with local content in WebView2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=dotnetcsharp)).

I'd be thankful for any tips on how to solve/work around this, or what it might be related to.

<details>
    <summary>tauri info output</summary>
  

> [✔] Environment
>     - OS: Windows 10.0.19045 X64
>     ✔ WebView2: 120.0.2210.144
>     ✔ MSVC: 
>         - Visual Studio Build Tools 2022
>         - Visual Studio Community 2022
>     ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
>     ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
>     ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
>     ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
>     - node: 20.10.0
>     - yarn: 1.22.19
>     - npm: 10.2.3
> 
> [-] Packages
>     - tauri [RUST]: 1.5.4
>     - tauri-build [RUST]: 1.5.1
>     - wry [RUST]: 0.24.7
>     - tao [RUST]: 0.16.7
>     - @tauri-apps/api : not installed!
>     - @tauri-apps/cli [NPM]: 1.5.9
> 
> [-] App
>     - build-type: bundle
>     - CSP: unset
>     - distDir: ../src
>     - devPath: ../src

</details>

<details>
    <summary>Reproduction steps</summary>

-     
    - create a new vanilla JS Tauri app on Windows
    - include code that plays HTML5 video from a local file. Code I used is here: https://codesandbox.io/p/sandbox/video-scrub-test-rk455m. You'd have to copy the code and the video file.
    - as a sanity check, open the file in a browser and make sure the video plays/videos play
    - run dev or build the tauri app, play a video, try to jump to a place in a video that's playing back locally
    - the video will not jump to desired timestamp/location, instead will jump back to where you were and continue playing 

</details>

**Comment by FabianLars** [comment]
Hi, thanks for the report. Did you also try using the asset protocol via https://tauri.app/v1/api/js/tauri/#convertfilesrc as the video source?
Just wanting to check if it handles it any better so we can look at their differences.

**Comment by janek** [comment]
Hi, thank you for answering so quickly. I didn't know about the asset protocol, I tried it now and worked perfectly. I just  struggled with getting my files to be included as assets, but got it to work eventually. I'm leaving it up to you if you want to close the issue.

**Comment by amrbashir** [comment]
is there any reason to include the video in your web assets? seems counter-intuitive and will just increase your bundle size.

A few solutions:
1. include the video as a resource https://tauri.app/v1/guides/building/resources/
2. download the video at runtime

and either way use `convertFileSrc` and the asset protocol to play it.

**Comment by janek** [comment]
I have a requirement of the app being fully offline, so everything has to be included on installation. I am including the videos as a resource + `convertFileSrc`, I just used the wrong word in my previous comment ("assets" instead of "resources").

Thank you for your help!

**Comment by BlueManCZ** [comment]
Sorry for bumping this, but I encountered the same problem and didn't really find a relevant documentation for setuping this correctly, so I want to document this for the future me or anybody else searching for this.

#### 1. Move your video files from `/static/videos/` to `/src-tauri/videos/`
We need to move our videos out of the static folder, because all files from static folder are included in the binary and we don't really want that. We will handle videos as resources instead.

#### 2. Configure resources and asset protocol in `tauri.conf.json`
- Add videos as [resources](https://v2.tauri.app/develop/resources/) in the `bundle.resources`, so they are included in the bundle like `.msi`, but not the actual binary `.exe`.
- Enable the [asset protocol](https://v2.tauri.app/reference/config/#assetprotocol), set the scope to [`$RESOURCE/**`](https://docs.rs/tauri/latest/tauri/path/struct.PathResolver.html#method.resource_dir) and update [csp](https://v2.tauri.app/security/csp/) value accordingly:

```json
{
  "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
  ...
  "bundle": {
    "active": true,
    "targets": ["msi"],
    "icon": [
        ...
    ],
    "resources": [
      "videos/**/*"
    ]
  }
  "app": {
    "windows": [
      ...
    ],
    "security": {
      "assetProtocol": {
        "enable": true,
        "scope": [
          "$RESOURCE/**"
        ]
      },
      "csp": "default-src 'self' ipc: http://ipc.localhost; media-src 'self' asset: http://asset.localhost;",
    }
  },
}
```

#### 3. Update video source `src` attributes in client

Insted of using path for static files like previous `<source src="/videos/example.mp4" type="video/mp4" />`, we will now generate the path to resources combining [resolveResource](https://tauri.app/reference/javascript/api/namespacepath/#resolveresource) and [convertFileSrc](https://v2.tauri.app/reference/javascript/api/namespacecore/#convertfilesrc) together. So in React or Svelte it could look like this:

```jsx
<video controls>
    <source
        src={convertFileSrc(await resolveResource(await join("videos", "example.mp4")))}
        type="video/mp4"
    />
</video>
```

<hr>

https://github.com/tauri-apps/tauri/discussions/12667
https://github.com/tauri-apps/tauri/discussions/14060
