### ISSUE TITLE
[feat] Split bundle and build steps in tauri cli

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#8734]
### Describe the problem

Please split the bundling and building commands in `tauri-cli` into two steps so it will be more flexible.
I saw that you have `beforeBundleCommand` but I think that it's better to split them complely,
even the `beforeBuild` 

Or at least provide a way to execute only single step

### Describe the solution you'd like

.

### Alternatives considered

.

**Comment by jacobgorm** [comment]
I agree, this should be two steps, because

- in docker builds, it is very slow to debug bundling problems, because you cannot cache the result of the rest of the build
- the signing step should be done separately and ideally in an airgapped environment, and only by completely trusted tools like signtool.exe, to avoid supply chain attacks from crates.io.
