### ISSUE TITLE
Does tauri not support macos 10.14?  [docs] 

### ISSUE THREAD

**Issue by yuanhaotian** [tauri-apps/tauri#8972]

**Comment by FabianLars** [comment]
Officially we support 10.15 and up because Apple supported that one for longer then previous 10.X versions. The actual hard requirement is 10.13 which introduced apis we require. So yes, 10.14 should work. It's not actively tested though, so take this with a grain of salt.

Also, on macos specifically, features tend to be bound to the macos version, for example printing from inside the webview only works in 11 and up.

Lastly, many tools seem to be dropping support for 10.x versions lately (similar to how they're dropping support for windows 7), so developing **on** macos 10.x may be/get tricky.
