### ISSUE TITLE
[bug] Tauri v2.0.0-beta failed to build on Windows

### ISSUE THREAD

**Issue by A-kirami** [tauri-apps/tauri#9045]
### Describe the bug

I recently migrated to v2, but encountered some issues. I am not sure if this issue should be raised here, but I think it may be related.
When I use github actions, it fails to build on Windows.
This may be related to my use of caching, as when I delete the cache, it can be successfully built.
But why?
This is a bit strange because there was no such issue in v1.

### Reproduction

https://github.com/A-kirami/tauri-windows-build

https://github.com/A-kirami/tauri-windows-build/actions/runs/8108131093/job/22160785334

### Expected behavior

It should be built successfully on Windows like v1.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.20348 X64
    ✔ WebView2: 119.0.2151.58
    ✔ MSVC: Visual Studio Enterprise 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.1
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

```text
error: failed to run custom build command for `tauri-app v0.0.0 (D:\a\tauri-windows-build\tauri-windows-build\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\a\tauri-windows-build\tauri-windows-build\src-tauri\target\release\build\tauri-app-24127a8263a01426\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_PREFIX=com_tauri
  failed to read plugin permissions: failed to read file: The system cannot find the file specified. (os error 2)
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.
Error: Command failed with exit code 1: pnpm tauri build -t x86_64-pc-windows-msvc
```

**Comment by amrbashir** [comment]
can you try removing `tauri-plugin-shell` from `Cargo.toml` and try again?

**Comment by A-kirami** [comment]
> can you try removing `tauri-plugin-shell` from `Cargo.toml` and try again?

The same result.

https://github.com/A-kirami/tauri-windows-build/actions/runs/8146043409/job/22263664310

**Comment by amrbashir** [comment]
I have no idea why this is not working, cloning the same repo and building it on my machine works just fine.

Here is a couple of things to try:
1. remove the use of cache in CI just to rule out that it is not a cache issue
2. try building without tauri-action and use `pnpm tauri build -t <target>` instead
3. if that doesn't work try without `-t` flag

**Comment by vasfvitor** [comment]
I guess I was having the same issue, with `yarn`. 

```console

Compiling testeapp v0.1.0 (D:\a\tauri-ci-test\tauri-ci-test\apps\my_tauri_app\src-tauri)
error: failed to run custom build command for `testeapp v0.1.0 (D:\a\tauri-ci-test\tauri-ci-test\apps\my_tauri_app\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\a\tauri-ci-test\tauri-ci-test\apps\my_tauri_app\src-tauri\target\release\build\testeapp-e05d03921a11ecee\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_PREFIX=com_teste
  failed to read plugin permissions: failed to read file: The system cannot find the file specified. (os error 2)
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
Error: Command failed with exit code 1: yarn tauri build

```
Building locally works, no cache involved.
Without cache, it builds.
With tauri-action `args: -v -d` also builds but doesn't solve the issue. 
With tauri-action `args: -t x86_64-pc-windows-msvc` it builds and solved for me as I'm targeting only Windows. Thanks for it @amrbashir, while you suggested to do it without tauri-action, I utilized the action anyway.

**Comment by FabianLars** [comment]
Using the target flag is basically the same as a cache reset because the flag changes the target dir.

So the question (I raised on discord iirc?) whether a single reset is enough or if it comes back, remains. So far I've not heard from it reappearing so I assume it's just an incompatibility with files from prior beta versions maybe?

**Comment by vasfvitor** [comment]
I've tried multiple times by cleaning the cache to be sure the issue was the caching. The way it was build with the `-t` flag it did hit cache, building time dropped 3min (not great imo). The cache hit was from a successful build without the flag. 

Lastly, I did not upgraded to v2, the project was born v2. So maybe a different issue?

Note: the project is Windows only.

**Comment by FabianLars** [comment]
The only part of the cache that could apply here is the global .cargo dir that holds the downloaded crates but 3 minutes is a bit much.
The -t flag changes the target dir from `target/release/` to `target/<target-flag>/release/` so nothing of the prior stuff should be re-used.

> Lastly, I did not upgraded to v2, the project was born v2. So maybe a different issue?

I was mainly thinking about the alpha to beta (or beta to beta) changes like the new ACL stuff since it talks about plugin permissions that were introduced in beta.

----

So if you're saying that without the -t flag it fails reliably even after clearing the cache then maybe something in tauri resolves the paths incorrectly without the -t flag? Weird that so far it only happened in CI though

**Comment by vasfvitor** [comment]
>So if you're saying that without the -t flag it fails reliably even after clearing the cache 

Yeah, but don't take this as a scientific testing, I've done many tests that I lost track. But I'm more than 80% sure, if I could gauge

The only thing that worked so far was the -t flag with "cache-all-crates: true" (just tried without it and didn't worked). Cache action is "swatinem/rust-cache@v2"

The build step doesn't download anything, it goes to compiling. Not sure how this would behave in a ideal scenario.

**Comment by venkr** [comment]
We're running into this issue too. It doesn't occur on macOS (the other platform we build for), but only occurs on Windows. Also it's stochastic, and has definitely sent us on some false paths due to occasionally building, but not always building.

Our initial tests are not consistent with it being a caching issue: we've seen it succeed multiple times with tweaks that shouldn't change the Rust cache. 

The characteristic error message we get is:

> failed to read plugin permissions: failed to read file: The system cannot find the file specified. (os error 2)
> warning: build failed, waiting for other jobs to finish...
>       Error failed to build app: failed to build app

I'm trying out `-t x86_64-pc-windows-msvc` as recommended, and will test it ~3 or so times and let you know what I find.

**Comment by venkr** [comment]
I'm back with results, tested `-t x86_64-pc-windows-msvc` as recommended, and I've seen no issues in 7 re-runs of the build, without any changes to caching.

Looks like adding a target somehow makes a difference?

**Comment by Ajayghoshm** [comment]
still not resolved?
how to resolve this issue?

**Comment by lars-berger** [comment]
> I'm back with results, tested `-t x86_64-pc-windows-msvc` as recommended, and I've seen no issues in 7 re-runs of the build, without any changes to caching.
> 
> Looks like adding a target somehow makes a difference?

Unfortunately running into the same error despite defining an explicit target. [Ref to failed GA run](https://github.com/glzr-io/zebar/actions/runs/8221612715/job/22482170240?pr=36)

**Comment by venkr** [comment]
Alright yeah, we also just ran into our first CI error despite an explicit target.

We've temporarily merged a change that disables our cache on Windows. That makes the build green again, but again, since it's flaky, it's hard to tell. I'll check back in if that breaks too. 

FWIW: This kinda sucks since it takes build times from 6 minutes to 19 minutes.

**Comment by S1lander** [comment]
For me, what fixed it was deleting the `scr-tauri/target/debug/build` folder and then running `npm run tauri dev` again. Once I did that I also noticed that my antivirus put some of the files in quarantine, so I had to put that folder on the whitelist.

**Comment by ImUrX** [comment]
is this error maybe an issue of softlinks? How does tauri read the permissions file in windows

**Comment by skyf0l** [comment]
Same using `Swatinem/rust-cache@v2`, I solved it by clearing the cache

**Comment by thewh1teagle** [comment]
Same, fixed by deleting all cache from `https://github.com/<User>/<Repo>/actions/caches`

**Comment by aispin** [comment]
> For me, what fixed it was deleting the `scr-tauri/target/debug/build` folder and then running `npm run tauri dev` again. Once I did that I also noticed that my antivirus put some of the files in quarantine, so I had to put that folder on the whitelist.

Works, thanks!

**Comment by happybeing** [comment]
Just hit this on Ubuntu 24 while migrating a Tauri v1 app to v2 beta and this also worked for me:

> For me, what fixed it was deleting the scr-tauri/target/debug/build folder

**Comment by TreltaSev** [comment]
On Windows, while getting the exact same error, the fix for me was uninstalling the 64x-bit version of Rust and installing the 32x-bit version instead. I'm not sure why that fixed it though.

**Comment by BranikSWG** [comment]
Just encountered this on Ubuntu 22 on an app I just started building using tauri 2 rc 11. It was working, closed it. went to restart it a few minutes later (no changes made) and it wouldn't restart until I deleted the debug/build folder.

**Comment by GrvExplorer** [comment]
My fix to this problem is to **delete target** and add **"capabilities": [],** to default.json
