### ISSUE TITLE
[feat] reduce the amount of branches

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#9189]
### Describe the problem

Please keep it simple the amount of branches in this repo and on other tauri repos.

I understand it would be better to contain: 1.the MAIN branch, 2. the DEV/2.0 beta branch, 3. branches for individual new features being developed outside the 2.0 branch, not merged yet, and 4. branches for major and minor past versions.

Branches for patch versions, like 1.0.1, or branches for RC/beta versions could be removed.

There are some stale branches, branches that seem to have been merged.

The same applies to tags: some very old branches that are not maintained anymore, like beta and rec versions, I suspect if they are useful at all. The list starts to get very big. There is no problem at all releasing many versions, so maybe only the latest version in any minor version is useful to keep listed. For example, the latest 1.5.x version, the latest 1.4.x versions.  Things that can be worked upon.

I am finding it unnecessarily confuse and unordered at the time.

### Describe the solution you'd like

This solution is not focused on erasing history. Is just to value if regarding open branches and tags, the relevance of keeping many patch/rc/beta versions.
We could keep only the latest minor versions, the main, the dev, and other features being worked.

### Alternatives considered

The full list of alpha and beta and such branches/versions could be listed in a blog page instead of being listed on GitHub repos.

### Additional context

Your repos (not only Tauri) start to get convoluted. Let's take care of the garden✂️ to grow healthier, focused🎶

**Comment by ghost** [comment]
Ah I just remembered that GitHub also has an option to close branches automatically as they get merged.
Maybe you already know, just noting and bringing to topic to help the conversation.👍

**Comment by FabianLars** [comment]
> I understand it would be better to contain: 1.the MAIN branch, 2. the DEV/2.0 beta branch, 3. branches for individual new features being developed outside the 2.0 branch, not merged yet, and 4. branches for major and minor past versions.

This is pretty much how we do it already, just that main and dev is the same is the same branch.

> Branches for patch versions, like 1.0.1, or branches for RC/beta versions could be removed.

As far as i can see we don't have those, unless you mean the wry 0.24.1 branch which is actually 0.24.x but renaming it now may break someone's project so that's not worth it imo.

> There are some stale branches, branches that seem to have been merged.

Can't see any of them being merged. They either have open PRs or never got a PR at all. 
I agree though that we should go through the stale branchess and check if there's anything valuable we may wanna get up to speed again and merge or remove if not.

> The same applies to tags: some very old branches that are not maintained anymore, like beta and rec versions, I suspect if they are useful at all. The list starts to get very big. There is no problem at all releasing many versions, so maybe only the latest version in any minor version is useful to keep listed. For example, the latest 1.5.x version, the latest 1.4.x versions. Things that can be worked upon.

I don't think this is how git tags work. They are just a versioning mechanism and aren't supposed to be updated. For me this would be the same as removing a version from the npm registry and uploading the same version to it again (not actually possible, i know).
Super old tags are probably indeed not used, but it'd be still weird to remove them imo, there _may_ be some super old project actually using it, who knows 🤷 

Edit: Also, this would probably break the github releases.

> Ah I just remembered that GitHub also has an option to close branches automatically as they get merged.
Maybe you already know, just noting and bringing to topic to help the conversation.👍

We have that enabled, otherwise we'd probably have 1000 open and not just 50.

**Comment by ghost** [comment]
Thank you Fabian. I appreciate your fast and detailed response.

Okay, now I understand some reasons for tags to remain as they are. This is actually almost irrelevant for me (tags for old versions), but I am just going to expand my previous thought, in hope to foster the discussion:   considering that:
- the current main version is 1.5.x,
- the previous main stopped in 1.4.0, 1.3.1, 1.2.3,
- and the current beta is in 2.0.x,
In this scenario, I don't see a problem at all in breaking old projects by removing any branch or tag that refers to: 1.3.0, 1.2.0, 1.2.1 and 1.2.2. You see, I proposed just to keep branches and/or tags for the latest minor version available. This would be seen as an incentive for old projects to update their versions, without promoting breaks in the pipeline, considering that patch versions don't break functioning.
If this is not possible to do, or if cons are bigger than the benefits, it is okay.

I can be more descriptive regarding what I found confusing in the first place and that may be object of possible improvement.
Here in tauri repo, I find it confusing to see the "latest" and "next" listed as branches, while not being actually the "latest" or "next". Do you know what I mean? It is unnecessarily confusing. The latest is actually the current "dev" branch. It is common to see "latest", "dev" and "next" referring to the same purpose in repositories of other people, so it is just a matter of avoiding these words together.

Also, I don't get the relevance of having the 1.x branch. I mean, it could be comprehensible, but this pattern is not being followed. Take it for example the latest version of your project, that is released on minor version 1.5, but there is no 1.5 branch available. There are available the 1.0, 1.1, 1.2, 1.3 branches, while not being available a branch for the 1.4 and 1.5 branches. What does 1.x mean in this context? A branch that contains 1.5 improvements? 1.6 improvements? I don't know!    Following that terminology, one person would imagine that it would exist an 2.0 branch, but that one also doesn't exist, probably because it is currently under the "dev" scope.

Some branches are prefixed with "chore/", "feat/" or with "fix/", which is clever to provide organization. Those ones seem to be related to open pull requests or issues. Once again, however, I don't understand why a few branches maintain no prefix at all. In which degree of importance and category would it be considered as part of, for example, the branches: "wix-deep-link", "wry-git", "runner-config", "parking_lot"?

In summary, when opening your github page, and trying to navigate on branches for different reasons, I find it difficult because those 2 main ways of organizing (1.1, 1.2, 1.3... and prefixes) have notable exceptions.

Considering that tags already cover the need of accessing old codebases, I would vote in favor of removing 1.1, 1.2, 1.3 branches, in order to keep only 1.5 and the dev.

--------------------

Now let's take a look in other repositories of tauri-apps.

plugins-workspace, for example.

The branches once again are named with prefixes, but some branches have no prefix at all. I don't understand if that means that one branch is more or less experimental, more or less important than the others, you know. "Uhh, if it is true to expect unprefixed branches, should i roll the entire list to search for keywords that are to be expected, like latest, dev or next? Or should I resort to prefix branches? What is this repo prioritizing?"

At the same time, branches related to version numbers also exist in the plugins-workspace: v1, v2, release-v2, and release.

Do you see how the format of versioning is different here? While on tauri it is 1.5.x, on plugins-workspace it contains a "v" before the number, with no reference to any minor version.

Also, it is not clear what is the difference between release-v2, release and v2. If v2 is not released yet, why does it exist release-v2? If release-v2 exists, does that mean that "release" refers to v1? What is more up-to-date: v1 or release-v1? Why does this repository prioritizes "v2" or "release-v2" instead of "dev"? Shouldn't the "release-v2" branch only exist when "v2" is actually released?

---

In tauri-docs, once again I see the "dev" branch mixed with "next" terminology. I suspect however that, in this case, "next" refers to the software, since there is also another branch named "astro-v4". However, as noted before, a branch named "next" could be confusing when down the list there is also a "dev" branch, because both can refer to the same meaning.

----

In tao repository, there is "dev", "v.22.x" and "v0.16". It may be clear to devs working on the project, but as a newcomer, I find it especially difficult to reason where is it located the current "0.26.1" version, the main. If they are following numbers with a "v" prefix, why isn't there a v0.26.x branch, you see? There are branches for 0.22 and 0.16. What about 0.25, 0.24 and the other in between? (Actually I am not a fan of a branch for each minor version, I just question why some branches have it while others and the main don't). Does the "dev" branch mean the same as "main" here?

-----

You see, it is already very well organized. It is just something still missing on your thinking model. A solution probably is going to be a terminology more consistently applied in all your repositories, in order to decrease the occurrences of exceptions.

Thank you again and I hope that my comment is valuable for you.

Gently

**Comment by FabianLars** [comment]
> Okay, now I understand some reasons for tags to remain as they are. This is actually almost irrelevant for me (tags for old versions), but I am just going to expand my previous thought, in hope to foster the discussion: considering that:
>
>  -  the current main version is 1.5.x,
>  -  the previous main stopped in 1.4.0, 1.3.1, 1.2.3,
>  -  and the current beta is in 2.0.x,
>  -  In this scenario, I don't see a problem at all in breaking old projects by removing any branch or tag that refers to: 1.3.0, 1.2.0, >1.2.1 and 1.2.2. You see, I proposed just to keep branches and/or tags for the latest minor version available. This would be seen as >an incentive for old projects to update their versions, without promoting breaks in the pipeline, considering that patch versions >don't break functioning.
>    If this is not possible to do, or if cons are bigger than the benefits, it is okay.

_Personally_ i agree with that sentiment, it's just not how git tags work so we have to live with it, at least for the stable releases (i think it's fine to delete the super old alpha tags).

> Also, I don't get the relevance of having the 1.x branch. I mean, it could be comprehensible, but this pattern is not being followed. Take it for example the latest version of your project, that is released on minor version 1.5, but there is no 1.5 branch available. There are available the 1.0, 1.1, 1.2, 1.3 branches, while not being available a branch for the 1.4 and 1.5 branches. What does 1.x mean in this context? A branch that contains 1.5 improvements? 1.6 improvements? I don't know! Following that terminology, one person would imagine that it would exist an 2.0 branch, but that one also doesn't exist, probably because it is currently under the "dev" scope.

Also completely agree. 1.x is the dev branch for v1. 1.0 1.1 etc were used to publish security fixes to those versions. Since there were no such releases for 1.4 and 1.5 those branches were not created. For consistency's sake i agree that those should have been created. I'd imagine that those branches will be deleted once v2 becomes stable, keeping 1.x around though.

> Some branches are prefixed with "chore/", "feat/" or with "fix/", which is clever to provide organization. Those ones seem to be related to open pull requests or issues. Once again, however, I don't understand why a few branches maintain no prefix at all. In which degree of importance and category would it be considered as part of, for example, the branches: "wix-deep-link", "wry-git", "runner-config", "parking_lot"?

Most of the branches that don't use the feat fix prefixes are mine, mostly a force of habit because tools i used in the past (including vscode) _sometimes_ couldn't handle those but i never digged in so idk what the actual problem was. I started using them again.

> Considering that tags already cover the need of accessing old codebases, I would vote in favor of removing 1.1, 1.2, 1.3 branches, in order to keep only 1.5 and the dev.

Tags do _not_ cover everything here. We can't use the tags to release new patch versions for older minor versions (ignoring the fact that we kinda stopped doing that)

> The branches once again are named with prefixes, but some branches have no prefix at all. I don't understand if that means that one branch is more or less experimental, more or less important than the others, you know. "Uhh, if it is true to expect unprefixed branches, should i roll the entire list to search for keywords that are to be expected, like latest, dev or next? Or should I resort to prefix branches? What is this repo prioritizing?"

This is basically the same thing again but it sounds a bit extreme this time tbh. We _will_ try to improve branch names but i also don't see the importance of that for temporary branches tbh, it's not like there are actually "normal" users using them unless we explicitly ask them to.

> At the same time, branches related to version numbers also exist in the plugins-workspace: v1, v2, release-v2, and release.

> Do you see how the format of versioning is different here? While on tauri it is 1.5.x, on plugins-workspace it contains a "v" before the number, with no reference to any minor version.

Yes, because the repos are vastly different (and managed by different people). In plugins-workspace the version number is not talking about the repo's version, but the Tauri version (from the tauri repo) the branch belongs too.

> Also, it is not clear what is the difference between release-v2, release and v2. If v2 is not released yet, why does it exist release-v2? If release-v2 exists, does that mean that "release" refers to v1? What is more up-to-date: v1 or release-v1? Why does this repository prioritizes "v2" or "release-v2" instead of "dev"? Shouldn't the "release-v2" branch only exist when "v2" is actually released?

The release branches are solely for our release pipeline. I've renamed them to make that clearer.

> In tauri-docs, once again I see the "dev" branch mixed with "next" terminology. I suspect however that, in this case, "next" refers to the software, since there is also another branch named "astro-v4". However, as noted before, a branch named "next" could be confusing when down the list there is also a "dev" branch, because both can refer to the same meaning.

tauri-docs is under a heavy refactor right now so i will skip this section.

> In tao repository, there is "dev", "v.22.x" and "v0.16". It may be clear to devs working on the project, but as a newcomer, I find it especially difficult to reason where is it located the current "0.26.1" version, the main. If they are following numbers with a "v" prefix, why isn't there a v0.26.x branch, you see? There are branches for 0.22 and 0.16. What about 0.25, 0.24 and the other in between? (Actually I am not a fan of a branch for each minor version, I just question why some branches have it while others and the main don't). Does the "dev" branch mean the same as "main" here?

Yeah, can't tell much about that. But again, different people and it was kinda improvised. We're probably scared of breaking something so we'll leave those branches as they are until we don't need them anymore, but again contributors should not really be concerned about those.

----

Anyway, thank you for your feedback! I've already made some changes and we will keep to have it in mind.
