### ISSUE TITLE
[docs] Access Control List

### ISSUE THREAD

**Issue by wvq** [tauri-apps/tauri#9201]
The [Access Control List](https://beta.tauri.app/references/v2/acl/)  confuses me.

1. There is no description about `<command>:default`. eg: what permissions are `path:default` allowed ?

2. Is there any way to turn on all permissions without allowing them line by line.

**Comment by amrbashir** [comment]
1. this can vary for each plugin; it could be an empty set of permissions or could be a combination of permissions which the author of the plugin considers as the default permissions.
2. currently no, you need to enable whichever permissions you need

**Comment by amrbashir** [comment]
@tweidinger do you think we should add an `<plugin>:allow-all` for each plugin or maybe a way to just disable the ACL altogether, like adding a special permission called `allow-all` (without any prefix)?

**Comment by tweidinger** [comment]
@amrbashir hard no for the second suggestion, I think this would result in the same overexposure we can observe with the v1 in the wild (80%+ repos use `allow-all`this because it's easy and they never needed to learn about security). We should rather opt for more usable defaults in the plugins and better explanation for the path default values. We could consider `plugin:enable-all` for each plugin but it should be a case by case basis.
