### ISSUE TITLE
[bug] Flickering with raw display handle + winit + wgpu + tauri v2 + transparency

### ISSUE THREAD

**Issue by TrueDoctor** [tauri-apps/tauri#9220]
### Describe the bug

When running the following tauri app: https://github.com/FabianLars/tauri-v2-wgpu the webview and wgpu context "fight" for the surface resulting in flickering.  

https://github.com/tauri-apps/tauri/assets/21245806/02f2553e-01c1-4f72-8927-bc8653449289

### Reproduction

Clone https://github.com/FabianLars/tauri-v2-wgpu.
Add the following `flake.nix` file
[flake.nix.txt](https://github.com/tauri-apps/tauri/files/14649750/flake.nix.txt)
Run `nix develop`
Run `pnpm install`
Run `pnpm tauri dev`

### Expected behavior

The webview content should be overlaid on top of the wgpu surface.

### Full `tauri info` output

```text
[✔] Environment
    - OS: NixOS 23.11.0 X64
    ✔ webkit2gtk-4.1: 2.42.5
    ✔ rsvg2: 2.57.1
    ✔ rustc: 1.79.0-nightly (3c85e5624 2024-03-18)
    ✔ cargo: 1.79.0-nightly (2fe739fcf 2024-03-15)
    ✔ rustup: 1.26.0 (1980-01-01)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.11.1
    - pnpm: 8.15.3
    - npm: 10.2.4
    - bun: 1.0.25

[-] Packages
    - tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=feat/window-displayhandle#26558f77a8bab39cf320160a1f135f9bae6194d5 (2.0.0-beta.12)
    - tauri-build [RUST]: no manifest (2.0.0-beta.10, 2.0.0-beta.10)
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.2
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: build
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Additional context

Display manager: Hyprland
CPU: Ryzen 7 7840U Raedon 78M Graphics
Driver: mesa  23.1.9

I did have to disable DMABUF for webkit to get any render output

**Comment by amrbashir** [comment]
This is kinda expected because we are using GTK to create the window (which is basically an X11 window) and so it has its own drawing loop, when you add wgpu on top of it, they both fight on the same x11 surface hence the flickering, we can't really do anything to fix this as we need to use GTK for webviews.

**Comment by FabianLars** [comment]
@amrbashir Any idea why it doesn't seem to be a problem when using wry directly instead of tauri?
I basically copy pasted wry's wgpu example into the tauri app.

**Comment by amrbashir** [comment]
The WGPU example in wry is using `winit` along with the webview added as a child X11 window and the webview is rendered on the child surface, which is not the same as your example, which under the hood uses a GTK window and the webview is added as a widget to it so it is rendered on the window surface.

**Comment by FabianLars** [comment]
right lol, forgot that we're using winit there sry🏃

**Comment by TrueDoctor** [comment]
Any idea why transparency is not working for me when using the wry example? Or should I make a separate issue for that? @amrbashir

**Comment by Keavon** [comment]
> This is kinda expected because we are using GTK to create the window (which is basically an X11 window) and so it has its own drawing loop, when you add wgpu on top of it, they both fight on the same x11 surface hence the flickering, we can't really do anything to fix this as we need to use GTK for webviews.

That's very unfortunate, since this is a necessary feature for [Graphite](https://graphite.rs/) to adopt Tauri. Can you please bring this up with the team to brainstorm solutions/workarounds that could be employed in the Linux version? Having those listed here would at least allow community contributors to open a PR to fix this. And even if there's a technological impediment, shouldn't this issue remain open to track the defect so it can, at least someday, be solved? Thank you.

**Comment by TrueDoctor** [comment]
> Any idea why transparency is not working for me when using the wry example? Or should I make a separate issue for that? @amrbashir

Ah, I think that might just be https://github.com/tauri-apps/wry/issues/1139

**Comment by amrbashir** [comment]
> That's very unfortunate, since this is a necessary feature for [Graphite](https://graphite.rs/) to adopt Tauri. Can you please bring this up with the team to brainstorm solutions/workarounds that could be employed in the Linux version? Having those listed here would at least allow community contributors to open a PR to fix this.

Unfortunately, that is not in our hands to fix, we are limited to using Webkit2GTK on Linux and that requires a GTK window. While possible to add a GTK widget as a child X11 window inside raw X11 window, this is however a bit hacky and it is not possible on Wayland at all and so we can't use this method in Tauri.

How can Tauri still achieve multiple child webviews? We use a GTK window with a `gtk::Fixed` widget that allows to position multiple widgets at arbitrary positions, see this example in WRY https://github.com/tauri-apps/wry/blob/dev/examples/gtk_multiwebview.rs

Can you draw OpenGL into GTK? yes you can combine `gtk::Fixed` a `gtk::GlArea` widget and then add the webview widgets on top of it. The only problem here is that you will do the drawing yourself because popular rust crates doesn't support GTK at all and probably has no plans to.

**Comment by ibotty** [comment]
Is there a reason why webkit2gtk uses X11?  Can it also use wayland natively?

**Comment by FabianLars** [comment]
webkitgtk supports (and "uses") both x11 and wayland
