### ISSUE TITLE
[docs]  Does not resolve to a valid URL. Error

### ISSUE THREAD

**Issue by prasaanth2k** [tauri-apps/tauri#9482]
Whatever I import in `main.js`, I am getting these errors. Currently, I am trying to access the file system.

```
import { open } from "@tauri-apps/api/dialog";
const readfilecontents = async() => {
  try {
    const selectedpath = await open({
      multiple: false,
      title: "Open Text file",
    });
    console.log(selectedpath)
  } catch (error) {
    console.error(err);
  }
};
document.getElementById('openExplorerBtn').addEventListener('click', () => {
  readfilecontents();
});
```
![Screenshot from 2024-04-16 21-41-26](https://github.com/tauri-apps/tauri/assets/118121673/22faf8a1-c4de-40d4-9e68-e4d704cca89d)

Please help me correct this.

**Comment by TylerJMcLean** [comment]
Have you added @tauri-apps/api as a dependency for your project in your package.json/installed it via npm or whatever package manager you use? Is this a brand new project created with create-tauri-app, or are you adding this to an existing project?

**Comment by prasaanth2k** [comment]
```json
{
  "name": "brooker",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "tauri": "tauri"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.5.11"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.5.3",
    "@tauri-apps/plugin-dialog": "^2.0.0-beta.2"
  }
}

```
Yes i have added and installed with with npm

**Comment by FabianLars** [comment]
@mrintroverrt If you use tauri v2, the cli and api must be v2 too, if you use v1, then remove the plugin-dialog again.

That said, this is not the problem here. The problem is that you're trying to use npm packages without a bundler like vite or webpack, that's realistically not really possible.

If you don't want to use a bundler you can replace the `import` with this syntax
```ts
const { open } = window.__TAURI__.dialog;
```
(requires `withGlobalTauri` enabled in tauri.conf.json)
