### ISSUE TITLE
[bug] Invoke function takes unusually long time to return a large Vec<u8> image data.

### ISSUE THREAD

**Issue by deepushajia** [tauri-apps/tauri#9654]
### Describe the bug

I tracked all time of executions. The image was processed at rust end in a reasonable time but there exists an unusual delay between sending and receiving on the display built using React.

### Expected behavior

Fast Send.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 20.04 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.48.9
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ Cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.9.0
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.8
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0 (outdated, latest: 1.5.4)
    - @tauri-apps/cli [NPM]: 1.5.1 (outdated, latest: 1.5.12)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:3001/
    - framework: React
```

**Comment by FabianLars** [comment]
This is not something we can fix in v1, but one of the main things we worked on for v2. It's still not perfect, see https://github.com/tauri-apps/tauri/issues/9190

**Comment by FutureExcited** [comment]
Not sure if it's related, but currently I'm having the same trouble in Tauri v1, but with a regular text data - it takes insane amount of time to display. 

Now, the good thing is that I figured out that it happens when the window is not focused. The second I click on it again, it instantly shows. 

Obviously not saying this is the cause, but perhaps you have this type of problem as well, you should try refocusing the window again. 

As for this problem, I will make a new issue tomorrow morning to describe it.

**Comment by anuradhawick** [comment]
@FutureExcited I have similar experience. I have an app that runs in bg and window listens to events. Memory explodes out of proportions and I thought it was angular that was leaking out.

Any temp fix you got for this?

**Comment by FutureExcited** [comment]
@anuradhawick  Unfortunately not. I'd recommend to try your luck in their discord

**Comment by enddeadroyal** [comment]
I think the cause is that webview or tauri has limit the frontend memory size.
it is like be 2GB,
when I transfer 2GB data to frontend, its very quick.
but when it is beyond 2GB, it became very slow.
the log following

![Image](https://github.com/user-attachments/assets/9649e0da-ed08-42c2-88bb-f9dd77064ab7)

**Comment by FabianLars** [comment]
yeah, that's an issue for sure, though tbh i would have expected it to crash once it hits the 2gb mark. We cannot change the webview's 2gb memory usage limits btw (iirc all platforms have it around 2gb but may be misremembering it)
