### ISSUE TITLE
[bug] Encoded text cannot have a 6-bit remainder on iOS

### ISSUE THREAD

**Issue by yIllusionSky** [tauri-apps/tauri#9735]
### Describe the bug

I use fetch to send a Post request. It is successfully requested on Windows, Android, and Mac, but on iOS it reports an error `Encoded text cannot have a 6-bit remainder`.
My http part:
 {
       "identifier": "http:default",
       "all": true,
       "allow": [{ "url": "https://**" }]
     }

### Expected behavior

success get result

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.0-nightly (87293c958 2024-05-08)
    ✔ cargo: 1.80.0-nightly (0ca60e940 2024-05-08)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - bun: 1.0.36

[-] Packages
    - tauri [RUST]: 2.0.0-beta.19
    - tauri-build [RUST]: 2.0.0-beta.15
    - wry [RUST]: 0.39.5
    - tao [RUST]: 0.28.0
    - tauri-cli [RUST]: 2.0.0-beta.17
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.17

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' data:;; connect-src ipc: http://ipc.localhost
    - frontendDist: ../dist
    - devUrl: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams: None
```

**Comment by ankitvermaAT** [comment]
I am getting the same error in windows can you please help me out because I am having the same issue
while I had put environment variable value TAURI_PRIVATE_KEY and public key in tauri.config.json
still getting the same error, Please help to fix this?

**Comment by yIllusionSky** [comment]
> I am getting the same error in windows can you please help me out because I am having the same issue while I had put environment variable value TAURI_PRIVATE_KEY and public key in tauri.config.json still getting the same error, Please help to fix this?

I solved this problem. It seems to be a problem with the library. I used axios-tauri-http-adapter before, and then I used @tauri-apps/plugin-http directly without this problem.

**Comment by ankitvermaAT** [comment]
HI @yIllusionSky , firstly a big thanks for your reply.

1. But I am not using that library @tauri-apps/plugin-http
2. I found a mistake i.e. I was using .sig file file in server file instead of it's value.
3. **Now I am getting another error during updater (Verify signature error: UnexpectedKeyId) if you have any idea about this** error kindly suggest I am following below steps..

1. run : npm run tauri signer generate
2. Got public and private keys
3. Put public key in tauri.config.json (pubkey) node
4. Put private key in env file
5. run : npm run tauri build
6. Got update build (myapp_1.0.2_x64_en-US.msi.zip) and .mis.zip.sig files
Upload .mis.zip on server and update signature value in server json which is inside (.mis.zip.sig) 

Now I have my old version build i.e. 1.0.1 run this app and got that error (Verify signature error: UnexpectedKeyId)

I had used below packages:

"dependencies": {
"@tauri-apps/api": "^1.5.2",
"axios": "^1.6.7",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.22.1"
},
"devDependencies": {
"@tauri-apps/cli": "^1.5.8",
"@types/react": "^18.2.15",
"@types/react-dom": "^18.2.7",
"@vitejs/plugin-react": "^4.2.1",
"typescript": "^5.0.2",
"vite": "^5.0.0"
}

**Comment by yIllusionSky** [comment]
> HI @yIllusionSky , firstly a big thanks for your reply.
> 
> 1. But I am not using that library @tauri-apps/plugin-http
> 2. I found a mistake i.e. I was using .sig file file in server file instead of it's value.
> 3. **Now I am getting another error during updater (Verify signature error: UnexpectedKeyId) if you have any idea about this** error kindly suggest I am following below steps..
> 4. run : npm run tauri signer generate
> 5. Got public and private keys
> 6. Put public key in tauri.config.json (pubkey) node
> 7. Put private key in env file
> 8. run : npm run tauri build
> 9. Got update build (myapp_1.0.2_x64_en-US.msi.zip) and .mis.zip.sig files
>    Upload .mis.zip on server and update signature value in server json which is inside (.mis.zip.sig)
> 
> Now I have my old version build i.e. 1.0.1 run this app and got that error (Verify signature error: UnexpectedKeyId)
> 
> I had used below packages:
> 
> "dependencies": { "@tauri-apps/api": "^1.5.2", "axios": "^1.6.7", "react": "^18.2.0", "react-dom": "^18.2.0", "react-router-dom": "^6.22.1" }, "devDependencies": { "@tauri-apps/cli": "^1.5.8", "@types/react": "^18.2.15", "@types/react-dom": "^18.2.7", "@vitejs/plugin-react": "^4.2.1", "typescript": "^5.0.2", "vite": "^5.0.0" }

I have not used tauri 1.5.2. I have been using tauri 2.0 before. I don't understand your error. In 2.0, tauri cannot use axios directly. You need to use @tauri-apps/plugin-http. I am not very clear about 1.5.2. You can try to open an issue to see if anyone can solve it.
