### ISSUE TITLE
[docs]  Using Binary for Distribution and Arch Linux Packaging for Tauri Application

### ISSUE THREAD

**Issue by DenisVASI9** [tauri-apps/tauri#9812]
Hello Tauri Team,

I am currently developing a Tauri application and am considering distribution options for Linux. I understand that Tauri can package applications into AppImage format, but I have a specific distribution strategy in mind and would like to ask for your advice:

1. Is it possible to distribute a Tauri application as a standalone binary file without packaging it into an AppImage? I am looking for a way to provide my application as a simple executable that Linux users can run directly, bypassing the AppImage format. If this approach is supported, could you provide any details on how to extract or generate just the binary from a Tauri build?

2. In addition to the standalone binary, I am also interested in creating an Arch Linux package for my application. Ideally, I would like to make it available through the AUR (Arch User Repository) to facilitate easy installation for Arch users. Could you offer any guidance or point me to resources on how to create an Arch Linux package from a Tauri application binary?

I appreciate any help or insights you can provide on these topics. Your assistance will be instrumental in helping me tailor the distribution of my application to the needs of my users.

Thank you for your time and support.

**Comment by FabianLars** [comment]
1. Nope, at least as long as we use webkitgtk (and probably gtk itself too) this doesn't seem feasible sadly. We would _love_ it too though, especially because there's always some kind of problem with appimages.
2. https://github.com/tauri-apps/tauri/pull/8656 - https://github.com/tauri-apps/tauri/pull/4301 - https://github.com/tauri-apps/tauri-docs/pull/2146 (!) - Feedback on those PRs, especially the first 2 would be appreciated because we (or i) don't know what's best.

**Comment by RoseBlume** [comment]
1. As previously stated by Fabian Lars, webkit2gtk is a required runtime dependency which can not be included into the binary through normal means. 
2. If you want to distribute on the arch user repository it is relatively simple. You can extract the debian bundle and install all of the resources. After that you simply have to adjust your dependencies to include things like libsoup and webkit2gtk.
