### ISSUE TITLE
[bug] V2："Promise Rejection: shell.open not allowed"

### ISSUE THREAD

**Issue by lencx** [tauri-apps/tauri#9815]
### Describe the bug

Configured permissions but unable to open links in Webview (tauri::WebviewBuilder).

<img width="366" alt="Screenshot 2024-05-19 at 07 39 06" src="https://github.com/tauri-apps/tauri/assets/16164244/0faa57ae-ca85-447e-bd49-031c46b56511">

```json
{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "desktop-capability",
  "windows": ["*"],
  "platforms": ["linux", "macOS", "windows"],
  "permissions": [
    "webview:default",
    "webview:allow-internal-toggle-devtools",
    "webview:allow-set-webview-zoom",
    "window:default",
    "window:allow-create",
    "webview:allow-create-webview",
    "webview:allow-create-webview-window",
    "window:allow-start-dragging",
    "event:allow-emit",
    "event:allow-listen",
    "event:allow-unlisten",
    "shell:default",
    "shell:allow-execute",
    "shell:allow-open"
  ]
}
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 18.17.0
    - pnpm: 9.0.6
    - yarn: 1.22.19
    - npm: 9.6.7
    - bun: 1.0.36

[-] Packages
    - tauri [RUST]: 2.0.0-beta.18
    - tauri-build [RUST]: 2.0.0-beta.14
    - wry [RUST]: 0.39.4
    - tao [RUST]: 0.27.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.15

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by lindongchen** [comment]
I also encountered this issue, setting shell:allow-open is invalid with new webview. Can you please advise on how to resolve this issue. Thank you

**Comment by IsaiahTek** [comment]
Go to the `src-tauri/capabilities/` folder you will either see a migrated.json file if you migrated from v1 to v2 otherwise you will see a default.json file.

In that file, go to the **windows: [...]** line. By default, you will see only "main" there. So add the other window you want to call the shell.open from or the anything similar to that.
So it when edited it should look something like the below

```json
{
  "identifier": "...",
  "description": "...",
  "windows": ["main", "your-second-window-label-here"],
  "permissions": [
    "path:default",
    "event:default",
    "window:default",
    "app:default",
    "resources:default",
    "menu:default",
    "tray:default"
  ]
}
```


I encountered similar issue when trying to call the listen() of @tauri-apps/api/event function/method from a second window of my frontend after migrating from v1 to v2 and got that error. Did some searching online but no help seeing it's barely 2 weeks since v2 was released and most part of the documentation is still a Work In Progress (WIP). So that's how I managed to fix mine.
I hope that helps someone else in the future.
