### ISSUE TITLE
[bug] tauri::api::path::app_local_data_dir returning different paths in Microsoft Store packaged app

### ISSUE THREAD

**Issue by gezihuzi** [tauri-apps/tauri#9936]
### Describe the bug

`tauri::api::path::app_local_data_dir` API returning different paths when the app is packaged and installed from the Microsoft Store. In the development environment, it returns the expected local data directory path. However, the path changes in the Microsoft Store environment, which leads to inconsistency.

### Reproduction

1. Create a Tauri app.
2. Use `tauri::api::path::app_local_data_dir` to get the local data directory:
`let local_data_dir = tauri::api::path::app_local_data_dir(&config).unwrap_or_default();
println!("Local data directory: {:?}", local_data_dir);`

3. In the development environment, the retrieved path is:
`C:\Users\<username>\AppData\Local\app.<app_name>`
4. Package the app for Microsoft Store.
5. Install the app from Microsoft Store.
6. In the production environment, the path changes to:
`C:\Users\<username>\AppData\Local\Packages\<package_identifier>\LocalCache\Local\app.<app_name>`

### Expected behavior

`tauri::api::path::app_local_data_dir` API should return a path that is appropriate for both development and Microsoft Store environments. The API should handle the virtualized paths seamlessly in the Microsoft Store environment.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 125.0.2535.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.14.0
    - yarn: 1.22.19
    - npm: 10.7.0
    - bun: 1.1.10

[-] Packages
    - tauri [RUST]: 1.6.7
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.14
    - @tauri-apps/api [NPM]: 1.5.6
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:1427/
    - framework: Vue.js (Vue CLI)
    - bundler: Vite
```

### Additional context

This issue seems to be related to the sandboxed file system used by Microsoft Store applications, leading to path virtualization. Here’s a more detailed view of the paths being returned:

- Development environment path:
`\Users\Chen\AppData\Local\app.octoclip.v1 `

- Production (Microsoft Store) environment path:
`\Users\Chen\AppData\Local\Packages\34976Hypobenthos.Octoclip_tmpkfjqnyj9dr\LocalCache\Local\app.octoclip.v1`

Due to these differences, any files that are written or read from these paths are not consistent across environments, leading to operational issues in the production environment. It would be beneficial if the Tauri API could account for this virtualization and provide a unified path resolution.

**Comment by FabianLars** [comment]
Does this also concern the apis without the app_ prefix? (like config_dir / data_dir)

Or rather, does this actually cause issues when reading/writing files? (According to https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#appdata-operations-on-windows-10-version-1903-and-later it shouldn't)

Because if not i'd lean towards marking this as `wontfix` tbh since the upstream `dirs` crates use Windows' `SHGetKnownFolderPath` api for this and i'd assume escaping the sandbox here wouldn't be easy/nice. I could also imagine that this would cause issues with the Store approval process but i have no data to base this on 🤷

**Comment by amrbashir** [comment]
I believe this is due to the sandboxing limitations of Store packaged applications, nothing we can do here. Your app should operate on these directories without a problem.

However, if your app requires to operate on the filesystem unconditionally, then you'll need to provide the appropriate permissions in your manifest.

**Comment by gezihuzi** [comment]
> Does this also concern the apis without the app_ prefix? (like config_dir / data_dir)
> 
> Or rather, does this actually cause issues when reading/writing files? (According to https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#appdata-operations-on-windows-10-version-1903-and-later it shouldn't)
> 
> Because if not i'd lean towards marking this as `wontfix` tbh since the upstream `dirs` crates use Windows' `SHGetKnownFolderPath` api for this and i'd assume escaping the sandbox here wouldn't be easy/nice. I could also imagine that this would cause issues with the Store approval process but i have no data to base this on 🤷

---

`data_dir` has the same issue, `config_dir` has not been tested, guessing it is the same as `data_dir`.

The app can run normally, and the files in the above path can be read and written to normally, the only difference is that the file paths are different.

However, I found an issue. I use `app_local_data_dir` to obtain the application's local data folder, then concatenate paths to get the absolute path of a specific file in this folder. When trying to "Open" or "Show in file explorer," it prompts:

![image](https://github.com/tauri-apps/tauri/assets/12797966/934153fe-4d6d-41bd-a71f-0dac9858a069)

This is where I am confused, since the app can read and write normally, why does it report an error when performing other operations through absolute paths.

**Comment by onehumandev** [comment]
We are running into this same issue with our project as well.
We are packaging our product as MSIX so that we can publish as a sandboxed Microsoft Store app, with the goal of replacing a UWP app with a Tauri app.

As described above, the path for the app local data directory is different between MSIX and MSI installations.
By this, I do not mean the value returned by the `dirs` crate; I mean the actual folders created on the device when the app is installed.
MSIX appLocalData: `C:\Users\<username>\AppData\Local\Packages\<package_identifier>\`
MSI appLocalData: `C:\Users\<username>\AppData\Local\app.<app_name>`

If MSIX becomes an officially supported output from Tauri (per [this feature request](https://github.com/tauri-apps/tauri/issues/4818)), this difference will become quickly evident for any file access to the app local data.

As a possible solution, the `app_` methods could [determine the package identity](https://learn.microsoft.com/en-us/windows/msix/detect-package-identity) at runtime.
If the identity is present, it means the app is packaged as MSIX and will have a different path for some of their paths.
To clarify, I have not personally tested this path, but we likely will be investigating using this API call to handle the paths needed for our Tauri app.

**Comment by lucasfernog** [comment]
I don't think we can do much in this case, I agree with Fabian-Lars and Amr. Sandbox rules also apply on macOS and AppImages, and we shouldn't escape them. If you want consistency for dev/prod in this case you should resolve the path using a different mechanism - but I advise against it.

**Comment by wadamek65** [comment]
@onehumandev @gezihuzi did you perhaps manage to find a sensible workaround/approach for working with paths on packaged MSIX apps? Running into the same issue and I'm not sure where to go from here as even trying to debug this locally seems impossible.

**Comment by onehumandev** [comment]
@wadamek65  We have not yet had a chance to test this (working on other platforms presently), but I am planning to test the `ApplicationData.LocalFolder` method described [here](https://learn.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localfolder?view=winrt-26100#windows-storage-applicationdata-localfolder).

We are using `ApplicationData` already to read from [LocalSettings](https://learn.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localsettings?view=winrt-26100), so I have no reason to think `LocalFolder` won't work as well.

I can't guarantee when I'll have a chance to test this, so if you find a concrete answer in the meantime, please let me know :) Thanks!

**Comment by wadamek65** [comment]
@onehumandev Unfortunately, I wasn't able to find a decent workaround. What I ended up doing was just modify the AppxManifest with broader permissions and went through certification to use the exact same app data directory as normal tauri build would use.

```
        <virtualization:FileSystemWriteVirtualization>
            <virtualization:ExcludedDirectories>
                <virtualization:ExcludedDirectory>$(KnownFolder:LocalAppData)\com.myapp.app</virtualization:ExcludedDirectory>
                <virtualization:ExcludedDirectory>$(KnownFolder:RoamingAppData)\com.myapp.app</virtualization:ExcludedDirectory>
            </virtualization:ExcludedDirectories>
        </virtualization:FileSystemWriteVirtualization>
```

and

```
    <Capabilities>
        <rescap:Capability Name="runFullTrust" />
        <rescap:Capability Name="unvirtualizedResources" />
    </Capabilities>
```
