### ISSUE TITLE
[bug] tauri cli doesn't work without node installed

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#9939]
### Describe the bug

I use tauri cli in v2 project on Ubuntu 24.04 and I use `bun` install of `nodejs`.
After installing the packages, the command `bunx tauri dev` doesn't do anything.
when checking directly on the binary:

```console
user@user-VirtualBox:~/Documents/vibe/desktop$ ./node_modules/.bin/tauri
/usr/bin/env: ‘node’: No such file or directory
```

Looks like the cli is somehow hard coded to use node somewhere

### Reproduction

Use tauri cli while node is not installed on ubuntu (install with bun or similar)

### Full `tauri info` output

```text
No tauri info since it's not working.
But this is the version:
"@tauri-apps/cli": "^2.0.0-beta.17"
```

**Comment by pewsheen** [comment]
It depends on how you call it. If you call it from `bun ./node_modules/.bin/tauri`, it will use `bun` instead of `node`. By default, it will use `node`.

**Comment by thewh1teagle** [comment]
> After installing the packages, the command `bunx tauri dev` doesn't do anything.

In windows/macOS it works

**Comment by amrbashir** [comment]
I honestly want to say that this feels more like a bug in bun? I know bun tries to have compatibility with node and I believe they should cover this case as well?

Because the default runtime for so long has been (and probably will still be for more years) node and so changing the shebang here is not the solution.


I also found this issue https://github.com/oven-sh/bun/issues/3417 and even it is closed, they expressed that this will be fixed at some point in https://github.com/oven-sh/bun/issues/3417#issuecomment-1927842420
